<?php
declare(strict_types=1);
return [
    "CREATE TABLE pl_recurring_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, source_kind ENUM('ar','document','journal') NOT NULL, source_id BIGINT UNSIGNED NOT NULL, source_payload JSON NOT NULL, frequency ENUM('weekly','monthly','quarterly','yearly','days') NOT NULL, every_days INT NOT NULL DEFAULT 1, start_date DATE NOT NULL, end_date DATE NULL, max_runs INT NULL, lead_days INT NOT NULL DEFAULT 0, next_index INT NOT NULL DEFAULT 0, status ENUM('active','paused','ended') NOT NULL DEFAULT 'active', revision INT NOT NULL DEFAULT 1, creation_key VARCHAR(128) NOT NULL, creation_hash CHAR(64) NOT NULL, UNIQUE KEY uq_recurring_key(book_id,creation_key), UNIQUE KEY uq_recurring_scope(id,company_id,book_id), FOREIGN KEY(book_id,company_id) REFERENCES pl_books(id,company_id), FOREIGN KEY(actor_id) REFERENCES pl_users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    "CREATE TABLE pl_recurring_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, template_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, occurrence_date DATE NOT NULL, occurrence_index INT NOT NULL, template_revision INT NOT NULL, action ENUM('queued','skipped') NOT NULL, job_id BIGINT UNSIGNED NULL, reason VARCHAR(500) NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, UNIQUE KEY uq_recurring_occurrence(template_id,occurrence_index), FOREIGN KEY(template_id,company_id,book_id) REFERENCES pl_recurring_templates(id,company_id,book_id), FOREIGN KEY(job_id) REFERENCES pl_scheduler_jobs(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    "CREATE TABLE pl_release_schedules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, kind ENUM('prepaid','accrual','deferred') NOT NULL, balance_account_id BIGINT UNSIGNED NOT NULL, counterpart_account_id BIGINT UNSIGNED NOT NULL, funding_journal_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(20,4) NOT NULL, creation_key VARCHAR(128) NOT NULL, creation_hash CHAR(64) NOT NULL, UNIQUE KEY uq_release_key(book_id,creation_key), UNIQUE KEY uq_release_funding(book_id,funding_journal_id,balance_account_id), UNIQUE KEY uq_release_scope(id,company_id,book_id), FOREIGN KEY(book_id,company_id) REFERENCES pl_books(id,company_id), FOREIGN KEY(actor_id) REFERENCES pl_users(id), FOREIGN KEY(balance_account_id,company_id,book_id) REFERENCES pl_accounts(id,company_id,book_id), FOREIGN KEY(counterpart_account_id,company_id,book_id) REFERENCES pl_accounts(id,company_id,book_id), FOREIGN KEY(funding_journal_id,company_id,book_id) REFERENCES pl_journals(id,company_id,book_id), CHECK(amount>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    'CREATE TABLE pl_schedule_releases (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, schedule_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, due_date DATE NOT NULL, amount DECIMAL(20,4) NOT NULL, UNIQUE KEY uq_release_date(schedule_id,due_date), FOREIGN KEY(schedule_id,company_id,book_id) REFERENCES pl_release_schedules(id,company_id,book_id), CHECK(amount>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    'CREATE TABLE pl_schedule_audit (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, entity_type VARCHAR(30) NOT NULL, entity_id BIGINT UNSIGNED NOT NULL, action VARCHAR(30) NOT NULL, reason VARCHAR(500) NOT NULL, before_state JSON NULL, after_state JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(book_id,company_id) REFERENCES pl_books(id,company_id), FOREIGN KEY(actor_id) REFERENCES pl_users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    "CREATE TRIGGER pl_recurring_runs_no_update BEFORE UPDATE ON pl_recurring_runs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_recurring_runs_no_delete BEFORE DELETE ON pl_recurring_runs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_release_schedules_no_update BEFORE UPDATE ON pl_release_schedules FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_release_schedules_no_delete BEFORE DELETE ON pl_release_schedules FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_schedule_releases_no_update BEFORE UPDATE ON pl_schedule_releases FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_schedule_releases_no_delete BEFORE DELETE ON pl_schedule_releases FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_schedule_audit_no_update BEFORE UPDATE ON pl_schedule_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
    "CREATE TRIGGER pl_schedule_audit_no_delete BEFORE DELETE ON pl_schedule_audit FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Schedule history is immutable'",
];
