<?php
declare(strict_types=1);
return [
    'CREATE TABLE pl_loans (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL, lender_party_id BIGINT UNSIGNED NOT NULL, liability_account_id BIGINT UNSIGNED NOT NULL, interest_account_id BIGINT UNSIGNED NOT NULL, bank_account_id BIGINT UNSIGNED NOT NULL, accrued_account_id BIGINT UNSIGNED NOT NULL, funding_journal_id BIGINT UNSIGNED NOT NULL, principal DECIMAL(20,4) NOT NULL, start_date DATE NOT NULL, current_version INT NOT NULL DEFAULT 1, revision INT NOT NULL DEFAULT 1, creation_key VARCHAR(128) NOT NULL, creation_hash CHAR(64) NOT NULL, UNIQUE KEY uq_loan_key(book_id,creation_key), UNIQUE KEY uq_loan_funding(book_id,funding_journal_id,liability_account_id), UNIQUE KEY uq_loan_scope(id,company_id,book_id), FOREIGN KEY(book_id,company_id) REFERENCES pl_books(id,company_id), FOREIGN KEY(actor_id) REFERENCES pl_users(id), FOREIGN KEY(lender_party_id,company_id) REFERENCES pl_parties(id,company_id), CHECK(principal>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    "CREATE TABLE pl_loan_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, loan_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, version INT NOT NULL, method ENUM('reducing','flat','custom') NOT NULL, annual_rate DECIMAL(12,8) NOT NULL, term_months INT NOT NULL, effective_date DATE NOT NULL, principal DECIMAL(20,4) NOT NULL, payment DECIMAL(20,4) NOT NULL, reason VARCHAR(500) NOT NULL, actor_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_loan_version(loan_id,version), UNIQUE KEY uq_loan_version_scope(id,company_id,book_id), FOREIGN KEY(loan_id,company_id,book_id) REFERENCES pl_loans(id,company_id,book_id), CHECK(annual_rate>=0 AND term_months>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    'CREATE TABLE pl_loan_instalments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, version_id BIGINT UNSIGNED NOT NULL, loan_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, due_date DATE NOT NULL, principal DECIMAL(20,4) NOT NULL, interest DECIMAL(20,4) NOT NULL, closing_balance DECIMAL(20,4) NOT NULL, UNIQUE KEY uq_loan_instalment(version_id,due_date), FOREIGN KEY(version_id,company_id,book_id) REFERENCES pl_loan_versions(id,company_id,book_id), CHECK(principal>=0 AND interest>=0 AND closing_balance>=0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    'CREATE TABLE pl_loan_accruals (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, loan_id BIGINT UNSIGNED NOT NULL, version_id BIGINT UNSIGNED NOT NULL, company_id BIGINT UNSIGNED NOT NULL, book_id BIGINT UNSIGNED NOT NULL, period_id BIGINT UNSIGNED NOT NULL, due_date DATE NOT NULL, from_date DATE NOT NULL, reverse_on DATE NOT NULL, amount DECIMAL(20,4) NOT NULL, days_elapsed INT NOT NULL, UNIQUE KEY uq_loan_accrual(loan_id,period_id), FOREIGN KEY(loan_id,company_id,book_id) REFERENCES pl_loans(id,company_id,book_id), FOREIGN KEY(version_id,company_id,book_id) REFERENCES pl_loan_versions(id,company_id,book_id), CHECK(amount>0 AND days_elapsed>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    "CREATE TRIGGER pl_loan_versions_no_update BEFORE UPDATE ON pl_loan_versions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
    "CREATE TRIGGER pl_loan_versions_no_delete BEFORE DELETE ON pl_loan_versions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
    "CREATE TRIGGER pl_loan_instalments_no_update BEFORE UPDATE ON pl_loan_instalments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
    "CREATE TRIGGER pl_loan_instalments_no_delete BEFORE DELETE ON pl_loan_instalments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
    "CREATE TRIGGER pl_loan_accruals_no_update BEFORE UPDATE ON pl_loan_accruals FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
    "CREATE TRIGGER pl_loan_accruals_no_delete BEFORE DELETE ON pl_loan_accruals FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Loan history is immutable'",
];
