<?php declare(strict_types=1);
$statuses=['draft'=>'Draft','unpaid'=>'Unpaid','overdue'=>'Overdue','paid'=>'Paid','reversed'=>'Reversed','all'=>'All'];
$ageLabels=['not_due'=>'Not due','1_30'=>'1–30','31_60'=>'31–60','61_90'=>'61–90','over_90'=>'90+'];
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header($isAr?pl_t('Invoices'):pl_t('Bills'),pl_t('{outstanding} outstanding · {overdue} overdue',['outstanding'=>$company['currency'].' '.pl_money($report['total_base']),'overdue'=>pl_money($report['overdue_base'])]),static function () use ($company,$path,$isAr,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/parties')) ?>"><?= pl_e($isAr?pl_t('Customers'):pl_t('Suppliers')) ?></a>
<?php if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url($path,['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> <?= pl_e($isAr?pl_t('New invoice'):pl_t('New bill')) ?></a><?php endif; ?>
<?php }); ?>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<div class="split-view"><section class="split-view-list<?= isset($_GET['select'])?' has-detail':'' ?>" aria-label="<?= pl_e($isAr?pl_t('Invoice list'):pl_t('Bill list')) ?>">
<nav class="tabs-seg mb-3" aria-label="<?= pl_e(pl_t('Document status')) ?>"><?php foreach ($statuses as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_workflow_url($path,array_replace($filters,['status'=>$key,'page'=>1]))) ?>"<?= $filters['status']===$key?' aria-current="page"':'' ?>><?= pl_e(pl_t($label)) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_workflow_url($path)) ?>"><input type="hidden" name="status" value="<?= pl_e($filters['status']) ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button><details class="date-filters"><summary><?= pl_e(pl_t('Date range')) ?></summary><div><label><?= pl_e(pl_t('From')) ?> <input type="date" name="from" value="<?= pl_e($filters['from']) ?>"></label><label><?= pl_e(pl_t('To')) ?> <input type="date" name="to" value="<?= pl_e($filters['to']) ?>"></label><button class="btn btn-secondary"><?= pl_e(pl_t('Apply dates')) ?></button></div></details></form>
<div class="rounded-panel border border-border bg-surface px-4 py-3 mb-3"><div class="ageing-strip" aria-label="<?= pl_e(pl_t('Ageing summary')) ?>"><?php foreach ($ageLabels as $key=>$label): ?><a class="ageing-item" href="<?= pl_e(pl_url('/reports/ageing',['direction'=>$isAr?'receivable':'payable','as_of'=>$report['as_of']])) ?>"><span class="ageing-item-label"><?= pl_e(pl_t($label)) ?></span><span class="ageing-item-value"><?= pl_e(pl_money($report['buckets'][$key])) ?></span></a><?php endforeach; ?></div><p class="text-xs text-ink-muted mt-2"><?= pl_e($report['reconciled']?pl_t('Control accounts reconcile to open items.'):pl_t('Control accounts and open items differ. Review the ageing report.')) ?> <a class="link" href="<?= pl_e(pl_url('/reports/ageing',['direction'=>$isAr?'receivable':'payable','as_of'=>$report['as_of']])) ?>"><?= pl_e(pl_t('Review ageing and reconciliation')) ?></a></p></div>
<div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e($isAr?pl_t('Invoices and customer credits'):pl_t('Bills and supplier credits')) ?></caption><thead><tr>
<?php foreach (['date'=>'Document / date','name'=>$isAr?pl_t('Customer'):pl_t('Supplier'),'amount'=>'Amount'] as $key=>$label): ?><th scope="col"<?= $key==='amount'?' class="text-end"':'' ?>><?php pl_ui_sort($path,$filters,$key,$key==='name'?$label:pl_t($label)); ?></th><?php endforeach; ?><th scope="col"><?= pl_e(pl_t('Status')) ?></th></tr></thead><tbody>
<?php foreach ($list['documents'] as $row): $selected=$selection && $selection['id']===$row['id']; ?><tr<?= $selected?' class="selected"':'' ?>><td><a class="record-link" data-record-link href="<?= pl_e(pl_workflow_url($path,array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selected?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['number']) ?></span><span class="row-sub"><?= pl_e(pl_date_label($row['document_date'])) ?></span></a></td><td><?= pl_e($row['party']['legal_name']) ?></td><td class="amount"><?= pl_e($row['currency'].' '.pl_money($row['total'])) ?></td><td><?php pl_ui_badge(str_replace('_','-',$row['payment_status']??$row['status'])); ?></td></tr><?php endforeach; ?></tbody></table>
<?php if (!$list['documents']): pl_ui_empty(pl_t('No matching documents.'),pl_t('Choose another status or adjust the search and dates.')); endif; ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= pl_e(pl_t('{total} records',['total'=>(int)$list['total']])) ?></span><?php pl_ui_pagination($path,$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_e(pl_t('These are sample records in a separate sample company.')) ?></p><?php endif; ?>
</section>
<?php pl_ui_side_panel($isAr?pl_t('Invoice details'):pl_t('Bill details'),static function () use ($selection,$selectionJournal,$path,$filters,$company,$isAr): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_workflow_url($path,$filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to list')) ?></a>
<?php if ($selection): ?><div class="border-b border-border px-5 py-4"><div class="flex flex-wrap items-center gap-2 mb-2"><h2 class="text-base font-semibold"><?= pl_e($selection['number']) ?></h2><?php pl_ui_badge(str_replace('_','-',$selection['payment_status']??$selection['status'])); ?></div><div class="flex flex-wrap justify-between items-end gap-3"><h3 class="text-sm text-ink-muted"><?= pl_e($selection['party']['legal_name']) ?></h3><p class="amount-lg"><?= pl_e($selection['currency'].' '.pl_money($selection['total'])) ?></p></div></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4">
<?php pl_ui_tabs([pl_t('Details')=>'#ar-details',pl_t('Journal')=>'#ar-journal',pl_t('History')=>'#ar-history'],pl_t('Details'),true); ?>
<section id="ar-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Document date'=>pl_date_label($selection['document_date']),'Due date'=>$selection['due_date']?pl_date_label($selection['due_date']):'—','Entered prices'=>$selection['price_mode']==='inclusive'?pl_t('Include tax'):pl_t('Exclude tax'),'Reference'=>$selection['reference']?:'—','Remaining'=>$selection['currency'].' '.pl_money($selection['outstanding_fc'])] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl></section>
<section id="ar-journal" class="py-3" data-ui-tab-panel><?php if ($selectionJournal): pl_ui_table([pl_t('Account'),pl_t('Debit'),pl_t('Credit')],static function () use ($selectionJournal): void { foreach ($selectionJournal['lines'] as $line): ?><tr><td><?= pl_e($line['code'].' · '.$line['name']) ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; },pl_t('Posted journal')); ?><a class="link text-sm" href="<?= pl_e(pl_url('/journals/detail',['id'=>$selectionJournal['id']])) ?>"><?= pl_e(pl_t('Open journal')) ?></a><?php else: ?><p class="text-sm text-ink-muted"><?= pl_e(pl_t('This saved draft does not change your books. Open the editor to review its posting preview.')) ?></p><?php endif; ?></section>
<section id="ar-history" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach ($selection['history'] as $revision): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Revision {number}',['number'=>(int)$revision['revision']])) ?></dt><dd><?= pl_e($revision['reason']) ?> · <time data-local-time datetime="<?= pl_e(str_replace(' ','T',$revision['recorded_at']).'Z') ?>"><?= pl_e(pl_t('{time} UTC',['time'=>$revision['recorded_at']])) ?></time></dd></div><?php endforeach; ?><?php if (!$selection['history']): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Draft')) ?></dt><dd><?= pl_e(pl_t('No posting yet.')) ?></dd></div><?php endif; ?></dl></section></div>
<div class="panel-actions"><a class="link text-sm" href="<?= pl_e(pl_workflow_url($path,['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('View full record')) ?></a>
<?php if (pl_can_write($company) && $selection['status']==='draft'): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url($path,['id'=>$selection['id'],'edit'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Edit draft')) ?></a>
<?php elseif (pl_can_write($company) && !$selection['is_credit'] && !$selection['reversal_journal_id'] && bccomp($selection['outstanding_fc'],'0',4)>0): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url($path,['settle'=>'1','party_id'=>$selection['party_id'],'currency'=>$selection['currency']])) ?>"><?= pl_e($isAr?pl_t('Record receipt'):pl_t('Record payment')) ?></a><?php endif; ?></div>
<?php else: pl_ui_empty(pl_t('Every document tells a story.'),pl_t('Choose a document to see its details and how it appears in your books.')); endif; ?>
<?php }); ?></div>
<div class="flex flex-wrap gap-3 text-sm"><a class="link" href="<?= pl_e(pl_workflow_url($path,['settle'=>'1'])) ?>"><?= pl_e($isAr?pl_t('Record customer receipt'):pl_t('Record supplier payment')) ?></a><a class="link" href="<?= pl_e(pl_url('/opening-conversion')) ?>"><?= pl_e(pl_t('Convert unpaid opening documents')) ?></a><a class="link" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_e(pl_t('Bank reconciliation')) ?></a></div>
<?php if ($company['role']==='owner'): ?><details><summary class="text-sm"><?= pl_e(pl_t('Activate an unused control account')) ?></summary><p class="text-xs text-ink-muted my-3"><?= pl_e(pl_t('Existing opening balances require the reviewed opening-debt conversion.')) ?></p><form method="post" action="<?= pl_e(pl_workflow_url($path,['return_filters'=>$filters])) ?>"><?php pl_starter_form($company,'activate'); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_select(pl_t('Control account'),'account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['role']===($isAr?'receivables':'payables')&&!$a['open_item_managed']))); pl_starter_field(pl_t('Reason'),'reason'); ?></div><button class="btn btn-secondary mt-3"><?= pl_e(pl_t('Activate control account')) ?></button></form></details><?php endif; ?>
</div>
