<?php declare(strict_types=1);
$recordStatus=str_replace('_','-',$document['payment_status']??$document['status']);
$canAct=pl_can_write($company);
$canSettle=$document['kind']===$normalKind && $document['journal_id'] && !$document['reversal_journal_id'] && bccomp($document['outstanding_fc'],'0',4)>0;
$names=pl_starter_options($accounts);
?>
<div class="py-5">
<a class="btn btn-ghost mb-3" href="<?= pl_e(pl_workflow_url($path,$filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to {target}', ['target' => $isAr ? pl_t('invoices') : pl_t('bills')])) ?></a>
<section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header($document['number'],$recordStatus,static function () use ($document,$path,$canAct,$canSettle,$isAr,$filters): void { ?>
<button class="btn btn-ghost" type="button" data-print-document hidden><?= pl_icon('printer') ?> <?= pl_e(pl_t('Print')) ?></button>
<?php if ($canAct && $document['status']==='draft'): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url($path,['id'=>$document['id'],'edit'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Edit draft')) ?></a><?php endif; ?>
<?php if ($canAct && $canSettle): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url($path,['new'=>'1','credit_for'=>$document['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Create {type}', ['type' => $isAr ? pl_t('credit note') : pl_t('supplier credit')])) ?></a><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url($path,['settle'=>'1','party_id'=>$document['party_id'],'currency'=>$document['currency']])) ?>"><?= pl_e($isAr?pl_t('Record customer receipt'):pl_t('Record supplier payment')) ?></a><?php endif; ?>
<?php if ($document['reversal_journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/journals/detail',['id'=>$document['reversal_journal_id']])) ?>"><?= pl_e(pl_t('View reversing entry')) ?></a><?php endif; ?>
<?php }); ?>
<div class="doc-body">
<?php if($document['status']==='posted' && !$document['reversal_journal_id'] && in_array($document['kind'],['invoice','bill'],true) && pl_user_can((int)$user['id'],(int)$company['id'],'schedules.manage')): ?><p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/recurring').'?source_kind=ar&source_id='.(int)$document['id']) ?>"><?= pl_e(pl_t('Make recurring')) ?></a></p><?php endif ?>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<?php if ($document['reversal_journal_id']): pl_ui_strip(pl_t('This document has been reversed. Its original posting and linked reversal remain in the history.'),'warning'); endif; ?>
<section><p class="text-sm text-ink-muted mb-3"><?= pl_e($company['name'].' · '.ucwords(str_replace('_',' ',$document['kind']))) ?></p>
<dl class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php foreach ([($isAr?pl_t('Customer'):pl_t('Vendor'))=>$document['party']['legal_name'],pl_t('Document date')=>pl_date_label($document['document_date']),pl_t('Due date')=>pl_date_label($document['due_date']),pl_t('Currency')=>$document['currency'],pl_t('Entered prices')=>$document['price_mode']==='inclusive'?pl_t('Include tax'):pl_t('Exclude tax'),pl_t('Reference')=>$document['reference']?:'—',pl_t('Terms')=>$document['terms']?:'—',pl_t('Revision')=>(string)$document['revision']] as $label=>$value): ?><div><dt class="field-label"><?= pl_e($label) ?></dt><dd class="text-sm font-medium mt-0.5"><?= pl_e($value) ?></dd></div><?php endforeach; ?>
</dl></section>
<?php if ($document['is_credit'] && $original): ?><p class="text-sm"><?= pl_e(pl_t('Credit against')) ?> <a class="link" href="<?= pl_e(pl_workflow_url($path,['id'=>$original['id']])) ?>"><?= pl_e($original['number']) ?></a><?= pl_e(pl_t(', original revision {revision}.', ['revision' => (int)$document['original_revision']])) ?></p><?php endif; ?>
<?php if ($purchaseSources): ?><section><h2 class="section-title mb-2"><?= pl_e(pl_t('Purchasing source')) ?></h2>
<?php pl_ui_table([pl_t('Purchase order'),pl_t('Goods receipt'),pl_t('Bill line'),pl_t('Matched quantity'),pl_t('Return')],static function () use ($purchaseSources): void { foreach ($purchaseSources as $source): ?><tr>
<td><a class="link" href="<?= pl_e(pl_workflow_url('/purchasing',['id'=>$source['order_id']])) ?>"><?= pl_e(pl_t('PO-{number}', ['number' => str_pad((string)$source['order_id'],6,'0',STR_PAD_LEFT)])) ?></a><span class="row-sub"><?= pl_e($source['order_reference']) ?></span></td>
<td><a class="link" href="<?= pl_e(pl_workflow_url('/purchasing',['id'=>$source['order_id'],'receipt_line'=>$source['receipt_line_id']]).'#receipt-line-'.$source['receipt_line_id']) ?>"><?= pl_e(pl_t('Receipt {id}', ['id' => (int)$source['receipt_id']])) ?></a><span class="row-sub"><?= pl_e(pl_date_label($source['document_date'])) ?></span></td>
<td><?= (int)$source['bill_line_number'] ?></td><td class="amount"><?= pl_e($source['quantity']) ?></td><td><?= pl_e($source['returned_by_credit']?pl_t('Physical return linked to this credit'):pl_t('Review receipt history')) ?></td></tr><?php endforeach; },pl_t('Supplier document purchasing sources')); ?>
<p class="text-xs text-ink-muted mt-3"><?= pl_e(pl_t('To return physical goods, open the goods receipt and use its return action. It records the stock movement and, for billed goods, the linked supplier credit together. A separately entered supplier credit changes the payable balance only; it does not return stock.')) ?></p>
</section><?php endif; ?>
<section><h2 class="section-title mb-2"><?= pl_e(pl_t('Lines')) ?></h2>
<?php pl_ui_table([pl_t('Line / description'),pl_t('Account'),pl_t('Quantity'),pl_t('Entered unit price'),pl_t('Tax'),pl_t('Net')],static function () use ($document,$names): void { foreach ($document['lines'] as $line): ?><tr><td><span class="row-title"><?= pl_e($line['description']) ?></span><span class="row-sub"><?= pl_e(pl_t('Line {number}', ['number' => (int)$line['line_number']])) ?></span></td><td><?= pl_e($names[$line['account_id']]??pl_t('Account {id}', ['id' => $line['account_id']])) ?></td><td class="amount"><?= pl_e($line['quantity']) ?></td><td class="amount"><?= pl_e(pl_money($line['unit_price'])) ?></td><td class="amount"><?= pl_e(pl_money($line['tax_amount'])) ?><span class="row-sub"><?= pl_e($line['tax_label']??'') ?></span></td><td class="amount"><?= pl_e(pl_money($line['line_total'])) ?></td></tr><?php endforeach; },pl_t('Document lines')); ?>
<div class="flex flex-wrap justify-between items-start gap-4 mt-3">
<dl class="dgrid"><?php if ($document['journal_id'] && !$document['is_credit'] && !$document['reversal_journal_id']): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Amount remaining')) ?></dt><dd class="amount"><?= pl_e($document['currency'].' '.pl_money($document['outstanding_fc'])) ?></dd></div><?php endif; ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Notes')) ?></dt><dd><?= pl_e($document['notes']?:'—') ?></dd></div></dl>
<?php pl_ui_totals([pl_t('Subtotal')=>pl_money($document['subtotal']),pl_t('Tax')=>pl_money($document['tax_total']),pl_t('Total ({currency})',['currency'=>$document['currency']])=>pl_money($document['total'])]); ?></div>
<p class="text-xs text-ink-muted mt-2"><?= pl_e($document['status']==='draft'?pl_t('Posting adds this transaction to reports. A saved draft does not change your books.'):pl_t('Net, tax and total are preserved from the posted revision. Posted entries cannot be edited.')) ?></p></section>
<?php if ($canAct && $document['status']==='draft'): ?><section><h2 class="section-title mb-2"><?= pl_e(pl_t('Post saved draft')) ?></h2><form method="post" action="<?= pl_e(pl_workflow_url($path,['return_filters'=>$filters])) ?>"><?php pl_starter_form($company,'post',['id'=>$document['id'],'revision'=>$postInput['revision']??$document['revision'],'request_key'=>$postInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field(pl_t('Manual exchange rate (blank for domestic or recorded rate)'),'rate',$postInput['rate']??'','text',false); ?></div><button class="btn btn-primary mt-3"><?= pl_e(pl_t('Post {kind}', ['kind' => str_replace('_',' ',$document['kind'])])) ?></button></form></section><?php endif; ?>
<?php if ($recordJournal): ?><section><h2 class="section-title mb-2"><?= pl_e(pl_t('Journal effect')) ?></h2><?php pl_ui_table([pl_t('Account'),pl_t('Debit ({currency})',['currency'=>$company['currency']]),pl_t('Credit ({currency})',['currency'=>$company['currency']])],static function () use ($recordJournal): void { foreach ($recordJournal['lines'] as $line): ?><tr><td><?= pl_e($line['code'].' · '.$line['name']) ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; },pl_t('Posted financial journal')); ?><a class="link text-sm" href="<?= pl_e(pl_workflow_url('/journals/detail',['id'=>$document['journal_id']])) ?>"><?= pl_e(pl_t('View journal and source reference')) ?></a></section><?php endif; ?>
<?php if ($settlements): ?><section><h2 class="section-title mb-2"><?= pl_e(pl_t('Ledger activity')) ?></h2>
<?php foreach ($settlements as $entry): ?><div class="border-b border-border py-3"><p class="text-sm"><a class="link" href="<?= pl_e(pl_workflow_url('/journals/detail',['id'=>$entry['journal_id']])) ?>"><?= pl_e($entry['posting_date'].' · '.ucfirst(str_replace('_',' ',$entry['kind']))) ?></a> · <span class="amount"><?= pl_e($document['currency'].' '.pl_money($entry['amount_fc'])) ?></span><?= $entry['already_reversed']?' · '.pl_e(pl_t('Reversed')):'' ?></p>
<?php if ($entry['credit_document_id']): ?><a class="link text-sm" href="<?= pl_e(pl_workflow_url($path,['id'=>$entry['credit_document_id']])) ?>"><?= pl_e(pl_t('View {number}', ['number' => pl_ar_document_display_number((int)$entry['credit_document_id'],$entry['credit_kind'])])) ?></a><?php endif; ?>
<?php if ($canAct && $document['kind']===$normalKind && !$entry['already_reversed'] && !$entry['credit_document_id'] && in_array($entry['source_type'],['open_item_settlement','open_item_batch_settlement'],true) && $entry['kind']==='allocation'): $paymentReversal=$failedAction==='reverse_payment' && (int)($form['input']['journal_id']??0)===(int)$entry['journal_id']?$form['input']:[]; ?><details class="mt-2" <?= $paymentReversal?'open':'' ?>><summary class="text-sm"><?= pl_e(pl_t('Reverse this payment')) ?></summary><p class="text-xs text-ink-muted my-3"><?= pl_e(pl_t('This reverses the whole payment and all its allocations, including allocations to other documents.')) ?></p><form method="post" action="<?= pl_e(pl_workflow_url($path,['return_filters'=>$filters])) ?>"><?php pl_starter_form($company,'reverse_payment',['id'=>$document['id'],'journal_id'=>$entry['journal_id'],'request_key'=>$paymentReversal['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field(pl_t('Reason'),'reason',$paymentReversal['reason']??''); pl_starter_field(pl_t('Reversal date (blank = today)'),'date',$paymentReversal['date']??'','date',false); ?></div><button class="btn btn-secondary mt-3"><?= pl_e(pl_t('Reverse payment')) ?></button></form></details><?php endif; ?></div><?php endforeach; ?></section><?php endif; ?>
<?php if ($canAct && $document['journal_id'] && !$document['reversal_journal_id']): ?><section><details <?= $reverseInput?'open':'' ?>><summary class="section-title"><?= pl_e(pl_t('Correction and cancellation')) ?></summary><p class="text-xs text-ink-muted my-3"><?= pl_e(pl_t('Corrections keep the document identity and create a linked reversal and replacement. Dependent payments and credits must be reversed first. Bank-reconciled entries and closed periods remain protected.')) ?></p><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url($path,['id'=>$document['id'],'correct'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Correct this document under the same identity')) ?></a><form class="mt-4" method="post" action="<?= pl_e(pl_workflow_url($path,['return_filters'=>$filters])) ?>"><?php pl_starter_form($company,'reverse',['id'=>$document['id'],'request_key'=>$reverseInput['request_key']??bin2hex(random_bytes(20))]); ?><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php pl_starter_field(pl_t('Reason'),'reason',$reverseInput['reason']??''); pl_starter_field(pl_t('Reversal date (blank = today)'),'date',$reverseInput['date']??'','date',false); ?></div><button class="btn btn-secondary mt-3"><?= pl_e(pl_t('Reverse document')) ?></button></form></details></section><?php endif; ?>
<section><h2 class="section-title mb-2"><?= pl_e(pl_t('History')) ?></h2><dl class="dgrid"><?php foreach ($document['history'] as $revision): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Revision {number}', ['number' => (int)$revision['revision']])) ?></dt><dd><a class="link" href="<?= pl_e(pl_workflow_url('/journals/detail',['id'=>$revision['journal_id']])) ?>"><?= pl_e(pl_t('Journal {id}', ['id' => (int)$revision['journal_id']])) ?></a> · <?= pl_e($revision['reason']) ?> · <time data-local-time datetime="<?= pl_e(str_replace(' ','T',$revision['recorded_at']).'Z') ?>"><?= pl_e(pl_t('{timestamp} UTC', ['timestamp' => $revision['recorded_at']])) ?></time></dd></div><?php endforeach; ?><?php if (!$document['history']): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Draft')) ?></dt><dd><?= pl_e(pl_t('No posting yet.')) ?></dd></div><?php endif; ?></dl></section>
<p class="text-xs text-ink-muted"><?= pl_e(pl_t('Use your browser’s Print command for this document.')) ?></p>
</div></section></div>
