<?php declare(strict_types=1);
// Stock locations panel: directory, add or edit a warehouse, and transfer stock at carrying value. Rendered only when the module is enabled.
$warehouseInput=($submitted['action']??'')==='warehouse'?$submitted:[]; $transferInput=($submitted['action']??'')==='transfer'?$submitted:[];
$editing=$warehouse_filter?($warehouseById[$warehouse_filter]??null):null; $values=$warehouseInput?:($editing?:['is_active'=>'1']); ?>
<details class="rounded-panel border border-border bg-surface p-4" <?= $warehouseInput||$transferInput||$warehouse_filter?'open':'' ?>><summary class="section-title">Stock locations</summary>
<p class="text-sm my-3">Every book has a permanent default warehouse. Add warehouses or vans, then move stock between them; transfers carry the source's average cost and never post to the ledger.</p>
<?php pl_ui_table(['Code','Location','Status','Stock'],static function () use ($warehouses,$filters): void { foreach ($warehouses as $w): ?><tr><td><?= pl_e($w['code']) ?></td><td><?= pl_e($w['name']) ?><?php if ($w['is_default']): ?> <span class="badge">Default</span><?php endif; ?></td><td><?php pl_ui_badge($w['is_active']?'active':'inactive'); ?></td><td><a class="link" href="<?= pl_e(pl_url('/inventory',array_replace($filters,['warehouse'=>$w['id']]))) ?>">View stock</a></td></tr><?php endforeach; },'Stock locations'); ?>
<?php if ($write): ?>
<div class="grid md:grid-cols-2 gap-4 mt-4">
<form method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>" class="flex flex-col gap-3"><h3 class="section-title"><?= $editing?'Edit '.pl_e($editing['name']):'Add a warehouse or van' ?></h3><?php pl_ui_return_filters($filters); pl_starter_form($company,'warehouse',['warehouse_id'=>$warehouseInput['warehouse_id']??($editing['id']??''),'revision'=>$warehouseInput['revision']??($editing['revision']??''),'request_key'=>$warehouseInput['request_key']??null]); ?>
<div class="grid grid-cols-2 gap-4"><?php if ($editing && !$warehouseInput): ?><label class="field"><span>Code</span><input class="input" name="code" value="<?= pl_e((string)$editing['code']) ?>" readonly></label><?php else: ?><?php pl_starter_field('Code','code',$values['code']??''); ?><?php endif; pl_starter_field('Name','name',$values['name']??''); pl_starter_field('Reason','reason',$warehouseInput['reason']??''); ?></div>
<p><label><input type="checkbox" name="is_active" value="1" <?= ($warehouseInput?($warehouseInput['is_active']??'')==='1':($values['is_active']??true))?'checked':'' ?>> Active for new stock movements</label></p>
<div class="flex gap-2"><button class="btn btn-secondary">Save location</button><?php if ($editing): ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/inventory',$filters)) ?>">Add a new one instead</a><?php endif; ?></div></form>
<form method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>" class="flex flex-col gap-3"><h3 class="section-title">Transfer stock between locations</h3><?php pl_ui_return_filters($filters); pl_starter_form($company,'transfer',['request_key'=>$transferInput['request_key']??null]); ?>
<div class="grid grid-cols-2 gap-4"><?php pl_starter_select('From','from_warehouse_id',$warehouseOptions,$transferInput['from_warehouse_id']??($warehouse_filter??'')); pl_starter_select('To','to_warehouse_id',$warehouseOptions,$transferInput['to_warehouse_id']??''); pl_starter_select('Stock product','product_id',pl_starter_options($stockProducts),$transferInput['product_id']??''); pl_starter_field('Quantity in base units','quantity',$transferInput['quantity']??''); pl_starter_field('Date','date',$transferInput['date']??gmdate('Y-m-d'),'date'); pl_starter_field('Source reference','reference',$transferInput['reference']??''); pl_starter_field('Reason','reason',$transferInput['reason']??''); ?></div>
<p class="text-xs text-ink-muted">An insufficient quantity in the source location is rejected and your entries are retained.</p><button class="btn btn-secondary">Record transfer</button></form>
</div><?php endif; ?></details>
