<?php declare(strict_types=1);
// Stock locations panel: directory, add or edit a warehouse, and transfer stock at carrying value. Rendered only when the module is enabled.
$warehouseInput=($submitted['action']??'')==='warehouse'?$submitted:[]; $transferInput=($submitted['action']??'')==='transfer'?$submitted:[];
$editing=$warehouse_filter?($warehouseById[$warehouse_filter]??null):null; $values=$warehouseInput?:($editing?:['is_active'=>'1']); ?>
<details class="rounded-panel border border-border bg-surface p-4" <?= $warehouseInput||$transferInput||$warehouse_filter?'open':'' ?>><summary class="section-title"><?= pl_e(pl_t('Stock locations')) ?></summary>
<p class="text-sm my-3"><?= pl_e(pl_t('Every book has a permanent default warehouse, which is always a building. Add warehouses or vans, then move stock between them; transfers carry the source\'s average cost and never post to the ledger. A van is a stock location that travels: it carries a driver, a vehicle and a route, and stock issued to it is still your stock.')) ?></p>
<?php pl_ui_table([pl_t('Code'),pl_t('Location'),pl_t('Kind'),pl_t('Driver / vehicle'),pl_t('Status'),pl_t('Stock')],static function () use ($warehouses,$filters): void { foreach ($warehouses as $w): ?><tr><td><?= pl_e($w['code']) ?></td><td><?= pl_e($w['name']) ?><?php if ($w['is_default']): ?> <span class="badge"><?= pl_e(pl_t('Default')) ?></span><?php endif; ?></td><td><?= pl_e(pl_inventory_warehouse_kinds()[$w['kind']] ?? $w['kind']) ?></td><td><?= pl_e(trim(($w['driver_name'] ?? '').' · '.($w['vehicle_reference'] ?? '').' · '.($w['route_name'] ?? ''),' ·')) ?></td><td><?php pl_ui_badge($w['is_active']?'active':'inactive'); ?></td><td><a class="link" href="<?= pl_e(pl_url('/inventory',array_replace($filters,['warehouse'=>$w['id']]))) ?>"><?= pl_e(pl_t('View stock')) ?></a></td></tr><?php endforeach; },pl_t('Stock locations')); ?>
<p class="text-sm"><a class="link" href="<?= pl_e(pl_url('/stock-documents')) ?>"><?= pl_e(pl_t('Stock issues, returns and gate passes')) ?></a> · <a class="link" href="<?= pl_e(pl_url('/reports/stock-by-location')) ?>"><?= pl_e(pl_t('Stock by location')) ?></a></p>
<?php if ($write): ?>
<div class="grid md:grid-cols-2 gap-4 mt-4">
<form method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>" class="flex flex-col gap-3"><h3 class="section-title"><?= $editing?pl_e(pl_t('Edit {name}', ['name' => $editing['name']])):pl_e(pl_t('Add a warehouse or van')) ?></h3><?php pl_ui_return_filters($filters); pl_starter_form($company,'warehouse',['warehouse_id'=>$warehouseInput['warehouse_id']??($editing['id']??''),'revision'=>$warehouseInput['revision']??($editing['revision']??''),'request_key'=>$warehouseInput['request_key']??null]); ?>
<div class="grid grid-cols-2 gap-4"><?php if ($editing && !$warehouseInput): ?><label class="field"><span><?= pl_e(pl_t('Code')) ?></span><input class="input" name="code" value="<?= pl_e((string)$editing['code']) ?>" readonly></label><?php else: ?><?php pl_starter_field(pl_t('Code'),'code',$values['code']??''); ?><?php endif; pl_starter_field(pl_t('Name'),'name',$values['name']??'');
if ($editing && !$warehouseInput) { ?><label class="field"><span><?= pl_e(pl_t('Kind')) ?></span><input class="input" name="kind" value="<?= pl_e((string)$editing['kind']) ?>" readonly></label><?php } else { pl_starter_select(pl_t('Kind'),'kind',pl_inventory_warehouse_kinds(),$values['kind']??'fixed'); }
$assignmentOptions=[''=>'Select employee'];foreach($assignmentEmployees as $assignmentEmployee){$assignmentOptions[(string)$assignmentEmployee['id']]='#'.$assignmentEmployee['id'].' '.$assignmentEmployee['full_name'];}
pl_starter_select(pl_t('Driver employee (vans only)'),'driver_employee_id',$assignmentOptions,$values['driver_employee_id']??'',false);
echo '<p class="text-xs">'.pl_e(pl_t('Select an existing employee number from the Employees register. Existing unmapped names stay unchanged until explicitly linked.')).'</p>';
pl_starter_field(pl_t('Vehicle registration (vans only)'),'vehicle_reference',$values['vehicle_reference']??'','text',false);
pl_starter_field(pl_t('Route (vans only)'),'route_name',$values['route_name']??'','text',false);
pl_starter_field(pl_t('Reason'),'reason',$warehouseInput['reason']??''); ?></div>
<p class="text-xs text-ink-muted"><?= pl_e(pl_t('A location\'s kind is permanent: a building never becomes a van. A van names its driver.')) ?></p>
<p><label><input type="checkbox" name="is_active" value="1" <?= ($warehouseInput?($warehouseInput['is_active']??'')==='1':($values['is_active']??true))?'checked':'' ?>> <?= pl_e(pl_t('Active for new stock movements')) ?></label></p>
<div class="flex gap-2"><button class="btn btn-secondary"><?= pl_e(pl_t('Save location')) ?></button><?php if ($editing): ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?= pl_e(pl_t('Add a new one instead')) ?></a><?php endif; ?></div></form>
<form method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>" class="flex flex-col gap-3"><h3 class="section-title"><?= pl_e(pl_t('Transfer stock between locations')) ?></h3><?php pl_ui_return_filters($filters); pl_starter_form($company,'transfer',['request_key'=>$transferInput['request_key']??null]); ?>
<div class="grid grid-cols-2 gap-4"><?php pl_starter_select(pl_t('From'),'from_warehouse_id',$warehouseOptions,$transferInput['from_warehouse_id']??($warehouse_filter??'')); pl_starter_select(pl_t('To'),'to_warehouse_id',$warehouseOptions,$transferInput['to_warehouse_id']??''); pl_starter_select(pl_t('Stock product'),'product_id',pl_starter_options($stockProducts),$transferInput['product_id']??''); pl_starter_field(pl_t('Quantity in base units'),'quantity',$transferInput['quantity']??''); pl_starter_field(pl_t('Date'),'date',$transferInput['date']??gmdate('Y-m-d'),'date'); pl_starter_field(pl_t('Source reference'),'reference',$transferInput['reference']??''); pl_starter_field(pl_t('Reason'),'reason',$transferInput['reason']??''); ?></div>
<p class="text-xs text-ink-muted"><?= pl_e(pl_t('An insufficient quantity in the source location is rejected and your entries are retained.')) ?></p><button class="btn btn-secondary"><?= pl_e(pl_t('Record transfer')) ?></button></form>
</div><?php endif; ?></details>
