<?php declare(strict_types=1); ?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header(pl_t('Customers & suppliers'),pl_t('{count} parties · one shared record can be both a customer and a supplier', ['count' => $list['total']]),static function () use ($company,$filters): void { if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/parties',['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> <?= pl_e(pl_t('New party')) ?></a><?php endif; }); ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="<?= pl_e(pl_t('Party list')) ?>">
<nav class="tabs-seg mb-3" aria-label="<?= pl_e(pl_t('Party type')) ?>"><?php foreach (['all'=>'All','customer'=>'Customers','vendor'=>'Suppliers'] as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/parties',array_replace($filters,['role'=>$key,'page'=>1]))) ?>"<?= $filters['role']===$key?' aria-current="page"':'' ?>><?= pl_e(pl_t($label)) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_url('/parties')) ?>"><input type="hidden" name="role" value="<?= pl_e($filters['role']) ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Customers and suppliers; balances in {currency}', ['currency' => $company['currency']])) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/parties',$filters,'name',pl_t('Legal name')); ?></th><th scope="col"><?= pl_e(pl_t('Role')) ?></th><th scope="col" class="text-end"><?= pl_e(pl_t('Receivable')) ?></th><th scope="col" class="text-end"><?= pl_e(pl_t('Payable')) ?></th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_url('/parties',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===(int)$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['legal_name']) ?></span><span class="row-sub"><?= pl_e($row['country_code']) ?></span></a></td><td><?php if ($row['is_customer']): ?><span class="role-tag"><?= pl_e(pl_t('Customer')) ?></span><?php endif; ?> <?php if ($row['is_vendor']): ?><span class="role-tag"><?= pl_e(pl_t('Supplier')) ?></span><?php endif; ?></td><?php foreach (['receivable','payable'] as $direction): ?><td class="amount"><?= pl_e(pl_money($balances[$row['id']][$direction]??'0.0000')) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table><?php if (!$list['rows']) { pl_ui_empty(pl_t('No matching parties.'),pl_t('Adjust the search or add a customer or supplier.')); } ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= pl_e(pl_t('{count} records · {currency}', ['count' => (int)$list['total'], 'currency' => $company['currency']])) ?></span><?php pl_ui_pagination('/parties',$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_e(pl_t('These are sample records in a separate sample company.')) ?></p><?php endif; ?></section>
<?php pl_ui_side_panel(pl_t('Party details'),static function () use ($selection,$filters,$company,$balances,$contacts,$activity): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_url('/parties',$filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to list')) ?></a>
<?php if (!$selection) { pl_ui_empty(pl_t('Choose a party'),pl_t('Select a name to view details, contacts and recent activity.')); return; } ?>
<div class="border-b border-border px-5 py-4"><h2 class="text-lg font-semibold"><?= pl_e($selection['legal_name']) ?></h2><dl class="dgrid mt-3"><?php foreach (['receivable'=>'Receivable balance','payable'=>'Payable balance'] as $direction=>$label): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($company['currency'].' '.pl_money($balances[$selection['id']][$direction]??'0.0000')) ?></dd></div><?php endforeach; ?></dl></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4"><?php pl_ui_tabs([pl_t('Details')=>'#party-details',pl_t('Contacts')=>'#party-contacts',pl_t('Activity')=>'#party-activity'],pl_t('Details'),true); ?>
<section id="party-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Trading name'=>$selection['trading_name']?:'—','Entity type'=>$selection['entity_type'],'Country'=>$selection['country_code'],'Currency'=>$selection['financial']['currency']??$company['currency'],'Payment terms'=>$selection['financial']['payment_terms']??'—'] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value?:'—') ?></dd></div><?php endforeach; ?></dl></section>
<section id="party-contacts" class="py-3" data-ui-tab-panel><?php foreach ($contacts as $contact): ?><div class="border-b border-border py-3"><h3 class="text-sm font-semibold"><?= pl_e($contact['name']) ?></h3><p class="text-xs text-ink-muted"><?= pl_e($contact['role']) ?><?= $contact['is_primary']?' · '.pl_e(pl_t('Primary')):'' ?></p><p class="text-sm"><?= pl_e($contact['email'].' · '.$contact['phones']) ?></p></div><?php endforeach; if (!$contacts): ?><p class="text-sm text-ink-muted"><?= pl_e(pl_t('No contacts yet.')) ?></p><?php endif; ?></section>
<section id="party-activity" class="py-3" data-ui-tab-panel><p class="text-xs text-ink-muted mb-2"><?= pl_e(pl_t('Latest 20 documents, including drafts.')) ?></p><dl class="dgrid"><?php foreach ($activity as $item): ?><div class="dgrid-row"><dt><a class="link" href="<?= pl_e(pl_url(in_array($item['kind'],['invoice','customer_credit'],true)?'/ar':'/ap',['id'=>$item['id']])) ?>"><?= pl_e($item['number']) ?></a></dt><dd><?= pl_e(ucfirst($item['payment_status']??$item['status']).' · '.$item['currency'].' '.pl_money($item['total'])) ?></dd></div><?php endforeach; if (!$activity): ?><div class="dgrid-row"><dt><?= pl_e(pl_t('Activity')) ?></dt><dd><?= pl_e(pl_t('No documents yet.')) ?></dd></div><?php endif; ?></dl></section></div>
<div class="panel-actions"><p class="panel-actions-note"><?= pl_e(pl_t('One shared record for both roles.')) ?></p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/parties',['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= pl_icon('pencil') ?> <?= pl_e(pl_can_write($company)?pl_t('Edit party'):pl_t('View party')) ?></a></div>
<?php }); ?></div></div>
