<?php declare(strict_types=1); $stock=array_column($valuation['products'],null,'id'); ?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header(pl_t('Products & stock'),pl_t('{total} products · {currency} {value} total carrying value',['total'=>$list['total'],'currency'=>$company['currency'],'value'=>pl_money($valuation['total_value_base'])]),static function () use ($write,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/purchasing')) ?>"><?= pl_e(pl_t('Purchase orders')) ?></a><?php if ($write): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/inventory',['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> <?= pl_e(pl_t('New product')) ?></a><?php endif; }); ?>
<?php if (!$enabled): ?><div class="alert alert-info"><?= pl_e(pl_t('Inventory is disabled for new operations. Existing products and reports remain available.')) ?> <a class="link" href="<?= pl_e(pl_url('/modules')) ?>"><?= pl_e(pl_t('Review modules')) ?></a>.</div><?php endif; ?>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?><p><?= pl_e(pl_t('Your entered values are retained.')) ?></p></div><?php endif; ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="<?= pl_e(pl_t('Product list')) ?>">
<nav class="tabs-seg mb-3" aria-label="<?= pl_e(pl_t('Product type')) ?>"><?php foreach (['all'=>'All','stock'=>'Stock','nonstock'=>'Non-stock'] as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_url('/inventory',array_replace($filters,['kind'=>$key,'page'=>1]))) ?>"<?= $filters['kind']===$key?' aria-current="page"':'' ?>><?= pl_e(pl_t($label)) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_url('/inventory')) ?>"><input type="hidden" name="kind" value="<?= pl_e($filters['kind']) ?>"><?php pl_ui_list_controls($filters); ?><select class="select" name="status" aria-label="<?= pl_e(pl_t('Product status')) ?>"><?php foreach (['all'=>'All statuses','active'=>'Active','inactive'=>'Inactive'] as $key=>$label): ?><option value="<?= pl_e($key) ?>" <?= $filters['status']===$key?'selected':'' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select><label class="text-xs"><?= pl_e(pl_t('As of')) ?> <input class="input" type="date" name="as_of" value="<?= pl_e($filters['as_of']) ?>"></label><?php if ($locations): ?><select class="select" name="warehouse" aria-label="<?= pl_e(pl_t('Stock location')) ?>"><option value=""><?= pl_e(pl_t('All locations')) ?></option><?php foreach ($warehouses as $w): ?><option value="<?= (int)$w['id'] ?>" <?= $warehouse_filter===(int)$w['id']?'selected':'' ?>><?= pl_e($w['is_active']?pl_t('{code} · {name}',['code'=>$w['code'],'name'=>$w['name']]):pl_t('{code} · {name} (inactive)',['code'=>$w['code'],'name'=>$w['name']])) ?></option><?php endforeach; ?></select><?php endif; ?><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Products and stock as of {date}',['date'=>$filters['as_of']])) ?></caption><thead><tr><th scope="col"><?php pl_ui_sort('/inventory',$filters,'name',pl_t('Product')); ?></th><th scope="col" class="text-end"><?= pl_e(pl_t('On hand')) ?></th><th scope="col" class="text-end"><?= pl_e(pl_t('Carrying value')) ?></th><th scope="col"><?= pl_e(pl_t('Status')) ?></th></tr></thead><tbody>
<?php foreach ($list['rows'] as $row): $value=$stock[$row['id']]??null; ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_url('/inventory',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===(int)$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['name']) ?></span><span class="row-sub"><?= pl_e($row['sku'].' · '.$row['kind']) ?></span></a></td><td class="amount"><?= $value?pl_e($value['quantity'].' '.$row['base_unit']):'—' ?></td><td class="amount"><?= $value?pl_e(pl_money($value['value_base'])):'—' ?></td><td><?php pl_ui_badge($row['is_active']?'active':'inactive',$row['is_active']?pl_t('Active'):pl_t('Inactive')); ?></td></tr><?php endforeach; ?></tbody></table><?php if (!$list['rows']) { pl_ui_empty(pl_t('No matching products.'),pl_t('Adjust the search or add a stock item or service.')); } ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= pl_e(pl_t('{total} records · {currency}',['total'=>(int)$list['total'],'currency'=>$company['currency']])) ?></span><?php pl_ui_pagination('/inventory',$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_e(pl_t('These are sample records in a separate sample company.')) ?></p><?php endif; ?></section>
<?php pl_ui_side_panel(pl_t('Product details'),static function () use ($selection,$stock,$filters,$company,$accountOptions,$movements,$write): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to list')) ?></a>
<?php if (!$selection) { pl_ui_empty(pl_t('Choose a product'),pl_t('Select a product to view its stock, accounts and movements.')); return; } $value=$stock[$selection['id']]??null; ?>
<div class="border-b border-border px-5 py-4"><div class="flex flex-wrap gap-2 items-center"><h2 class="text-lg font-semibold"><?= pl_e($selection['name']) ?></h2><?php pl_ui_badge($selection['is_active']?'active':'inactive',$selection['is_active']?pl_t('Active'):pl_t('Inactive')); ?></div><p class="text-sm text-ink-muted mt-2"><?= pl_e($selection['sku']) ?><?= $value?' · '.pl_e(pl_t('{qty} on hand',['qty'=>$value['quantity'].' '.$selection['base_unit']])):'' ?></p><p class="amount-lg mt-2"><?= $value?pl_e($company['currency'].' '.pl_money($value['value_base'])):pl_e(pl_t('Non-stock item')) ?></p><p class="text-xs text-ink-muted mt-1"><?= pl_e(pl_t('As of {date}',['date'=>pl_date_label($filters['as_of'])])) ?></p></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4"><?php pl_ui_tabs([pl_t('Details')=>'#product-details',pl_t('Movements')=>'#product-movements'],pl_t('Details'),true); ?>
<section id="product-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Base unit'=>$selection['base_unit'],'Average unit cost'=>$value['average_cost']??'—','Selling price'=>$selection['selling_price'],'Sales account'=>$accountOptions[$selection['sales_account_id']]??'—','Inventory account'=>$accountOptions[$selection['inventory_account_id']]??'—','Cost account'=>$accountOptions[$selection['cogs_account_id']]??'—'] as $label=>$text): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($text) ?></dd></div><?php endforeach; ?></dl></section>
<section id="product-movements" class="py-3" data-ui-tab-panel><p class="text-xs text-ink-muted mb-2"><?= pl_e(pl_t('Latest 500 movements, all dates, with original source references.')) ?></p><?php pl_ui_table([pl_t('Date / movement'),pl_t('Quantity / value'),pl_t('Source')],static function () use ($movements): void { foreach ($movements as $row): ?><tr><td><?= pl_e(pl_date_label($row['movement_date'])) ?><span class="row-sub"><?= pl_e(str_replace('_',' ',$row['kind'])) ?></span></td><td class="amount"><?= pl_e($row['quantity_delta']) ?><span class="row-sub"><?= pl_e($row['value_delta']) ?></span></td><td><?php if ($row['journal_id']): ?><a class="link" href="<?= pl_e(pl_url('/journals/detail',['id'=>$row['journal_id']])) ?>"><?= pl_e($row['source_reference']) ?></a><?php else: ?><?= pl_e($row['source_reference']) ?><?php endif; ?></td></tr><?php endforeach; if (!$movements): ?><tr><td colspan="3"><?= pl_e(pl_t('No movements yet.')) ?></td></tr><?php endif; },pl_t('Product movements')); ?></section></div>
<div class="panel-actions"><a class="btn btn-secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= pl_e($write?pl_t('Edit product'):pl_t('View product')) ?></a><?php if ($write && $selection['kind']==='stock'): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/inventory',['id'=>$selection['id'],'count'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Record count')) ?></a><?php endif; ?></div>
<?php }); ?></div>
<?php if ($locations) { require __DIR__.'/inventory-locations.php'; } ?>
<details class="rounded-panel border border-border bg-surface p-4"><summary class="section-title"><?= pl_e(pl_t('Stock to ledger reconciliation')) ?></summary><?php if ($warehouse_filter): ?><p class="text-sm my-3"><?= pl_e(pl_t('Showing one stock location. Ledger reconciliation covers all locations together;')) ?> <a class="link" href="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?= pl_e(pl_t('view all locations')) ?></a>.</p><?php endif; ?><p class="text-sm my-3"><?= pl_e(pl_t('Total carrying value {amount} as of {date}. Totals cover all stock products, regardless of list filters.',['amount'=>$company['currency'].' '.pl_money($valuation['total_value_base']),'date'=>pl_date_label($valuation['as_of'])])) ?></p><?php pl_ui_table([pl_t('Account'),pl_t('Stock value'),pl_t('Ledger value'),pl_t('Difference')],static function () use ($valuation,$accountOptions): void { foreach ($valuation['accounts'] as $row): ?><tr><td><a class="link" href="<?= pl_e(pl_url('/reports/account',['id'=>$row['account_id'],'as_of'=>$valuation['as_of']])) ?>"><?= pl_e($accountOptions[$row['account_id']]??pl_t('Account {id}',['id'=>$row['account_id']])) ?></a></td><td class="amount"><?= pl_e(pl_money($row['stock_value'])) ?></td><td class="amount"><?= $row['ledger_value']===null?'—':pl_e(pl_money($row['ledger_value'])) ?></td><td class="amount"><?= $row['difference']===null?'—':pl_e(pl_money($row['difference'])) ?></td></tr><?php endforeach; },pl_t('Stock to ledger')); ?><a class="link text-sm" href="<?= pl_e(pl_url('/accounts')) ?>"><?= pl_e(pl_t('Manage accounts')) ?></a></details>
<?php require __DIR__.'/inventory-opening.php'; ?>
</div>
