<?php declare(strict_types=1); ?>
<div class="flex flex-col gap-4 py-5"><section class="rounded-panel border border-border bg-surface">
<?php pl_ui_document_header($product?$product['name']:pl_t('New product'),$product?($product['is_active']?'active':'inactive'):'',static function () use ($write,$product,$filters): void { ?>
<?php if ($write && $product && $product['kind']==='stock'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$product['id'],'count'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Record count')) ?></a><?php endif; ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?= pl_e(pl_t('Cancel')) ?></a><?php if ($write): ?><button class="btn btn-primary" form="product-editor"><?= pl_e(pl_t('Save product')) ?></button><?php endif; ?>
<?php }); ?>
<div class="doc-body">
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?><p><?= pl_e(pl_t('Your entered values are retained.')) ?></p></div><?php endif; ?>
<?php if ($product): ?><p class="text-xs text-ink-muted"><?= pl_e(pl_t('Product code, type, base unit, inventory and cost accounts are protected here. Existing movements retain their original quantities and values.')) ?></p><?php endif; ?>
<?php if ($write): ?><form id="product-editor" class="flex flex-col gap-4" method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?php pl_ui_return_filters($filters); pl_starter_form($company,'product',['id'=>$product['id']??0,'revision'=>$productInput?($productInput['revision']??''):($product['revision']??0),'request_key'=>($submitted['action']??'')==='product'?($submitted['request_key']??null):null]); ?><div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
<?php if ($product) {
    foreach (['sku'=>'Product code','kind'=>'Type','base_unit'=>'Base unit'] as $field=>$label) { echo '<p>'.pl_e(pl_t($label)).'<br><strong>'.pl_e($product[$field]).'</strong></p>'; pl_starter_hidden($field,$product[$field]); }
} else { pl_starter_field(pl_t('Product code'),'sku',$v['sku']??''); pl_starter_select(pl_t('Type'),'kind',['stock'=>pl_t('Stock item'),'nonstock'=>pl_t('Service / non-stock')],$v['kind']??'stock'); pl_starter_field(pl_t('Base unit'),'base_unit',$v['base_unit']??'each'); }
pl_starter_field(pl_t('Name'),'name',$v['name']??''); pl_starter_field(pl_t('Selling price'),'selling_price',$v['selling_price']??'0');
foreach (['inventory_account_id'=>'Inventory asset account','cogs_account_id'=>'Cost of goods sold account','sales_account_id'=>'Sales income account','purchase_account_id'=>'Purchase account'] as $field=>$label) {
    if ($product && in_array($field,['inventory_account_id','cogs_account_id'],true)) { echo '<p>'.pl_e(pl_t($label)).'<br><strong>'.pl_e($product[$field]===null?pl_t('Not used'):($accountOptions[$product[$field]]??pl_t('Account {id}',['id'=>$product[$field]]))).'</strong></p>'; pl_starter_hidden($field,$product[$field]); continue; }
    $types=match($field){'inventory_account_id'=>['asset'],'cogs_account_id'=>['expense'],'sales_account_id'=>['income'],default=>['asset','expense']};
    $eligible=array_filter($accounts,static fn(array $a):bool=>in_array($a['type'],$types,true)&&!in_array($a['role'],['cash_bank','receivables','payables'],true));
    pl_starter_select(pl_t($label),$field,pl_starter_options($eligible),$v[$field]??'',!in_array($field,['inventory_account_id','cogs_account_id'],true));
}
pl_starter_field(pl_t('Reason'),'reason',$v['reason']??''); ?></div><p><label><input type="checkbox" name="is_active" value="1" <?= ($productInput?($productInput['is_active']??'')==='1':($v['is_active']??true))?'checked':'' ?>> <?= pl_e(pl_t('Active')) ?></label></p><?php if ($productInput && $product): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$product['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Reload saved product')) ?></a><?php endif; ?></form>
<?php elseif ($product): ?><dl class="dgrid"><?php foreach (['Product code'=>$product['sku'],'Type'=>$product['kind'],'Base unit'=>$product['base_unit'],'Selling price'=>$product['selling_price']] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl><p class="text-sm text-ink-muted"><?= pl_e(pl_t('Product changes require write access and the Inventory module.')) ?></p><?php else: pl_ui_empty(pl_t('Inventory is unavailable'),pl_t('Enable Inventory and use an owner or bookkeeper account to add products.')); endif; ?>
</div></section>

<?php if ($product && $product['kind']==='stock'): ?><section class="rounded-panel border border-border bg-surface p-5"><h2><?= pl_e($product['name']) ?></h2><div class="grid grid-cols-2 md:grid-cols-3 gap-4"><p><?= pl_e(pl_t('Quantity')) ?><br><strong><?= pl_e($balance['quantity'].' '.$product['base_unit']) ?></strong></p><p><?= pl_e(pl_t('Carrying value')) ?><br><strong><?= pl_e($company['currency'].' '.pl_money($balance['value_base'])) ?></strong></p><p><?= pl_e(pl_t('Average unit cost')) ?><br><strong><?= pl_e($balance['average_cost']) ?></strong></p></div>
<?php if ($write): ?>
<?php foreach (['receive'=>'Manual stock receipt','issue'=>'Manual stock issue','value'=>'Reviewed value adjustment'] as $action=>$label): $move=($submitted['action']??'')===$action?$submitted:[]; ?><details <?= $move?'open':'' ?>><summary><?= pl_e(pl_t($label)) ?></summary><p class="muted"><?= pl_e(pl_t('Use Purchasing for ordered goods and supplier returns. Manual movements need an explicit counterpart account and reason. Value adjustments retain the quantity and must agree with the reviewed carrying value.')) ?></p><form method="post" action="<?= pl_e(pl_url('/inventory',$filters)) ?>"><?php pl_ui_return_filters($filters); pl_starter_form($company,$action,['id'=>$product['id'],'expected_quantity'=>$move?($move['expected_quantity']??''):$balance['quantity'],'expected_value_base'=>$move?($move['expected_value_base']??''):$balance['value_base'],'request_key'=>$move['request_key']??null]); ?><div class="grid grid-cols-2 md:grid-cols-3 gap-4"><?php pl_starter_field(pl_t('Date'),'date',$move['date']??gmdate('Y-m-d'),'date'); if ($action!=='value') { pl_starter_field(pl_t('Quantity'),'quantity',$move['quantity']??''); } else { pl_starter_field(pl_t('Value change in {currency} (use a minus sign to reduce)',['currency'=>$company['currency']]),'amount_base',$move['amount_base']??''); } if ($action==='receive') { pl_starter_field(pl_t('Total cost in {currency}',['currency'=>$company['currency']]),'amount_base',$move['amount_base']??''); } pl_starter_select(pl_t('Counterpart account'),'offset_account_id',$accountOptions,$move['offset_account_id']??($action==='issue'?$product['cogs_account_id']:'')); if ($locations) { pl_starter_select(pl_t('Stock location'),'warehouse_id',$warehouseOptions,$move['warehouse_id']??($warehouse_filter??''),false); } pl_starter_field(pl_t('Source reference'),'reference',$move['reference']??''); pl_starter_field(pl_t('Reason'),'reason',$move['reason']??''); ?></div><button class="btn btn-secondary"><?= pl_e(pl_t($label)) ?></button><?php if ($move && $action==='value'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/inventory',['id'=>$product['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Reload current stock for review')) ?></a><?php endif; ?></form></details><?php endforeach; endif; ?></section><?php endif; ?>
</div>
