<?php declare(strict_types=1); $statuses=['draft'=>'Draft','ordered'=>'Ordered','partial'=>'Partially received','received'=>'Received','cancelled'=>'Cancelled','all'=>'All']; ?>
<?php pl_ui_page_header(pl_t('Purchase orders'),pl_t('{count} orders · track commitments, deliveries and supplier billing',['count'=>$list['total']]),static function () use ($write,$filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_url('/inventory')) ?>"><?= pl_e(pl_t('Products & stock')) ?></a><?php if ($write): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url('/purchasing',['new'=>'1','return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> <?= pl_e(pl_t('New purchase order')) ?></a><?php endif; }); ?>
<div class="split-view"><section class="split-view-list<?= $selection?' has-detail':'' ?>" aria-label="<?= pl_e(pl_t('Purchase order list')) ?>">
<nav class="tabs-seg mb-3" aria-label="<?= pl_e(pl_t('Order status')) ?>"><?php foreach ($statuses as $key=>$label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_workflow_url('/purchasing',array_replace($filters,['status'=>$key,'page'=>1]))) ?>"<?= $filters['status']===$key?' aria-current="page"':'' ?>><?= pl_e(pl_t($label)) ?></a><?php endforeach; ?></nav>
<form class="filter-bar mb-3" method="get" action="<?= pl_e(pl_workflow_url('/purchasing')) ?>"><input type="hidden" name="status" value="<?= pl_e($filters['status']) ?>"><input type="hidden" name="as_of" value="<?= pl_e($filters['as_of']) ?>"><?php pl_ui_list_controls($filters); ?><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button></form>
<div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Purchase orders')) ?></caption><thead><tr><?php foreach (['date'=>'Order / date','name'=>'Supplier','amount'=>'Value'] as $key=>$label): ?><th scope="col"><?php pl_ui_sort('/purchasing',$filters,$key,pl_t($label)); ?></th><?php endforeach; ?><th scope="col"><?= pl_e(pl_t('Status')) ?></th></tr></thead><tbody>
<?php foreach ($list['orders'] as $row): $progress=pl_purchase_order_progress($row); ?><tr><td><a class="record-link" data-record-link href="<?= pl_e(pl_workflow_url('/purchasing',array_replace($filters,['select'=>$row['id']]))) ?>"<?= $selection && $selection['id']===$row['id']?' aria-current="true"':'' ?>><span class="row-title"><?= pl_e($row['number']) ?></span><span class="row-sub"><?= pl_e(pl_date_label($row['document_date'])) ?></span></a></td><td><?= pl_e($row['party_name']) ?></td><td class="amount"><?= pl_e($row['currency'].' '.pl_money($row['total'])) ?></td><td><?php pl_ui_badge($progress==='partial'?'partially-received':$progress,pl_t($statuses[$progress])); ?></td></tr><?php endforeach; ?></tbody></table><?php if (!$list['orders']) { pl_ui_empty(pl_t('No matching purchase orders.'),pl_t('Adjust the filters or create an order for your supplier.')); } ?></div>
<div class="flex flex-wrap justify-between items-center gap-3 mt-3"><span class="text-xs text-ink-muted"><?= pl_e(pl_tn('{count} record', '{count} records', (int)$list['total'], ['count' => (int)$list['total']])) ?></span><?php pl_ui_pagination('/purchasing',$filters,$list['page'],$list['pages']); ?></div>
<?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_e(pl_t('These are sample records in a separate sample company.')) ?></p><?php endif; ?></section>
<?php pl_ui_side_panel(pl_t('Purchase order details'),static function () use ($selection,$filters,$write,$receipts,$statuses): void { ?>
<a class="split-view-back link" href="<?= pl_e(pl_workflow_url('/purchasing',$filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to list')) ?></a>
<?php if (!$selection) { pl_ui_empty(pl_t('Choose an order'),pl_t('Select an order to review its supplier, quantities and receipts.')); return; } $progress=pl_purchase_order_progress($selection); ?>
<div class="border-b border-border px-5 py-4"><div class="flex flex-wrap gap-2 items-center"><h2 class="text-lg font-semibold"><?= pl_e($selection['number']) ?></h2><?php pl_ui_badge($progress==='partial'?'partially-received':$progress,pl_t($statuses[$progress])); ?></div><p class="text-sm text-ink-muted mt-2"><?= pl_e($selection['party_name']) ?></p><p class="amount-lg mt-2"><?= pl_e($selection['currency'].' '.pl_money($selection['total'])) ?></p></div>
<div class="flex flex-col min-h-0 flex-1 overflow-y-auto px-5 pt-4"><?php pl_ui_tabs([pl_t('Details')=>'#order-details',pl_t('Receipts')=>'#order-receipts'],pl_t('Details'),true); ?>
<section id="order-details" class="py-3" data-ui-tab-panel><dl class="dgrid"><?php foreach (['Order date'=>pl_date_label($selection['document_date']),'Reference'=>$selection['reference']?:'—','Status'=>ucfirst($selection['status'])] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl>
<?php foreach ($selection['lines'] as $line): ?><div class="border-t border-border py-3"><h3 class="text-sm font-semibold"><?= pl_e($line['description']) ?></h3><dl class="dgrid"><?php foreach (['Ordered'=>$line['quantity'],'Received'=>$line['received_quantity'],'Unreceived'=>$line['remaining_quantity']] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl></div><?php endforeach; ?></section>
<section id="order-receipts" class="py-3" data-ui-tab-panel><?php $selectedReceipts=array_filter($receipts,static fn(array $row):bool=>(int)$row['order_id']===$selection['id']); foreach ($selectedReceipts as $row): ?><div class="border-b border-border py-3"><a class="link text-sm" href="<?= pl_e(pl_workflow_url('/journals/detail',['id'=>$row['journal_id']])) ?>"><?= pl_e(pl_t('Receipt {number} · {date}',['number'=>(int)$row['receipt_id'],'date'=>pl_date_label($row['document_date'])])) ?></a><p class="text-xs text-ink-muted"><?= pl_e(pl_t('{description} · Received {received} · Unbilled {unbilled}',['description'=>$row['description'],'received'=>$row['quantity'],'unbilled'=>$row['unbilled_quantity']])) ?></p></div><?php endforeach; if (!$selectedReceipts): ?><p class="text-sm text-ink-muted"><?= pl_e(pl_t('No receipts yet.')) ?></p><?php endif; ?></section></div>
<div class="panel-actions"><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/purchasing',['id'=>$selection['id'],'return_filters'=>$filters])) ?>"><?= pl_e($write && $selection['status']==='draft'?pl_t('Edit order'):pl_t('Open order')) ?></a><?php if ($write && in_array($progress,['ordered','partial'],true)): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url('/purchasing',['id'=>$selection['id'],'receive'=>'1','return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Receive goods')) ?></a><?php endif; ?></div>
<?php }); ?></div>
