<?php
declare(strict_types=1);
$canManage = pl_can_write($company) && !pl_demo_enabled();
$types = ['asset' => 'Asset', 'liability' => 'Liability', 'equity' => 'Equity', 'income' => 'Income', 'expense' => 'Expense'];
$roles = ['' => 'No operational purpose', 'cash_bank' => 'Cash / bank — Asset', 'receivables' => 'Receivables — Asset', 'payables' => 'Payables — Liability', 'customer_advances' => 'Customer advances — Liability', 'supplier_advances' => 'Supplier advances — Asset', 'owner_equity' => 'Owner equity — Equity', 'income' => 'Income — Income', 'expense' => 'Expense — Expense'];
$moneyKinds = ['' => 'Not classified — choose before paying out', 'physical' => 'Physical cash — petty cash, till or cash box', 'bank' => 'Bank account'];
$hasFailure = pl_web_text($form, 'message') !== '';
$isActive = $hasFailure ? pl_web_text($input, 'is_active') === '1' : (bool) ($input['is_active'] ?? true);
$isContra = $hasFailure ? pl_web_text($input, 'is_contra') === '1' : (bool) ($input['is_contra'] ?? false);
$hasOverdraft = $hasFailure ? pl_web_text($input, 'overdraft_enabled') === '1' : (bool) ($input['overdraft_enabled'] ?? false);
$facilityCurrency = $account['currency'] ?? $company['currency'];
$levels = ['class' => 'Class heading', 'group' => 'Group heading', 'account' => 'Account', 'sub_account' => 'Sub-account'];
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header(pl_t('Chart of accounts'),pl_t('{count} accounts · {currency}',['count'=>count($company['accounts']),'currency'=>$company['currency']]),static function () use ($canManage,$chartFilters):void { if ($canManage): ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/accounts',['new'=>'1','return_filters'=>$chartFilters])) ?>"><?= pl_icon('plus') ?> <?= pl_e(pl_t('New account')) ?></a><?php endif; },'accounts-title'); ?>
<div class="split-view">
<section class="split-view-list <?= $account || $isNew?'has-detail':'' ?>" aria-labelledby="accounts-title">
<form class="filter-bar flex-wrap" method="get" action="<?= pl_e(pl_url('/accounts')) ?>">
<label class="sr-only" for="chart-search"><?= pl_e(pl_t('Search accounts')) ?></label><input class="input" id="chart-search" name="q" value="<?= pl_e($chartFilters['q']) ?>" placeholder="<?= pl_e(pl_t('Code or account name')) ?>" maxlength="160">
<label class="sr-only" for="chart-type"><?= pl_e(pl_t('Filter by classification')) ?></label><select class="select" id="chart-type" name="type"><option value="all"><?= pl_e(pl_t('All classifications')) ?></option><?php foreach ($types as $value=>$label): ?><option value="<?= pl_e($value) ?>" <?= $chartFilters['type']===$value?'selected':'' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select>
<label class="sr-only" for="chart-status"><?= pl_e(pl_t('Account status')) ?></label><select class="select" id="chart-status" name="status"><?php foreach (['all'=>'All statuses','active'=>'Active','inactive'=>'Inactive'] as $value=>$label): ?><option value="<?= pl_e($value) ?>" <?= $chartFilters['status']===$value?'selected':'' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select>
<label class="sr-only" for="chart-size"><?= pl_e(pl_t('Accounts per page')) ?></label><select class="select" id="chart-size" name="per_page"><?php foreach ([25,50,100] as $size): ?><option value="<?= $size ?>" <?= $chartFilters['per_page']===$size?'selected':'' ?>><?= pl_e(pl_t('{size} per page', ['size' => $size])) ?></option><?php endforeach; ?></select>
<input type="hidden" name="sort" value="<?= pl_e($chartFilters['sort']) ?>"><input type="hidden" name="dir" value="<?= pl_e($chartFilters['dir']) ?>"><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button><a class="btn btn-ghost" href="<?= pl_e(pl_url('/accounts')) ?>"><?= pl_e(pl_t('Clear')) ?></a>
</form><p class="text-xs text-ink-muted mb-2"><?= pl_e(pl_t('{count} matching accounts · Sort within classification:', ['count' => (int) $accountList['total']])) ?> <?php pl_ui_sort('/accounts',$chartFilters,'code',pl_t('Code')); ?> · <?php pl_ui_sort('/accounts',$chartFilters,'name',pl_t('Name')); ?></p>
<div class="table-wrap max-h-[560px] overflow-auto" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Accounts')) ?>">
<table class="table"><caption class="sr-only"><?= pl_e(pl_t('Chart of accounts and posted balances through {date}. Debit balances for assets and expenses; credit balances for other classifications.', ['date' => pl_date_label($balanceDate)])) ?></caption><thead><tr><th scope="col"><?= pl_e(pl_t('Code / account')) ?></th><th scope="col"><?= pl_e(pl_t('Purpose')) ?></th><th scope="col"><?= pl_e(pl_t('Status')) ?></th><th scope="col" class="num"><?= pl_e(pl_t('Balance')) ?></th></tr></thead><tbody>
<?php foreach ($types as $type=>$typeLabel): $group=array_filter($accountList['rows'],static fn(array $row):bool=>$row['type']===$type); if (!$group) { continue; } ?>
<tr class="bg-surface-subtle"><th scope="rowgroup" colspan="4" class="text-xs uppercase tracking-wide text-ink-muted"><?= pl_e(pl_t($typeLabel)) ?></th></tr>
<?php foreach ($group as $row): $selected=$account && (int)$account['id']===(int)$row['id']; $balance=$balances[(int)$row['id']]??'0.0000'; ?>
<tr<?= $selected?' aria-selected="true"':'' ?>><th scope="row"><a class="row-title link" href="<?= pl_e(pl_url('/accounts',['id'=>$row['id'],'return_filters'=>$chartFilters])) ?>"<?= $selected?' aria-current="true"':'' ?>><?= pl_e($row['name']) ?></a><span class="row-sub"><?= pl_e($row['code']) ?></span></th><td class="text-xs text-ink-muted"><?= pl_e($row['role']?ucfirst(str_replace('_',' / ',$row['role'])):pl_t($levels[$row['level']]??'—')) ?><?= $row['is_contra']?' · '.pl_e(pl_t('Contra')):'' ?><?php pl_ui_heading_help((string) $row['code'], 'sheet'); ?></td><td><?php pl_ui_badge($row['is_active']?'active':'inactive', $row['is_active']?pl_t('Active'):pl_t('Inactive')); ?></td><td class="num"><a class="link" href="<?= pl_e(pl_url('/reports/account',['id'=>$row['id'],'as_of'=>$balanceDate])) ?>" aria-label="<?= pl_e(pl_t('Statement for {name}: {currency} {amount}', ['name' => $row['name'], 'currency' => $company['currency'], 'amount' => pl_money($balance)])) ?>"><?= pl_e(pl_money($balance)) ?></a></td></tr>
<?php endforeach; endforeach; ?>
</tbody></table></div>
<?php if (!$accountList['total']) { pl_ui_empty(pl_t('No matching accounts'), pl_t('Clear or change the filters to see other accounts.')); } ?>
<?php pl_ui_pagination('/accounts',$chartFilters,$accountList['page'],$accountList['pages']); ?>
<p class="text-xs text-ink-muted mt-3"><?= pl_e(pl_t('Posted balances through {date}. Inactive accounts retain their balances and history.', ['date' => pl_date_label($balanceDate)])) ?></p>
</section>
<section class="split-view-detail p-4 gap-3" aria-labelledby="account-detail-title">
    <a class="btn btn-ghost self-start" href="<?= pl_e(pl_url('/accounts',$chartFilters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to accounts')) ?></a>
    <?php if ($hasFailure): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><strong><?= pl_e(pl_t('Your account was not saved.')) ?></strong><p><?= pl_e(pl_web_text($form, 'message')) ?></p><p><?= pl_e(pl_t('Your submitted values are retained.')) ?><?php if ($account): ?> <a href="<?= pl_e(pl_url('/accounts', ['id' => $account['id'],'return_filters'=>$chartFilters])) ?>"><?= pl_e(pl_t('Reload the latest saved version')) ?></a> <?= pl_e(pl_t('before resolving a revision conflict.')) ?><?php endif; ?></p></div><?php endif; ?>
    <?php if ($account || ($isNew && $canManage)): ?>
    <div class="section-heading"><h2 class="section-title" id="account-detail-title"><?= $account ? pl_e($account['name']) : pl_e(pl_t('New account')) ?></h2><?php if ($canManage): ?><button class="btn btn-primary" type="submit" form="account-editor" data-fold="primary action"><?= $account ? pl_e(pl_t('Save account')) : pl_e(pl_t('Create account')) ?></button><?php elseif ($account): ?><span class="muted small"><?= pl_e(pl_t('Revision {number}', ['number' => (int) $account['revision']])) ?></span><?php endif; ?></div>
    <?php if ($canManage): ?>
    <form id="account-editor" method="post" action="<?= pl_e(pl_url('/accounts/save')) ?>" class="flex flex-col gap-3">
        <?php pl_ui_return_filters($chartFilters); ?>
        <?= pl_csrf_field() ?><?= pl_scope_fields($company) ?>
        <input type="hidden" name="creation_key" value="<?= pl_e(pl_web_text($input, 'creation_key')) ?>">
        <?php if ($account): ?><input type="hidden" name="id" value="<?= (int) $account['id'] ?>"><input type="hidden" name="revision" value="<?= pl_web_id($input, 'revision') ?>">
        <dl class="record-details"><div><dt><?= pl_e(pl_t('Code')) ?></dt><dd><?= pl_e($account['code']) ?><?= $account['legacy_code'] ? ' <span class="text-xs text-ink-muted">' . pl_e(pl_t('was {code}', ['code' => $account['legacy_code']])) . '</span>' : '' ?></dd></div><div><dt><?= pl_e(pl_t('Level')) ?></dt><dd><?= pl_e(pl_t($levels[$account['level']] ?? 'Account')) ?><?= $account['is_postable'] ? '' : ' · ' . pl_e(pl_t('aggregates the accounts below it')) ?><?php pl_ui_heading_help((string) $account['code']); ?></dd></div><div><dt><?= pl_e(pl_t('Classification')) ?></dt><dd><?= pl_e(pl_t($types[$account['type']] ?? $account['type'])) ?><?= $account['is_contra'] ? ' · ' . pl_e(pl_t('contra')) : '' ?></dd></div><div><dt><?= pl_e(pl_t('Purpose')) ?></dt><dd><?= pl_e(pl_t($roles[$account['role'] ?? ''] ?? 'No operational purpose')) ?></dd></div></dl>
        <?php foreach (['code', 'type', 'role'] as $fixedField): ?><input type="hidden" name="<?= pl_e($fixedField) ?>" value="<?= pl_e((string) ($account[$fixedField] ?? '')) ?>"><?php endforeach; ?>
        <p class="muted small"><?= pl_e(pl_t('Code, classification and purpose are fixed. Use a new account and a reviewed correction for a classification change.')) ?></p>
        <?php else: ?>
        <div class="grid grid-cols-2 gap-3">
            <label class="field"><?= pl_e(pl_t('Account code')) ?><input class="input" name="code" value="<?= pl_e(pl_web_text($input, 'code')) ?>" maxlength="20" pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,19}" required autocomplete="off"><span class="field-hint"><?php /* One sentence, not eight fragments around <code> elements: a clause order a translator cannot change is not translatable, and it comes apart in a right-to-left locale. The codes are placeholder values, isolated so they stay left to right. */ ?><?= pl_e(pl_t('Structured code {format}: class, group, account, sub-account. {heading} is the Equity heading, {group} a group heading, {account} an account and {sub} a sub-account under it. A heading is not posted to; postings belong on the lowest account. Group numbers 900 and above are reserved for contra accounts.', ['format' => pl_ltr('X-XXX-XXXXX-XX'), 'heading' => pl_ltr('3-000-00000-00'), 'group' => pl_ltr('3-100-00000-00'), 'account' => pl_ltr('3-100-10001-00'), 'sub' => pl_ltr('3-100-10001-01')])) ?></span></label>
            <label class="field"><?= pl_e(pl_t('Classification')) ?><select class="select" name="type" required><?php foreach ($types as $value => $label): ?><option value="<?= pl_e($value) ?>" <?= pl_web_text($input, 'type') === $value ? 'selected' : '' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select></label>
            <label class="field col-span-2"><?= pl_e(pl_t('Operational purpose')) ?><select class="select" name="role"><?php foreach ($roles as $value => $label): ?><option value="<?= pl_e($value) ?>" <?= pl_web_text($input, 'role') === $value ? 'selected' : '' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select><span class="field-hint"><?= pl_e(pl_t('Choose a purpose with the same classification, or no operational purpose.')) ?></span></label>
        </div>
        <?php endif; ?>
        <p class="field-hint" data-account-consequence><?= pl_e(in_array(pl_web_text($input,'type'),['income','expense'],true)?pl_t('This account appears on Profit & loss.'):pl_t('This account appears on the Balance sheet.')) ?> <?= pl_e(pl_t('Assets, liabilities and equity appear on the Balance sheet; income and expenses appear on Profit & loss.')) ?></p>
        <?php if (!$account || $account['type']==='expense'): ?><div class="field"><label for="account-report-section"><?= pl_e(pl_t('Profit & loss section')) ?></label><select id="account-report-section" class="select" name="report_classification" aria-describedby="classification-hint"><option value=""><?= pl_e(pl_t('Unclassified — keep existing expense presentation')) ?></option><option value="cost_of_sales" <?= pl_web_text($input,'report_classification')==='cost_of_sales'?'selected':'' ?>><?= pl_e(pl_t('Cost of sales — expense accounts only')) ?></option></select></div><p id="classification-hint" class="field-hint"><?= pl_e(pl_t('Changing this section affects reports for every period. Posted amounts and net profit stay unchanged.')) ?></p><?php endif; ?>
        <label class="field"><?= pl_e(pl_t('Account name')) ?><input class="input" name="name" value="<?= pl_e(pl_web_text($input, 'name')) ?>" maxlength="120" required></label>
        <?php if ($operationalWarning): ?><?php pl_ui_strip(pl_t('This account supports cash/bank, receivable, payable or tax operations. Deactivating it prevents new entries that need it. Existing balances and history remain; review affected workflows before saving.'), 'warning'); ?><?php endif; ?>
        <label class="flex items-start gap-2 text-sm"><input type="checkbox" name="is_active" value="1" <?= $isActive ? 'checked' : '' ?>><span><?= pl_e(pl_t('Active — available for new entries')) ?></span></label>
        <label class="flex items-start gap-2 text-sm"><input type="checkbox" name="is_contra" value="1" <?= $isContra ? 'checked' : '' ?>><span><?= pl_e(pl_t('Contra account — presented as a deduction inside its own section')) ?><span class="block text-xs text-ink-muted"><?= pl_e(pl_t('Accumulated depreciation and provisions against assets, sales returns and discounts allowed, purchase returns and discounts received, and drawings. The flag changes presentation only: no posted entry moves, and clearing it restores the earlier presentation exactly.')) ?></span></span></label>
        <?php if (!$account || $account['role'] === 'cash_bank'): ?>
        <label class="field" for="account-money-kind"><?= pl_e(pl_t('Cash / bank kind')) ?><select class="select" id="account-money-kind" name="money_kind" aria-describedby="account-money-kind-help"><?php foreach ($moneyKinds as $value => $label): ?><option value="<?= pl_e($value) ?>" <?= pl_web_text($input, 'money_kind') === $value ? 'selected' : '' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select></label>
        <p class="text-xs text-ink-muted" id="account-money-kind-help"><?= pl_e(pl_t('For cash / bank accounts, choose what this account actually holds. When Strict is selected in Admin > Accounting policies, payments cannot create or worsen a physical-cash shortfall or exceed a bank\'s recorded overdraft limit. Warning only permits posting with balance warnings. Leave other account purposes unclassified. Strict mode requires an explicit classification before paying out.')) ?></p>
        <fieldset class="flex flex-col gap-2"><legend class="field-label"><?= pl_e(pl_t('Agreed bank overdraft facility')) ?></legend>
            <input type="hidden" name="overdraft_configured" value="1">
            <label class="flex items-start gap-2 text-sm"><input type="checkbox" name="overdraft_enabled" value="1" <?= $hasOverdraft ? 'checked' : '' ?> aria-describedby="overdraft-help"><span><?= pl_e(pl_t('An agreed overdraft facility exists for this bank account')) ?></span></label>
            <label class="field" for="overdraft-limit"><?= pl_e(pl_t('Agreed limit in {currency}', ['currency' => $facilityCurrency])) ?><input class="input" id="overdraft-limit" name="overdraft_limit" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'overdraft_limit', '0')) ?>" maxlength="21" pattern="(?:0|[1-9][0-9]*)(?:\.[0-9]{1,4})?" aria-describedby="overdraft-help"></label>
            <p id="overdraft-help" class="text-xs text-ink-muted"><?= pl_e(pl_t('Enter the limit actually agreed with the bank, in this account’s designated currency or the book currency when none is designated. Other currencies receive no borrowing allowance. Turning the facility off sets its permitted floor to zero. Saving changes requires a reason and preserves existing journals; it does not arrange borrowing or confirm cleared or available bank funds.')) ?></p>
        </fieldset>
        <?php endif; ?>
        <label class="field"><?= pl_e($account ? pl_t('Reason for this change') : pl_t('Reason for adding this account')) ?><textarea name="reason" rows="2" maxlength="500" required><?= pl_e(pl_web_text($input, 'reason')) ?></textarea></label>
        <div class="panel-actions"><?php if ($account): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/account', ['id' => $account['id']])) ?>"><?= pl_e(pl_t('Open statement')) ?></a><?php endif; ?></div>
    </form>
    <?php else: ?>
    <dl class="record-details"><div><dt><?= pl_e(pl_t('Code')) ?></dt><dd><?= pl_e($account['code']) ?></dd></div><div><dt><?= pl_e(pl_t('Classification')) ?></dt><dd><?= pl_e(pl_t($types[$account['type']] ?? $account['type'])) ?></dd></div><div><dt><?= pl_e(pl_t('Purpose')) ?></dt><dd><?= pl_e(pl_t($roles[$account['role'] ?? ''] ?? 'No operational purpose')) ?></dd></div><div><dt><?= pl_e(pl_t('Status')) ?></dt><dd><?= pl_e($account['is_active'] ? pl_t('Active') : pl_t('Inactive')) ?></dd></div></dl>
    <?php if ($account['role'] === 'cash_bank'): ?><p><?= pl_e(pl_t($moneyKinds[$account['money_kind'] ?? ''])) ?></p><?php endif; ?>
    <?php if ($account['money_kind'] === 'bank'): ?><p><?= pl_e($account['overdraft_enabled'] ? pl_t('Agreed overdraft limit: {currency} {limit}.', ['currency' => $facilityCurrency, 'limit' => pl_money($account['overdraft_limit'])]) : pl_t('No overdraft facility is configured; the permitted floor is zero.')) ?></p><?php endif; ?>
    <a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/account', ['id' => $account['id']])) ?>"><?= pl_e(pl_t('Open statement')) ?></a>
    <p class="muted small core-footnote"><?= pl_e(pl_demo_enabled() ? pl_t('Account changes are unavailable in the public demo.') : pl_t('Your role can view accounts and their history.')) ?></p>
    <?php endif; ?>
    <?php if ($account): ?><details class="text-xs border-t border-border pt-3"><summary><?= pl_e(pl_t('Account history')) ?> <span class="muted">· <?= pl_e(pl_t('Latest 50 changes')) ?></span></summary><?php if (!$history): ?><p class="muted small"><?= pl_e(pl_t('No account-management changes have been recorded.')) ?></p><?php endif; ?><ol><?php foreach ($history as $event): ?><li><strong><?= pl_e(ucfirst(str_replace('_', ' ', $event['action']))) ?></strong> · <?= pl_e($event['display_name']) ?><p><?= pl_e($event['reason']) ?></p><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $event['recorded_at']) . 'Z') ?>"><?= pl_e(pl_t('{time} UTC', ['time' => $event['recorded_at']])) ?></time></li><?php endforeach; ?></ol></details><?php endif; ?>
    <?php else: ?><div class="empty-state"><h2 class="section-title" id="account-detail-title"><?= pl_e($isNew ? pl_t('Account changes unavailable') : pl_t('Choose an account')) ?></h2><p><?= pl_e($isNew ? pl_t('Account changes are available to authorised administrators outside the public demo.') : pl_t('Inspect its classification, open its statement or review its history.')) ?></p></div><?php endif; ?>
</section></div>
</div>
