<?php declare(strict_types=1); ?>
<section class="flex flex-col gap-4 py-5">
    <?php pl_ui_page_header(pl_t('Connections'), pl_t('Connect your tools to {company}. Each credential reads only this company and book using your current permissions.', ['company' => $company['name']]),static function () use ($endpoint):void { if ($endpoint!==''): ?><button class="btn btn-primary" form="connection-create"><?= pl_e(pl_t('Create token')) ?></button><?php endif; }); ?>
    <?php if ($message !== ''): ?><p class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($message) ?></p><?php endif; ?>
    <section class="rounded-panel border border-border bg-surface p-4 text-sm"><h2 class="section-title"><?= pl_e(pl_t('Connect a client')) ?></h2><p><?= pl_e(pl_t('Use the Streamable HTTP endpoint below with a personal token, or choose OAuth in a client that supports it. OAuth opens a sign-in and consent screen here.')) ?></p><div class="flex items-center gap-2 mb-3"><code id="connection-endpoint" class="break-all text-xs"><?= pl_e($endpoint) ?></code><button type="button" class="btn btn-secondary btn-sm" data-copy-from="connection-endpoint" hidden><?= pl_e(pl_t('Copy endpoint')) ?></button><span class="text-xs text-ink-muted" data-copy-status role="status"></span></div><p><?= pl_e(pl_t('Access is read-only. Your client receives financial results and may store or send them according to its own settings. Use a separate credential for each private agent or workflow. Shared chat services should use a separate OAuth connection for each user.')) ?></p>
    <?php if (pl_demo_enabled()): ?><p class="alert"><?= pl_e(pl_t('Sample access ends at the next hourly reset. After it expires, start a new sample and reconnect your client. Refresh tokens cannot extend demo access.')) ?></p><?php else: ?><p><?= pl_e(pl_t('Personal tokens and OAuth grants expire after 30 days. OAuth access tokens last up to 15 minutes. Revocation takes effect on the next request.')) ?></p><?php endif; ?></section>
    <?php if ($issued): ?><section class="rounded-panel border border-border bg-surface p-4 text-sm" aria-labelledby="new-token-heading"><h2 id="new-token-heading"><?= pl_e(pl_t('Save your token now')) ?></h2><p><?= pl_e(pl_t('This is its only display. Copy it into your client\'s private credential settings. Reloading this page cannot retrieve it.')) ?></p><div class="field"><label for="new-token"><?= pl_e(pl_t('Personal token')) ?></label><textarea class="textarea" id="new-token" readonly rows="3" autocomplete="off" spellcheck="false"><?= pl_e($issued['token']) ?></textarea><button type="button" class="btn btn-secondary btn-sm self-start" data-copy-from="new-token" hidden><?= pl_e(pl_t('Copy token')) ?></button><span class="text-xs text-ink-muted" data-copy-status role="status"></span></div><p><?= pl_e(pl_t('Access expires')) ?> <time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $issued['connection']['expires_at']) . 'Z') ?>"><?= pl_e(pl_t('{expires} UTC', ['expires' => $issued['connection']['expires_at']])) ?></time>.</p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/connections')) ?>"><?= pl_e(pl_t('I saved the token')) ?></a></section><?php endif; ?>
    <?php if ($endpoint !== ''): ?><section class="rounded-panel border border-border bg-surface p-4 text-sm"><h2 class="section-title"><?= pl_e(pl_t('Create a personal token')) ?></h2><form id="connection-create" method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="create"><div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div class="field"><label for="connection-name"><?= pl_e(pl_t('Connection name')) ?></label><input class="input" id="connection-name" name="name" maxlength="120" required placeholder="<?= pl_e(pl_t('For example, my private reporting agent')) ?>" autocomplete="off" value="<?= pl_e(pl_web_text($input,'name')) ?>"></div><div><?php pl_ui_connection_scope('connection-scope',pl_web_text($input,'access_mode','reports')); ?></div></div><p><?= pl_e(pl_t('Company:')) ?> <strong><?= pl_e($company['name']) ?></strong> <?= pl_e(pl_t('· Book {book} · Read access', ['book' => (string) $company['book_id']])) ?></p></form></section><?php endif; ?>
    <h2 class="section-title"><?= pl_e(pl_t('Recent connections for this book')) ?></h2><p><?= pl_e(pl_t('Owners can revoke any connection that includes their company. Revoking a connection ends all of its company grants.')) ?></p>
    <div class="table-wrap"><table class="table"><thead><tr><th><?= pl_e(pl_t('Name')) ?></th><th><?= pl_e(pl_t('Kind')) ?></th><th><?= pl_e(pl_t('Scope')) ?></th><th><?= pl_e(pl_t('Status')) ?></th><th><?= pl_e(pl_t('Expires')) ?></th><th><?= pl_e(pl_t('Action')) ?></th></tr></thead><tbody>
    <?php foreach ($connections as $connection): ?><tr><th scope="row"><?= pl_e($connection['name']) ?></th><td><?= pl_e($connection['kind'] === 'personal' ? pl_t('Personal token') : pl_t('OAuth')) ?></td><td><?= pl_e($connection['access_mode'] === 'reports' ? pl_t('Report-only') : pl_t('Full read')) ?></td><td><?= pl_e($connection['revoked_at'] !== null ? pl_t('Revoked') : ($connection['expires_at'] <= gmdate('Y-m-d H:i:s') ? pl_t('Expired') : pl_t('Active'))) ?></td><td><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $connection['expires_at']) . 'Z') ?>"><?= pl_e(pl_t('{expires} UTC', ['expires' => $connection['expires_at']])) ?></time></td><td><?php if ($connection['revoked_at'] === null): ?><?php pl_ui_confirmation(pl_t('Revoke {name}', ['name' => $connection['name']]), pl_t('This ends all company grants held by this connection on its next request. The client will need a new token or new consent to reconnect.'), static function () use ($company, $connection): void { ?><form method="post" action="<?= pl_e(pl_url('/connections')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="connection_id" value="<?= pl_e($connection['id']) ?>"><button class="btn btn-danger" name="action" value="revoke"><?= pl_e(pl_t('Confirm revoke')) ?></button></form><?php }); ?><?php endif; ?></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php if ($connections === []): ?><p><?= pl_e(pl_t('No connections have been created for this book.')) ?></p><?php endif; ?>
</section>
