<?php
 declare(strict_types=1);
 $kind = pl_web_text($input, 'kind', 'expense');
 $parties = $parties ?? [];
 $cashPreview = $cashPreview ?? null;
 $cashAccounts = array_filter($company['accounts'], static fn (array $a): bool => $a['role'] === 'cash_bank' && $a['type'] === 'asset' && $a['is_active']);
 $categoryAccounts = array_filter($company['accounts'], static fn (array $a): bool => $a['type'] === ($kind === 'receipt' ? 'income' : 'expense') && $a['role'] === $a['type'] && $a['is_active']);
 $defaultCash = array_key_first($cashAccounts);
 $cashId = array_key_exists('money_account_id',$input) ? pl_web_id($input,'money_account_id') : ($defaultCash === null ? 0 : (int)$cashAccounts[$defaultCash]['id']);
 $errors = $form['message'] !== '' && $form['input'] !== [] ? pl_web_editor_errors($input, 'transaction') : [];
 if (in_array(pl_web_text($input,'editor_action'),['create_party','open_party','search_party'],true)) { $errors=[]; }
 if (isset($errors['counterparty']) && (!$document || $document['party_id'] !== null)) { unset($errors['counterparty']); $errors['party_id']=pl_t('Choose a party or explicitly create one.'); }
 $fields = ['date'=>['transaction-date',pl_t('Date')],'amount'=>['transaction-amount',pl_t('Amount')],'counterparty'=>['legacy-counterparty',pl_t('Historical name')],'party_id'=>['transaction-party',pl_t($kind === 'receipt' ? 'Received from' : 'Paid to')],
     'money_account_id'=>['transaction-cash',pl_t($kind === 'receipt' ? 'Received into account' : 'Paid from account')],'category_account_id'=>['transaction-category',pl_t($kind === 'receipt' ? 'Income category' : 'Expense category')],
     'reference'=>['transaction-reference',pl_t('Reference')],'memo'=>['transaction-memo',pl_t('Memo')]];
 $returnPath = pl_workflow_url($document ? '/transactions/detail' : '/transactions', ($document ? ['id'=>$document['id']] : []) + $returnFilters);
?>
<section class="py-5" aria-labelledby="transaction-editor-title">
    <a class="back-link" href="<?= pl_e($returnPath) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t(($returnFilters['kind'] ?? '') === 'expense' ? 'Back to expenses' : (($returnFilters['kind'] ?? '') === 'receipt' ? 'Back to receipts' : 'Back to transactions'))) ?></a>
    <?php pl_ui_document_header($document ? pl_t('{number} · Edit draft', ['number' => $document['number']]) : pl_t('New {kind}', ['kind' => $kind === 'receipt' ? pl_t('receipt') : pl_t('expense')]), 'draft', static function () use ($returnPath): void { ?>
        <a class="btn btn-ghost" href="<?= pl_e($returnPath) ?>"><?= pl_e(pl_t('Cancel')) ?></a><button class="btn btn-primary" form="transaction-editor" type="submit"><?= pl_e(pl_t('Save draft')) ?></button>
    <?php }, 'transaction-editor-title'); ?>
    <?php if ($form['message']): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-error-message <?= $errors===[]?'data-form-error':'' ?>><strong><?= pl_e(pl_t('Your draft has not been changed.')) ?></strong><p><?= pl_e($form['message']) ?></p><p><?php if ($form['input'] !== []): ?><?= pl_e(pl_t('Your submitted values are kept below.')) ?><?php else: ?><?= pl_e(pl_t('The selected business changed. Enter the transaction again.')) ?><?php endif; ?><?php if ($document): ?> <a href="<?= pl_e(pl_workflow_url('/' . $screen . '/edit', ['id'=>$document['id']])) ?>"><?= pl_e(pl_t('Reload the latest saved version')) ?></a> <?= pl_e(pl_t('to resolve a revision conflict.')) ?><?php endif; ?></p></div><?php endif; ?>
    <?php pl_ui_error_summary($errors, $fields); ?>
    <form id="transaction-editor" class="panel doc-body" method="post" action="<?= pl_e(pl_workflow_url('/' . $screen . '/save')) ?>" data-document-form>
        <?= pl_csrf_field() ?><?= pl_scope_fields($company) ?>
        <?php pl_ui_return_filters($returnFilters); ?>
        <input type="hidden" name="creation_key" value="<?= pl_e(pl_web_text($input,'creation_key')) ?>">
        <?php if ($document): ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><input type="hidden" name="revision" value="<?= pl_web_id($input,'revision',(int)$document['revision']) ?>"><?php endif; ?>
        <input type="hidden" name="kind" value="<?= pl_e($kind) ?>">
        <p class="text-sm text-ink-muted"><?= pl_e(pl_t($kind === 'receipt' ? 'Record money received into your cash or bank account.' : 'Record money paid from your cash or bank account.')) ?></p>
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <?php pl_ui_field('transaction-date',pl_t('Date'),static function () use ($input,$document,$form,$errors): void { ?><input class="input" id="transaction-date"<?= pl_ui_error_attributes('transaction-date',$errors['date']??'') ?> type="date" name="date" value="<?= pl_e(pl_web_text($input,'date')) ?>" required <?= !$document && !$form['input'] ? 'data-local-today' : '' ?>><?php }, pl_t('The accounting date for this transaction.'), $errors['date']??''); ?>
        <?php pl_ui_field('transaction-amount',pl_t('Amount ({currency})', ['currency' => $company['currency']]),static function () use ($input,$errors): void { ?><input class="input input-amount" id="transaction-amount"<?= pl_ui_error_attributes('transaction-amount',$errors['amount']??'') ?> type="text" inputmode="decimal" name="amount" value="<?= pl_e(pl_web_text($input,'amount')) ?>" placeholder="0.00" maxlength="21" pattern="[0-9]+(\.[0-9]{1,4})?" required autocomplete="off"><?php }, pl_t('Use a decimal point, without separators.'), $errors['amount']??''); ?>
        <div class="party-picker sm:col-span-2" data-party-picker>
            <div class="inline-heading"><label class="field-label" for="transaction-party"><?= pl_e(pl_t($kind === 'receipt' ? 'Received from' : 'Paid to')) ?></label><?php pl_ui_help('transaction-party'); ?></div>
            <label class="sr-only" for="party-search"><?= pl_e(pl_t('Search all customers and suppliers')) ?></label>
            <div class="flex gap-2"><input class="input" id="party-search" type="search" name="party_search" value="<?= pl_e(pl_web_text($input,'party_search')) ?>" placeholder="<?= pl_e(pl_t('Search name or trading name')) ?>" maxlength="160" data-party-search><button class="btn btn-secondary btn-sm" name="editor_action" value="search_party" type="submit" formnovalidate><?= pl_e(pl_t('Search all parties')) ?></button></div>
            <select class="select" id="transaction-party" name="party_id"<?= pl_ui_error_attributes('transaction-party',$errors['party_id']??'') ?> <?= !$document || $document['party_id'] !== null ? 'required' : '' ?> data-party-select>
                <option value=""><?= pl_e(pl_t('Choose a party')) ?></option>
                <?php foreach ($parties as $party): ?><option value="<?= (int)$party['id'] ?>" <?= pl_web_id($input,'party_id') === (int)$party['id'] ? 'selected' : '' ?>><?= pl_e($party['legal_name'].($party['trading_name'] ? ' · '.$party['trading_name'] : '').' · '.$party['country_code'].' · #'.$party['id'].(!in_array($party['status'],['draft','under_review','approved'],true)?' · '.pl_t('Unavailable — choose another'):'')) ?></option><?php endforeach; ?>
            </select>
            <?php if (isset($errors['party_id'])): ?><p class="field-error-text" id="transaction-party-error"><?= pl_e($errors['party_id']) ?></p><?php endif; ?>
            <p class="text-xs text-ink-muted" role="status" data-party-results data-empty-message="<?= pl_e(pl_t('No matching parties in this list. Use Search all parties, change the name, or create a party.')) ?>"><?= pl_e(pl_t($parties === [] ? 'No matching parties. Change the search or explicitly create a party.' : 'Search includes both customer and supplier roles. Up to 100 matches are shown; search to narrow the list.')) ?></p>
            <?php if ($document && $document['party_id'] === null): ?><label for="legacy-counterparty"><?= pl_e(pl_t('Historical name (link a party explicitly when known)')) ?></label><input class="input" id="legacy-counterparty"<?= pl_ui_error_attributes('legacy-counterparty',$errors['counterparty']??'') ?> name="counterparty" value="<?= pl_e(pl_web_text($input,'counterparty')) ?>" maxlength="160"><?php if (isset($errors['counterparty'])): ?><p class="field-error-text" id="legacy-counterparty-error"><?= pl_e($errors['counterparty']) ?></p><?php endif; ?><?php endif; ?>
            <?php if (!pl_demo_enabled()): ?><button class="btn btn-ghost btn-sm" name="editor_action" value="open_party" type="submit" formnovalidate><?= pl_icon('plus') ?> <?= pl_e(pl_t('Create party')) ?></button><?php else: ?><p class="text-xs text-ink-muted"><?= pl_e(pl_t('Party creation is unavailable in the shared demo. Choose an existing sample party.')) ?></p><?php endif; ?>
            <p class="text-xs text-ink-muted"><?= pl_e(pl_t('This identifies the payer or payee. It does not settle an invoice or bill.')) ?> <a href="<?= pl_e(pl_url($kind === 'receipt' ? '/ar' : '/ap')) ?>"><?= pl_e(pl_t('Open invoices or bills for settlement')) ?></a></p>
        </div>
        <div class="field"><div class="inline-heading"><label class="field-label" for="transaction-cash"><?= pl_e(pl_t($kind === 'receipt' ? 'Received into account' : 'Paid from account')) ?></label><?php pl_ui_help('cash-availability'); ?></div><select class="select" id="transaction-cash"<?= pl_ui_error_attributes('transaction-cash',$errors['money_account_id']??'') ?> name="money_account_id" required><option value=""><?= pl_e(pl_t('Choose a cash / bank account')) ?></option><?php if ($cashId && !in_array($cashId,array_map(static fn(array $a):int=>(int)$a['id'],$cashAccounts),true)): ?><option value="<?= $cashId ?>" selected><?= pl_e(pl_t('Unavailable saved account — choose another')) ?></option><?php endif; ?><?php foreach ($cashAccounts as $account): ?><option value="<?= (int)$account['id'] ?>" <?= $cashId === (int)$account['id'] ? 'selected' : '' ?>><?= pl_e($account['name']) ?></option><?php endforeach; ?></select><?php if (!empty($errors['money_account_id'])): ?><p class="field-error-text" id="transaction-cash-error"><?= pl_e($errors['money_account_id']) ?></p><?php endif; ?></div>
        <?php pl_ui_field('transaction-category',pl_t($kind === 'receipt' ? 'Income category' : 'Expense category'),static function () use ($categoryAccounts,$input,$errors): void { ?><select class="select" id="transaction-category"<?= pl_ui_error_attributes('transaction-category',$errors['category_account_id']??'') ?> name="category_account_id" required><option value=""><?= pl_e(pl_t('Choose a category')) ?></option><?php $categoryId=pl_web_id($input,'category_account_id'); if ($categoryId && !in_array($categoryId,array_map(static fn(array $a):int=>(int)$a['id'],$categoryAccounts),true)): ?><option value="<?= $categoryId ?>" selected><?= pl_e(pl_t('Unavailable saved category — choose another')) ?></option><?php endif; ?><?php foreach ($categoryAccounts as $account): ?><option value="<?= (int)$account['id'] ?>" data-category-kind="<?= $account['type'] === 'income' ? 'receipt' : 'expense' ?>" <?= pl_web_id($input,'category_account_id') === (int)$account['id'] ? 'selected' : '' ?>><?= pl_e($account['name']) ?></option><?php endforeach; ?></select><?php }, '', $errors['category_account_id']??''); ?>
        <?php pl_ui_field('transaction-reference',pl_t('Reference (optional)'),static function () use ($input,$errors): void { ?><input class="input" id="transaction-reference"<?= pl_ui_error_attributes('transaction-reference',$errors['reference']??'') ?> name="reference" value="<?= pl_e(pl_web_text($input,'reference')) ?>" maxlength="120" placeholder="<?= pl_e(pl_t('Receipt number or your own reference')) ?>"><?php }, '', $errors['reference']??''); ?>
        <div class="sm:col-span-2 lg:col-span-4"><?php pl_ui_field('transaction-memo',pl_t('Memo (optional)'),static function () use ($input,$errors): void { ?><textarea class="textarea" id="transaction-memo"<?= pl_ui_error_attributes('transaction-memo',$errors['memo']??'') ?> name="memo" rows="2" maxlength="500" placeholder="<?= pl_e(pl_t('What was this transaction for?')) ?>"><?= pl_e(pl_web_text($input,'memo')) ?></textarea><?php }, '', $errors['memo']??''); ?></div>
        </div>
        <?php if (in_array(pl_web_text($input,'editor_action'),['open_party','create_party'],true) && !pl_demo_enabled()): ?>
        <fieldset class="panel p-3" aria-labelledby="new-party-title"><legend id="new-party-title"><?= pl_e(pl_t('Create and select a party')) ?></legend>
            <input type="hidden" name="party_creation_key" value="<?= pl_e(pl_web_text($input,'party_creation_key') ?: bin2hex(random_bytes(24))) ?>">
            <label for="new-party-name"><?= pl_e(pl_t('Legal name')) ?></label><input class="input" id="new-party-name" name="new_party_name" maxlength="160" value="<?= pl_e(pl_web_text($input,'new_party_name')) ?>">
            <label for="new-party-type"><?= pl_e(pl_t('Entity type')) ?></label><select class="select" id="new-party-type" name="new_party_type"><?php foreach (['business'=>'Business','individual'=>'Individual'] as $value=>$label): ?><option value="<?= $value ?>" <?= pl_web_text($input,'new_party_type','business')===$value?'selected':'' ?>><?= pl_e(pl_t($label)) ?></option><?php endforeach; ?></select>
            <label for="new-party-country"><?= pl_e(pl_t('Country code (two letters)')) ?></label><input class="input" id="new-party-country" name="new_party_country" maxlength="2" value="<?= pl_e(pl_web_text($input,'new_party_country')) ?>" placeholder="<?= pl_e(pl_t('For example, {code}', ['code'=>'PK'])) ?>">
            <label><input type="checkbox" name="new_party_customer" value="1" <?= isset($input['new_party_customer']) || (pl_web_text($input,'editor_action')==='open_party' && $kind==='receipt')?'checked':'' ?>> <?= pl_e(pl_t('Customer')) ?></label>
            <label><input type="checkbox" name="new_party_vendor" value="1" <?= isset($input['new_party_vendor']) || (pl_web_text($input,'editor_action')==='open_party' && $kind==='expense')?'checked':'' ?>> <?= pl_e(pl_t('Supplier')) ?></label>
            <p class="text-xs text-ink-muted"><?= pl_e(pl_t('Choose either or both roles. Creating a master record does not approve it or post this transaction.')) ?></p>
            <button class="btn btn-primary" type="submit" name="editor_action" value="create_party" formnovalidate><?= pl_e(pl_t('Create and select')) ?></button><button class="btn btn-ghost" type="submit" name="editor_action" value="cancel_party" formnovalidate><?= pl_e(pl_t('Cancel party creation')) ?></button>
        </fieldset>
        <?php endif; ?>
        <?php if ($cashPreview): ?><div data-cash-preview data-preview-date="<?= pl_e($cashPreview['date']) ?>" class="alert <?= ($cashPreview['blocked_payment'] ?? false) ? 'alert-danger' : '' ?>" role="status"><p><?= pl_e(pl_t('Posted book balance as of {date}: {balance}. Proposed payment: {payment}. Projected book balance: {projected}.',['date'=>$cashPreview['date'],'balance'=>$cashPreview['currency'].' '.pl_money($cashPreview['balance']),'payment'=>$cashPreview['currency'].' '.pl_money($cashPreview['payment']),'projected'=>$cashPreview['currency'].' '.pl_money($cashPreview['projected_balance'])])) ?></p><?php if (isset($cashPreview['payment_currency_balance']) && bccomp($cashPreview['payment_currency_balance'],$cashPreview['balance'],4)!==0): ?><p><?= pl_e(pl_t('Recorded balance in {currency}: {balance}. This payment would leave {projected} {currency}.',['currency'=>$cashPreview['payment_currency'],'balance'=>pl_money($cashPreview['payment_currency_balance']),'projected'=>pl_money($cashPreview['projected_currency_balance'])])) ?></p><?php endif; ?>
            <?php if ($cashPreview['money_kind']==='bank'): ?><p><?php if ($cashPreview['overdraft_enabled']??false): ?><?= pl_e(pl_t('Agreed overdraft limit: {currency} {limit}. In strict mode, the posting floor is {currency} {floor}.',['currency'=>$cashPreview['facility_currency'],'limit'=>pl_money($cashPreview['overdraft_limit']),'floor'=>pl_money($cashPreview['permitted_floor'])])) ?><?php else: ?><?= pl_e(pl_t('No overdraft facility is recorded. Strict mode blocks payments that create or worsen a balance below zero.')) ?><?php endif; ?></p><?php if (($cashPreview['overdraft_enabled']??false) && $cashPreview['facility_currency']!==$cashPreview['payment_currency']): ?><p><?= pl_e(pl_t('This payment is in {currency}; the facility in another currency does not provide an overdraft allowance for this payment.',['currency'=>$cashPreview['payment_currency']])) ?></p><?php endif; ?><p><?= pl_e(pl_t('These are posted book balances, not cleared or available funds confirmed by the bank. Unpresented payments, holds and bank charges may differ.')) ?></p><?php endif; ?>
            <p><?= pl_e(pl_t('Cash shortfall policy: {policy}.', ['policy' => pl_t(($cashPreview['cash_shortfall_policy'] ?? 'warning') === 'strict' ? 'Strict' : 'Warning')])) ?></p><?php if ($cashPreview['warning']): ?><p><?= pl_e($cashPreview['warning']) ?></p><?php endif; ?><p><?= pl_e(pl_t('Update the posting preview after changing the date, account or amount. Drafts do not change these balances.')) ?></p></div><p class="text-xs text-ink-muted" data-cash-preview-stale hidden><?= pl_e(pl_t('The cash balance preview is out of date. Update the posting preview to recalculate it.')) ?></p><?php endif; ?>
        <p class="text-xs text-ink-muted"><?= pl_e(pl_t('This entry uses one category in {currency}. Split entries, tax and foreign-currency amounts are not supported by this form.', ['currency' => $company['currency']])) ?></p>
        <section class="rounded-panel border border-border p-3" aria-labelledby="posting-preview-title">
            <div class="flex flex-wrap items-center justify-between gap-2"><h2 class="section-title" id="posting-preview-title"><?= pl_e(pl_t('Posting preview')) ?></h2><button class="btn btn-secondary btn-sm" name="editor_action" value="preview" type="submit"><?= pl_e(pl_t('Update posting preview')) ?></button></div>
            <?php if ($preview): ?><div class="mt-3" data-server-preview><?php $entryLines=$preview['lines']; require __DIR__ . '/../partials/entry.php'; ?></div><p class="text-xs text-ink-muted mt-2"><?= pl_e(pl_t('This preview uses the same posting payload as the saved transaction. Update it after changing fields. Permissions, revisions and open periods are checked again when posting.')) ?></p><?php else: ?><p class="text-xs text-ink-muted mt-2"><?= pl_e(pl_t('Enter the transaction details, then update the preview to inspect the exact journal lines without saving or posting.')) ?></p><?php endif; ?>
            <p class="text-xs text-ink-muted mt-2"><?= pl_e(pl_t('Posting adds this transaction to reports. A saved draft does not change your books.')) ?></p>
        </section>
    </form>
</section>
