<?php
declare(strict_types=1);
$journalRows = is_array($input['lines'] ?? null) ? array_values($input['lines']) : [];
$hasFailure = pl_web_text($form, 'message') !== '';
$errors = $hasFailure ? pl_web_editor_errors($input, 'journal') : [];
$fields = ['date'=>['journal-date',pl_t('Journal date')],'reference'=>['journal-reference',pl_t('Reference')],'description'=>['journal-description',pl_t('Journal description')]];
if ($journalRows === []) { $journalRows[] = []; }
foreach ($journalRows as $index=>$unused) {
    foreach (['account_id'=>'Account, line {n}','debit'=>'Debit, line {n}','credit'=>'Credit, line {n}'] as $field=>$labelTemplate) { $fields['lines.'.$index.'.'.$field]=['journal-line-'.$index.'-'.$field, pl_t($labelTemplate, ['n' => $index+1])]; }
}
$accountIds = array_map(static fn (array $row): int => (int) $row['id'], $company['accounts']);
?>
<section class="page-wrap core-page core-editor" aria-labelledby="journal-editor-title">
<a class="back-link" href="<?= pl_e(pl_workflow_url($draft ? '/general-journals/detail' : '/general-journals', $draft ? ['id' => $draft['id'],'return_filters'=>$filters] : $filters)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to {target}', ['target' => $draft ? pl_t('journal') : pl_t('journals')])) ?></a>
<?php pl_ui_document_header($draft ? pl_t('{number} · Edit draft', ['number' => $draft['number']]) : pl_t('New general journal'), 'draft', static function () use ($company, $draft, $filters): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_workflow_url($draft ? '/general-journals/detail' : '/general-journals', $draft ? ['id'=>$draft['id'],'return_filters'=>$filters] : $filters)) ?>"><?= pl_e(pl_t('Cancel')) ?></a>
<button class="btn btn-secondary" form="journal-editor" type="submit" <?= $company['setup_status'] !== 'ready' ? 'disabled' : '' ?>><?= pl_e(pl_t('Save draft and review')) ?></button>
<button class="btn btn-primary" form="journal-editor" name="editor_action" value="post_reviewed_journal" type="submit" <?= $company['setup_status'] !== 'ready' ? 'disabled' : '' ?>><?= pl_e(pl_t('Post journal')) ?></button>
<?php }, 'journal-editor-title'); ?>
<?php if ($hasFailure): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-error-message <?= $errors===[]?'data-form-error':'' ?>><strong><?= pl_e(pl_t('Your draft was not saved or posted.')) ?></strong><p><?= pl_e(pl_web_text($form, 'message')) ?></p><p><?= pl_e(pl_t('Your submitted values are retained.')) ?><?php if ($draft): ?> <a href="<?= pl_e(pl_workflow_url('/general-journals/edit', ['id' => $draft['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Reload the latest saved version')) ?></a> <?= pl_e(pl_t('before resolving a revision conflict.')) ?><?php endif; ?></p></div><?php endif; ?>
<?php pl_ui_error_summary($errors,$fields); ?>
<form id="journal-editor" method="post" action="<?= pl_e(pl_workflow_url('/general-journals/save')) ?>" class="panel core-journal-form" data-core-journal>
<?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="creation_key" value="<?= pl_e(pl_web_text($input, 'creation_key')) ?>">
<?php if ($draft): ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><input type="hidden" name="revision" value="<?= pl_web_id($input, 'revision') ?>"><?php endif; ?>
<div class="form-grid core-journal-meta">
<?php pl_ui_field('journal-date', pl_t('Journal date'), static function () use ($input, $draft, $hasFailure,$errors): void { ?><input class="input" id="journal-date"<?= pl_ui_error_attributes('journal-date',$errors['date']??'') ?> type="date" name="date" value="<?= pl_e(pl_web_text($input, 'date')) ?>" required <?= !$draft && !$hasFailure ? 'data-local-today' : '' ?>><?php }, '', $errors['date']??''); ?>
<?php pl_ui_field('journal-reference', pl_t('Reference (optional)'), static function () use ($input,$errors): void { ?><input class="input" id="journal-reference"<?= pl_ui_error_attributes('journal-reference',$errors['reference']??'') ?> name="reference" value="<?= pl_e(pl_web_text($input, 'reference')) ?>" maxlength="120"><?php }, '', $errors['reference']??''); ?>
<?php pl_ui_field('journal-description', pl_t('Journal description'), static function () use ($input,$errors): void { ?><textarea class="textarea journal-description" id="journal-description"<?= pl_ui_error_attributes('journal-description',$errors['description']??'') ?> name="description" rows="1" maxlength="500" required placeholder="<?= pl_e(pl_t('Explain the purpose of this entry.')) ?>"><?= pl_e(pl_web_text($input, 'description')) ?></textarea><?php }, '', $errors['description']??''); ?>
</div>
<div class="section-heading"><h2 class="section-title"><?= pl_e(pl_t('Journal lines')) ?></h2><span class="muted small"><?= pl_e(pl_t('Up to 100 lines')) ?></span></div>
<p class="muted small" id="journal-line-help"><?= pl_e(pl_t('Enter one positive debit or credit per line, using a decimal point and up to four decimal places. Leave unused rows completely blank. An unbalanced draft can be saved for later.')) ?></p>
<div class="table-wrap core-lines-wrap" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Journal entry lines; scroll horizontally on smaller screens')) ?>"><table class="table doc-lines-table core-line-editor" aria-describedby="journal-line-help"><caption class="sr-only"><?= pl_e(pl_t('Journal draft lines in {currency}', ['currency' => $company['currency']])) ?></caption><thead><tr><th scope="col"><?= pl_e(pl_t('Line')) ?></th><th scope="col"><?= pl_e(pl_t('Account')) ?></th><th scope="col" class="amount"><?= pl_e(pl_t('Debit')) ?></th><th scope="col" class="amount"><?= pl_e(pl_t('Credit')) ?></th><th scope="col"><?= pl_e(pl_t('Description')) ?> <span class="optional"><?= pl_e(pl_t('optional')) ?></span></th><th scope="col"><span class="sr-only"><?= pl_e(pl_t('Actions')) ?></span></th></tr></thead><tbody data-journal-rows>
<?php foreach ($journalRows as $lineIndex => $rawLine): $line = is_array($rawLine) ? $rawLine : []; $lineAccountId = pl_web_id($line, 'account_id'); ?>
<tr data-journal-row><td class="core-line-number"><span data-line-number><?= $lineIndex + 1 ?></span></td>
<td data-line-field="account_id"><label><span class="sr-only" data-line-label="Account"><?= pl_e(pl_t('Account, line {n}', ['n' => $lineIndex + 1])) ?></span><select aria-label="<?= pl_e(pl_t('Account, line {n}', ['n' => $lineIndex + 1])) ?>" class="select" id="journal-line-<?= $lineIndex ?>-account_id"<?= pl_ui_error_attributes('journal-line-'.$lineIndex.'-account_id',$errors['lines.'.$lineIndex.'.account_id']??'') ?> name="lines[<?= $lineIndex ?>][account_id]" data-journal-account><option value=""><?= pl_e(pl_t('Choose account')) ?></option><?php if ($lineAccountId && !in_array($lineAccountId, $accountIds, true)): ?><option value="<?= $lineAccountId ?>" data-unavailable-account selected><?= pl_e(pl_t('Unavailable account {id} — choose another', ['id' => $lineAccountId])) ?></option><?php endif; ?><?php foreach ($company['accounts'] as $lineAccount): if (!$lineAccount['is_active'] && (int) $lineAccount['id'] !== $lineAccountId) { continue; } ?><option value="<?= (int) $lineAccount['id'] ?>" <?= !$lineAccount['is_active'] ? 'data-unavailable-account' : '' ?> <?= (int) $lineAccount['id'] === $lineAccountId ? 'selected' : '' ?>><?= pl_e($lineAccount['is_active'] ? $lineAccount['code'] . ' · ' . $lineAccount['name'] : pl_t('{code} · {name} (inactive — choose another)', ['code' => $lineAccount['code'], 'name' => $lineAccount['name']])) ?></option><?php endforeach; ?></select></label><?php if (isset($errors['lines.'.$lineIndex.'.account_id'])): ?><p class="field-error-text" id="journal-line-<?= $lineIndex ?>-account_id-error"><?= pl_e($errors['lines.'.$lineIndex.'.account_id']) ?></p><?php endif; ?></td>
<td data-line-field="debit"><label><span class="sr-only" data-line-label="Debit"><?= pl_e(pl_t('Debit, line {n}', ['n' => $lineIndex + 1])) ?></span><input class="input" id="journal-line-<?= $lineIndex ?>-debit"<?= pl_ui_error_attributes('journal-line-'.$lineIndex.'-debit',$errors['lines.'.$lineIndex.'.debit']??'') ?> name="lines[<?= $lineIndex ?>][debit]" value="<?= pl_e(pl_web_text($line, 'debit')) ?>" inputmode="decimal" maxlength="21" pattern="[0-9]+(\.[0-9]{1,4})?" placeholder="0.00" autocomplete="off" data-journal-amount="debit"></label><?php if (isset($errors['lines.'.$lineIndex.'.debit'])): ?><p class="field-error-text" id="journal-line-<?= $lineIndex ?>-debit-error"><?= pl_e($errors['lines.'.$lineIndex.'.debit']) ?></p><?php endif; ?></td>
<td data-line-field="credit"><label><span class="sr-only" data-line-label="Credit"><?= pl_e(pl_t('Credit, line {n}', ['n' => $lineIndex + 1])) ?></span><input class="input" id="journal-line-<?= $lineIndex ?>-credit"<?= pl_ui_error_attributes('journal-line-'.$lineIndex.'-credit',$errors['lines.'.$lineIndex.'.credit']??'') ?> name="lines[<?= $lineIndex ?>][credit]" value="<?= pl_e(pl_web_text($line, 'credit')) ?>" inputmode="decimal" maxlength="21" pattern="[0-9]+(\.[0-9]{1,4})?" placeholder="0.00" autocomplete="off" data-journal-amount="credit"></label><?php if (isset($errors['lines.'.$lineIndex.'.credit'])): ?><p class="field-error-text" id="journal-line-<?= $lineIndex ?>-credit-error"><?= pl_e($errors['lines.'.$lineIndex.'.credit']) ?></p><?php endif; ?></td>
<td data-line-field="description"><label><span class="sr-only" data-line-label="Description"><?= pl_e(pl_t('Description, line {n}', ['n' => $lineIndex + 1])) ?></span><input class="input" name="lines[<?= $lineIndex ?>][description]" value="<?= pl_e(pl_web_text($line, 'description')) ?>" maxlength="500"></label></td>
<td class="core-line-action"><button type="submit" name="remove_line" value="<?= $lineIndex ?>" formnovalidate class="btn btn-ghost btn-sm" data-remove-journal-row aria-label="<?= pl_e(pl_t('Remove line {n}', ['n' => $lineIndex + 1])) ?>"><?= pl_e(pl_t('Remove')) ?></button></td></tr>
<?php endforeach; ?>
</tbody></table></div>
<div class="core-line-toolbar"><button type="submit" name="editor_action" value="add_line" formnovalidate class="btn btn-secondary" data-add-journal-row><?= pl_icon('plus') ?> <?= pl_e(pl_t('Add line')) ?></button><p class="muted small" data-journal-message aria-live="polite"></p></div>
<div class="core-draft-totals" data-journal-totals data-fold="document total" hidden aria-live="polite" aria-atomic="true"><span><?= pl_e(pl_t('Debit')) ?> <strong class="amount" data-journal-total="debit">0.00</strong></span><span><?= pl_e(pl_t('Credit')) ?> <strong class="amount" data-journal-total="credit">0.00</strong></span><span data-journal-balance><?= pl_e(pl_t('Enter journal lines')) ?></span></div>
<noscript><p class="muted small"><?= pl_e(pl_t('Add or remove a line without saving. Save your draft to review the server-calculated totals before posting.')) ?></p></noscript>
<p class="text-xs text-ink-muted mt-3"><?= pl_e(pl_t('Posting adds this transaction to reports. A saved draft does not change your books.')) ?></p>
</form>
<p class="muted small core-footnote"><?= pl_e(pl_t('An opening-balance import is a separate reviewed workflow and is not available here.')) ?></p>
</section>
