<?php
declare(strict_types=1);
$accountNames = [];
foreach ($company['accounts'] as $detailAccount) { $accountNames[(int) $detailAccount['id']] = $detailAccount['code'] . ' · ' . $detailAccount['name']; }
$formInput = is_array($form['input'] ?? null) ? $form['input'] : [];
$hasFailure = pl_web_text($form, 'message') !== '';
$canPost = pl_can_write($company) && $company['setup_status'] === 'ready' && $draft['totals']['balanced'];
?>
<section class="flex flex-col gap-4 my-5 rounded-panel border border-border bg-surface" aria-labelledby="general-detail-title">
<?php pl_ui_document_header($draft['number'],$draft['status'],static function () use ($company,$draft,$filters,$canPost,$formInput,$hasFailure,$form): void { ?>
<a class="btn btn-ghost" href="<?= pl_e(pl_workflow_url('/general-journals',$filters)) ?>"><?= pl_e(pl_t('Back to journals')) ?></a><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>"><?= pl_e(pl_t('Trial balance')) ?></a>
<?php if ($draft['status'] === 'draft' && pl_can_write($company)): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/general-journals/edit', ['id' => $draft['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Edit draft')) ?></a><?php if ($canPost): ?><form method="post" action="<?= pl_e(pl_workflow_url('/general-journals/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><input type="hidden" name="revision" value="<?= array_key_exists('revision', $formInput) ? pl_web_id($formInput, 'revision') : (int) $draft['revision'] ?>"><input type="hidden" name="intent" value="post_reviewed_journal"><button class="btn btn-primary" type="submit"><?= pl_e(pl_t('Post journal')) ?></button></form><?php endif; ?><?php endif; ?>
<?php if ($draft['status']==='posted' && pl_can_write($company)) { pl_ui_sheet(pl_t('Reverse journal'),static function () use ($company,$draft,$filters,$formInput,$hasFailure,$form): void { ?>
<?php if ($hasFailure): ?><p class="alert alert-danger" role="alert"><?= pl_e(pl_web_text($form,'message')) ?></p><?php endif; ?>
<p><?= pl_e(pl_t('Create an opposite entry on the selected date, preserving the original and its history.')) ?></p><form method="post" action="<?= pl_e(pl_workflow_url('/general-journals/reverse')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $draft['id'] ?>"><div class="flex flex-col gap-3"><label class="field"><?= pl_e(pl_t('Reversal date')) ?><input class="input" type="date" name="date" value="<?= pl_e(pl_web_text($formInput, 'date', gmdate('Y-m-d'))) ?>" required <?= !isset($formInput['date']) ? 'data-local-today' : '' ?>></label><label class="field"><?= pl_e(pl_t('Reason')) ?><textarea class="textarea" name="reason" rows="3" maxlength="500" required><?= pl_e(pl_web_text($formInput, 'reason')) ?></textarea></label></div><button type="submit" class="btn btn-secondary"><?= pl_e(pl_t('Post linked reversal')) ?></button></form>
<?php },$hasFailure,'btn btn-primary'); } },'general-detail-title'); ?>
<p class="text-xs text-ink-muted px-5"><?= pl_e(pl_t('{date} · {currency} · Revision {revision}',['date'=>pl_date_label($draft['document_date']),'currency'=>$company['currency'],'revision'=>(int)$draft['revision']])) ?></p>
<?php if ($hasFailure): ?><div class="alert alert-danger mx-5" role="alert"><strong><?= pl_e(pl_t('The action could not be completed.')) ?></strong><p><?= pl_e(pl_web_text($form, 'message')) ?></p><p><a href="<?= pl_e(pl_workflow_url('/general-journals/detail', ['id' => $draft['id'],'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Reload and review the latest saved version')) ?></a> <?= pl_e(pl_t('before retrying a changed draft.')) ?></p></div><?php endif; ?>
<div class="doc-body"><dl class="dgrid"><div class="dgrid-row"><dt><?= pl_e(pl_t('Description')) ?></dt><dd><?= pl_e($draft['description']) ?></dd></div><div class="dgrid-row"><dt><?= pl_e(pl_t('Reference')) ?></dt><dd><?= pl_e($draft['reference'] ?: '—') ?></dd></div></dl>
<div class="flex items-center justify-between gap-3"><h2 class="section-title"><?= pl_e($draft['status'] === 'draft' ? pl_t('Review the entry') : pl_t('Saved entry')) ?></h2><span class="<?= $draft['totals']['balanced'] ? 'balanced-label' : 'core-unbalanced' ?>"><?= pl_e($draft['totals']['balanced'] ? pl_t('Balanced') : pl_t('Needs balancing')) ?></span></div>
<div class="table-wrap" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Journal debit and credit lines')) ?>"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Journal lines in {currency}',['currency'=>$company['currency']])) ?></caption><thead><tr><th scope="col"><?= pl_e(pl_t('Account')) ?></th><th scope="col"><?= pl_e(pl_t('Description')) ?></th><th scope="col" class="amount"><?= pl_e(pl_t('Debit')) ?></th><th scope="col" class="amount"><?= pl_e(pl_t('Credit')) ?></th></tr></thead><tbody>
<?php foreach ($draft['lines'] as $line): ?><tr><td><a href="<?= pl_e(pl_url('/reports/account', ['id' => $line['account_id']])) ?>"><?= pl_e($accountNames[(int) $line['account_id']] ?? pl_t('Account {id}', ['id' => (int) $line['account_id']])) ?></a></td><td><?= pl_e($line['description'] ?: '—') ?></td><td class="amount"><?= pl_e(pl_money($line['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; ?>
</tbody><tfoot><tr><th scope="row" colspan="2"><?= pl_e(pl_t('Total ({currency})',['currency'=>$company['currency']])) ?></th><td class="amount"><?= pl_e(pl_money($draft['totals']['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($draft['totals']['credit'])) ?></td></tr></tfoot></table></div>
<?php if (!$draft['totals']['balanced']): ?><p class="text-xs text-danger"><?= pl_e(pl_t('Debit minus credit: {amount}. Balance the draft before posting.',['amount'=>$company['currency'] . ' ' . pl_money($draft['totals']['difference'])])) ?></p><?php endif; ?>
<p class="text-xs text-ink-muted"><?= pl_e($draft['status'] === 'draft' ? pl_t('This saved draft has no effect on balances. Posting includes these lines in the accounts and reports.') : pl_t('Posted details are preserved. Corrections use a linked reversal.')) ?></p>
<div class="flex flex-wrap gap-2">

<?php if ($draft['journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/journals/detail', ['id' => $draft['journal_id']])) ?>"><?= pl_e(pl_t('Open posted journal')) ?></a><?php endif; ?>
<?php if ($draft['reversal_journal_id']): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/journals/detail', ['id' => $draft['reversal_journal_id']])) ?>"><?= pl_e(pl_t('Open linked reversal')) ?></a><?php endif; ?>
</div></div>

<details class="rounded-panel border border-border p-4 mx-5 mb-5"><summary><?= pl_e(pl_t('Journal history')) ?> <span class="muted">· <?= pl_e(pl_t('Latest 50 changes')) ?></span></summary><?php if (!$history): ?><p class="muted small"><?= pl_e(pl_t('No history is available.')) ?></p><?php endif; ?><ol><?php foreach ($history as $event): ?><li><strong><?= pl_e(ucfirst(str_replace('_', ' ', $event['action']))) ?></strong> · <?= pl_e($event['display_name']) ?><p><?= pl_e($event['reason']) ?></p><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $event['recorded_at']) . 'Z') ?>"><?= pl_e(pl_t('{time} UTC',['time'=>$event['recorded_at']])) ?></time></li><?php endforeach; ?></ol></details>
</section>
