<?php declare(strict_types=1); ?>
<div class="flex flex-col gap-3 py-5">
    <?php pl_ui_page_header(pl_t('Opening balances & cutover'), pl_t('Record the balances at the close of {date}. New transactions belong after this day.', ['date' => pl_date_label($company['start_date'])])); ?>
    <?php if ($form['message']): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
    <details class="rounded-panel border border-border bg-surface p-4"><summary class="text-sm font-semibold"><?= pl_e(pl_t('One balanced starting point')) ?></summary><p><?= pl_e(pl_t('Use a reviewed trial balance and the remaining amounts on unpaid invoices and bills. The unpaid-document register must match receivables and payables exactly. Confirmation posts the balances once; the register preserves supporting detail without posting those amounts a second time.')) ?></p><p class="small muted"><?= pl_e(pl_t('This records a cutover snapshot. Invoice collection, bill settlement, credit notes, tax, stock valuation and detailed historical journal imports need their own workflows. Mid-year cutovers must include reviewed year-to-date income and expense balances.')) ?></p></details>
    <?php if ($preview): $payload = $preview['payload']; ?>
    <section class="rounded-panel border border-border bg-surface p-4"><p class="eyebrow"><?= pl_e($reviewing ? pl_t('Review before posting') : pl_t('Saved source evidence')) ?></p><h2 class="section-title mb-2"><?= pl_e(pl_t('Cutover preview #{id}', ['id' => (int) $preview['id']])) ?></h2><p><?= pl_e($payload['source']) ?> · <?= pl_e(pl_date_label($payload['cutover_date'])) ?> · <?= pl_e($payload['currency']) ?></p>
        <div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Opening trial balance')) ?></caption><thead><tr><th><?= pl_e(pl_t('Account')) ?></th><th class="amount"><?= pl_e(pl_t('Debit')) ?></th><th class="amount"><?= pl_e(pl_t('Credit')) ?></th></tr></thead><tbody>
        <?php foreach ($payload['balances'] as $balance): ?><tr><td><?= pl_e($balance['account_code']) ?></td><td class="amount"><?= pl_e(pl_money($balance['debit'])) ?></td><td class="amount"><?= pl_e(pl_money($balance['credit'])) ?></td></tr><?php endforeach; ?>
        <?php if ($payload['balances'] === []): ?><tr><td colspan="3"><?= pl_e(pl_t('Explicit zero opening. No journal is needed.')) ?></td></tr><?php endif; ?>
        </tbody><tfoot><tr><th><?= pl_e(pl_t('Balanced totals')) ?></th><td class="amount"><?= pl_e(pl_money($payload['total_debit'])) ?></td><td class="amount"><?= pl_e(pl_money($payload['total_credit'])) ?></td></tr></tfoot></table></div>
        <h3 class="section-title my-3"><?= pl_e(pl_t('Unpaid documents ({count})', ['count' => count($payload['unpaid_documents'])])) ?></h3>
        <?php if ($payload['unpaid_documents']): ?><div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Unpaid document source register')) ?></caption><thead><tr><th><?= pl_e(pl_t('Kind / account')) ?></th><th><?= pl_e(pl_t('Customer or vendor')) ?></th><th><?= pl_e(pl_t('Reference')) ?></th><th><?= pl_e(pl_t('Document date')) ?></th><th><?= pl_e(pl_t('Due')) ?></th><th class="amount"><?= pl_e(pl_t('Remaining')) ?></th></tr></thead><tbody>
        <?php foreach ($payload['unpaid_documents'] as $document): ?><tr><td><?= pl_e(ucfirst($document['kind']) . ' / ' . $document['account_code']) ?></td><td><?= pl_e($document['party']) ?></td><td><?= pl_e($document['reference']) ?></td><td><?= pl_e($document['document_date']) ?></td><td><?= pl_e($document['due_date']) ?></td><td class="amount"><?= pl_e(pl_money($document['outstanding'])) ?></td></tr><?php endforeach; ?>
        </tbody></table></div><?php else: ?><p><?= pl_e(pl_t('No unpaid invoices or bills. Control balances are zero.')) ?></p><?php endif; ?>
        <?php if ($reviewing && $company['setup_status'] === 'opening_required' && pl_can_write($company)): ?>
        <form method="post" action="<?= pl_e(pl_url('/opening-balances')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="confirm"><input type="hidden" name="preview_id" value="<?= (int) $preview['id'] ?>"><input type="hidden" name="payload_hash" value="<?= pl_e($preview['payload_hash']) ?>">
            <label class="checkbox"><input type="checkbox" name="confirmed" value="1" required> <?= pl_e(pl_t('I checked the balanced totals against the source records and included all unpaid documents.')) ?></label><div class="panel-actions"><button class="btn btn-primary" type="submit"><?= pl_e(pl_t('Confirm opening balances')) ?></button><a class="btn btn-secondary" href="<?= pl_e(pl_url('/opening-balances')) ?>"><?= pl_e(pl_t('Prepare a different preview')) ?></a></div>
        </form><?php endif; ?>
    </section><?php endif; ?>
    <?php if (!$reviewing && $company['setup_status'] === 'opening_required' && pl_can_write($company)): ?>
    <form class="rounded-panel border border-border bg-surface p-4" method="post" enctype="multipart/form-data" action="<?= pl_e(pl_url('/opening-balances')) ?>">
        <?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="preview"><input type="hidden" name="request_key" value="<?= pl_e(bin2hex(random_bytes(24))) ?>">
        <h2 class="section-title mb-2"><?= pl_e(pl_t('Prepare the opening balances')) ?></h2><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><label class="field"><?= pl_e(pl_t('Cutover date')) ?><input type="date" name="cutover_date" value="<?= pl_e($company['start_date']) ?>" readonly required></label><label class="field"><?= pl_e(pl_t('Source records reference')) ?><input name="source" maxlength="200" value="<?= pl_e(pl_web_text($input, 'source')) ?>" placeholder="<?= pl_e(pl_t('Reviewed trial balance and unpaid list')) ?>" required></label></div>
        <p class="small muted"><?= pl_e(pl_t('Enter decimal points without separators, up to four decimal places. Leave zero balances blank.')) ?></p>
        <div class="table-wrap max-h-44 overflow-y-auto" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Enter account balances')) ?>"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Enter account balances')) ?></caption><thead><tr><th><?= pl_e(pl_t('Account')) ?></th><th class="amount"><?= pl_e(pl_t('Debit')) ?></th><th class="amount"><?= pl_e(pl_t('Credit')) ?></th></tr></thead><tbody>
        <?php foreach ($company['accounts'] as $account): if (!$account['is_active']) { continue; } ?><tr><th scope="row"><?= pl_e($account['code'] . ' · ' . $account['name']) ?></th><td><input class="opening-amount" aria-label="<?= pl_e(pl_t('{account} debit', ['account' => $account['name']])) ?>" name="debit_<?= (int) $account['id'] ?>" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'debit_' . $account['id'])) ?>"></td><td><input class="opening-amount" aria-label="<?= pl_e(pl_t('{account} credit', ['account' => $account['name']])) ?>" name="credit_<?= (int) $account['id'] ?>" inputmode="decimal" value="<?= pl_e(pl_web_text($input, 'credit_' . $account['id'])) ?>"></td></tr><?php endforeach; ?>
        </tbody></table></div>
        <details<?= pl_web_text($input, 'balances_csv') !== '' ? ' open' : '' ?>><summary><?= pl_e(pl_t('Import account balances from CSV instead')) ?></summary><p class="small muted"><?= pl_e(pl_t('A supplied CSV replaces the fields above. Header:')) ?> <code>account_code,debit,credit</code><?= pl_e(pl_t('. Use this book\'s exact account codes, up to 500 rows / 512 KiB.')) ?></p><label class="field"><?= pl_e(pl_t('Balance CSV file')) ?><input type="file" name="balances_csv_file" accept=".csv,text/csv"></label><label class="field"><?= pl_e(pl_t('Or paste balance CSV')) ?><textarea name="balances_csv" rows="5"><?= pl_e(pl_web_text($input, 'balances_csv')) ?></textarea></label></details>
        <details<?= pl_web_text($input, 'documents_csv') !== '' ? ' open' : '' ?>><summary><?= pl_e(pl_t('Bring unpaid invoices and bills')) ?></summary><p class="small muted"><?= pl_e(pl_t('Header:')) ?> <code>kind,account_code,party,reference,document_date,due_date,outstanding</code><?= pl_e(pl_t('. Use')) ?> <code>receivable</code> <?= pl_e(pl_t('or')) ?> <code>payable</code><?= pl_e(pl_t(', dates in YYYY-MM-DD, and each document\'s remaining unpaid amount. Amounts use this book\'s base currency.')) ?></p><label class="field"><?= pl_e(pl_t('Unpaid-document CSV file')) ?><input type="file" name="documents_csv_file" accept=".csv,text/csv"></label><label class="field"><?= pl_e(pl_t('Or paste unpaid-document CSV')) ?><textarea name="documents_csv" rows="6"><?= pl_e(pl_web_text($input, 'documents_csv')) ?></textarea></label></details>
        <label class="checkbox"><input type="checkbox" name="zero_confirmed" value="1"<?= pl_web_text($input, 'zero_confirmed') === '1' ? ' checked' : '' ?>> <?= pl_e(pl_t('If all balances are zero, I confirm there are no opening balances or unpaid documents.')) ?></label>
        <div class="panel-actions" data-fold="primary action"><button class="btn btn-primary" type="submit"><?= pl_e(pl_t('Preview and validate')) ?></button><p class="panel-actions-note"><?= pl_e(pl_t('A preview has no effect on the books. You will review the totals before confirmation.')) ?></p></div>
    </form>
    <?php elseif (!$reviewing && $history === []): ?><div class="rounded-panel border border-border bg-surface p-4"><p><?= pl_e($company['setup_status'] === 'opening_required' ? pl_t('An authorised owner can prepare and confirm these balances.') : pl_t('This business does not need an opening cutover.')) ?></p></div><?php endif; ?>
    <?php if ($history): ?><section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2"><?= pl_e(pl_t('Cutover history')) ?></h2><div class="table-wrap"><table class="table"><caption class="sr-only"><?= pl_e(pl_t('Confirmation and correction history')) ?></caption><thead><tr><th><?= pl_e(pl_t('Cutover')) ?></th><th><?= pl_e(pl_t('Status')) ?></th><th><?= pl_e(pl_t('Confirmed')) ?></th><th><?= pl_e(pl_t('Journal')) ?></th><th><?= pl_e(pl_t('Correction')) ?></th></tr></thead><tbody>
    <?php foreach ($history as $cutover): ?><tr><td>#<?= (int) $cutover['id'] ?> · <?= pl_e($cutover['cutover_date']) ?></td><td><?= pl_e(ucfirst($cutover['status'])) ?></td><td><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $cutover['confirmed_at']) . 'Z') ?>"><?= pl_e(pl_t('{when} UTC', ['when' => $cutover['confirmed_at']])) ?></time></td><td><?php if ($cutover['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $cutover['journal_id']])) ?>"><?= pl_e(pl_t('View journal')) ?></a><?php else: ?><?= pl_e(pl_t('Zero opening')) ?><?php endif; ?></td><td><?php if ($cutover['reversed_journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => $cutover['reversed_journal_id']])) ?>"><?= pl_e(pl_t('Linked reversal')) ?></a><?php endif; ?> <?= pl_e($cutover['reversal_reason'] ?? '') ?></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php if ($company['role'] === 'owner' && $history[0]['status'] === 'confirmed'): ?><details<?= pl_web_text($input, 'action') === 'reverse' ? ' open' : '' ?>><summary><?= pl_e(pl_t('Correct an opening cutover')) ?></summary><p><?= pl_e(pl_t('You can reverse and restart only before any transactions, drafts or bank statements exist, while the cutover period remains open. The original records and linked reversal remain in history.')) ?></p><form method="post" action="<?= pl_e(pl_url('/opening-balances')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="reverse"><input type="hidden" name="cutover_id" value="<?= (int) $history[0]['id'] ?>"><label class="field"><?= pl_e(pl_t('Correction reason')) ?><input name="reason" maxlength="400" value="<?= pl_e(pl_web_text($input, 'reason')) ?>" required></label><button class="btn btn-secondary" type="submit"><?= pl_e(pl_t('Reverse cutover and restart review')) ?></button></form></details><?php endif; ?>
    </section><?php endif; ?>
    <div class="panel-actions"><a class="btn btn-secondary" href="<?= pl_e(pl_url('/periods')) ?>"><?= pl_e(pl_t('Period administration')) ?></a><a class="btn btn-secondary" href="<?= pl_e(pl_url('/bank-reconciliation')) ?>"><?= pl_e(pl_t('Bank reconciliation')) ?></a></div>
</div>
