<?php declare(strict_types=1); ?>
<section class="flex flex-col gap-4 py-5" aria-labelledby="payroll-title">
<div class="page-header"><div><p class="eyebrow"><?= pl_e(pl_t('Accounting')) ?></p><h1 class="page-title" id="payroll-title"><?= pl_e(pl_t('Payroll accounting')) ?></h1><p class="muted"><?= pl_e(pl_t('Record reviewed totals for a pay period, then settle each payable through an ordinary journal. No individual pay, payslips or statutory calculations are stored here.')) ?></p></div></div>
<?php if ($form['message']!==''): ?><div class="alert alert-danger" role="alert"><?= pl_e($form['message']) ?></div><?php endif; ?>
<form method="get" class="flex flex-wrap gap-3" action="<?= pl_e(pl_url('/payroll')) ?>"><label class="field"><?= pl_e(pl_t('Pay period from')) ?><input class="input" type="date" name="from" value="<?= pl_e($from) ?>" required></label><label class="field"><?= pl_e(pl_t('To')) ?><input class="input" type="date" name="to" value="<?= pl_e($to) ?>" required></label><button class="btn btn-secondary"><?= pl_e(pl_t('Filter')) ?></button></form>
<div class="table-wrap" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Payroll journals')) ?>"><table class="table"><thead><tr><th><?= pl_e(pl_t('Reference')) ?></th><th><?= pl_e(pl_t('Pay period')) ?></th><th><?= pl_e(pl_t('Posting date')) ?></th><th><?= pl_e(pl_t('Status')) ?></th></tr></thead><tbody>
<?php foreach ($rows as $row): ?><tr><td><a href="<?= pl_e(pl_url('/payroll',['id'=>$row['id'],'from'=>$from,'to'=>$to])) ?>"><?= pl_e($row['external_reference']) ?></a></td><td><?= pl_e($row['period_from'].' — '.$row['period_to']) ?></td><td><?= pl_e($row['posting_date']) ?></td><td><?= pl_e(pl_t($row['reversal_id']===null?'Posted':'Reversed')) ?></td></tr><?php endforeach; ?>
<?php if ($rows===[]): ?><tr><td colspan="4"><?= pl_e(pl_t('No payroll journals in this pay period range.')) ?></td></tr><?php endif; ?></tbody></table></div>
<?php if ($selected): ?>
<div class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title"><?= pl_e($selected['external_reference']) ?></h2><p><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$selected['journal_id']])) ?>"><?= pl_e(pl_t('Open posted journal')) ?></a></p><div class="table-wrap" tabindex="0"><table class="table"><thead><tr><th><?= pl_e(pl_t('Element')) ?></th><th><?= pl_e(pl_t('Account')) ?></th><th><?= pl_e(pl_t('Accrued')) ?></th><th><?= pl_e(pl_t('Paid')) ?></th><th><?= pl_e(pl_t('Outstanding')) ?></th></tr></thead><tbody>
<?php foreach ($selected['elements'] as $e): ?><tr><td><?= pl_e(pl_t($kinds[$e['element_kind']]['label'])) ?></td><td><?= pl_e($e['account_code'].' '.$e['account_name']) ?></td><td><?= pl_e($e['amount']) ?></td><td><?= $e['settleable']?pl_e($e['paid']):'—' ?></td><td><?= $e['settleable']?pl_e($e['remaining']):'—' ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php foreach ($payments as $payment): ?><p><a href="<?= pl_e(pl_url('/general-journals/detail',['id'=>$payment['draft_id']])) ?>"><?= pl_e(pl_t('Payment journal #{id}', ['id'=>$payment['draft_id']])) ?></a> — <?= pl_e($payment['document_date']) ?> — <?= pl_e(pl_t($payment['journal_id']===null?'Draft':($payment['reversal_id']===null?'Posted':'Reversed'))) ?></p><?php endforeach; ?>
<?php if ($mayManage && $selected['reversal_id']===null): ?>
<form method="post" class="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3" action="<?= pl_e(pl_url('/payroll')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="pay"><input type="hidden" name="payroll_id" value="<?= (int)$selected['id'] ?>"><input type="hidden" name="request_key" value="<?= pl_e(bin2hex(random_bytes(16))) ?>">
<h3 class="section-title sm:col-span-2"><?= pl_e(pl_t('Prepare a payment')) ?></h3><label class="field"><?= pl_e(pl_t('Payment date')) ?><input class="input" type="date" name="date" value="<?= pl_e(gmdate('Y-m-d')) ?>" required></label><label class="field"><?= pl_e(pl_t('Cash or bank')) ?><select class="select" name="bank_account_id" required><option value=""><?= pl_e(pl_t('Choose account')) ?></option><?php foreach ($accounts as $a): if($a['role']!=='cash_bank'){continue;} ?><option value="<?= (int)$a['id'] ?>"><?= pl_e($a['name']) ?></option><?php endforeach; ?></select></label>
<?php foreach ($selected['elements'] as $e): if(!$e['settleable'] || bccomp($e['remaining'],'0',4)<=0){continue;} ?><label class="field"><?= pl_e(pl_t($kinds[$e['element_kind']]['label'])) ?><input class="input" inputmode="decimal" name="allocations[<?= (int)$e['id'] ?>]" placeholder="<?= pl_e($e['remaining']) ?>"><span class="field-hint"><?= pl_e(pl_t('Leave blank to pay this element later.')) ?></span></label><?php endforeach; ?>
<button class="btn btn-primary sm:col-span-2"><?= pl_e(pl_t('Create journal for review')) ?></button></form>
<details class="mt-3"><summary><?= pl_e(pl_t('Reverse this accrual')) ?></summary><form method="post" class="grid gap-3 mt-3" action="<?= pl_e(pl_url('/payroll')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="reverse"><input type="hidden" name="payroll_id" value="<?= (int)$selected['id'] ?>"><input type="hidden" name="request_key" value="<?= pl_e(bin2hex(random_bytes(16))) ?>"><label class="field"><?= pl_e(pl_t('Reversal date')) ?><input class="input" type="date" name="date" value="<?= pl_e(gmdate('Y-m-d')) ?>" required></label><label class="field"><?= pl_e(pl_t('Reason')) ?><input class="input" name="reason" required maxlength="400"></label><p class="muted"><?= pl_e(pl_t('Reverse posted payments first. A corrected payroll needs a new external reference.')) ?></p><button class="btn btn-secondary"><?= pl_e(pl_t('Record linked reversal')) ?></button></form></details>
<?php endif; ?></div><?php endif; ?>
<?php if ($mayManage): ?>
<div class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title"><?= pl_e(pl_t($preview?'Review payroll totals':'New payroll journal')) ?></h2>
<?php if (!$preview): ?><form method="post" action="<?= pl_e(pl_url('/payroll')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="provision"><button class="btn btn-secondary"><?= pl_e(pl_t('Set up missing payroll accounts')) ?></button></form><?php endif; ?>
<form method="post" class="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3" action="<?= pl_e(pl_url('/payroll')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="action" value="<?= $preview?'post':'preview' ?>"><input type="hidden" name="request_key" value="<?= pl_e(pl_web_text($input,'request_key',bin2hex(random_bytes(16)))) ?>">
<?php foreach (['period_from'=>'Pay period start','period_to'=>'Pay period end','date'=>'Posting date'] as $field=>$label): ?><label class="field"><?= pl_e(pl_t($label)) ?><input class="input" type="date" name="<?= pl_e($field) ?>" value="<?= pl_e(pl_web_text($input,$field)) ?>" required <?= $preview?'readonly':'' ?>></label><?php endforeach; ?>
<label class="field"><?= pl_e(pl_t('External reference')) ?><input class="input" name="external_reference" value="<?= pl_e(pl_web_text($input,'external_reference')) ?>" maxlength="120" required <?= $preview?'readonly':'' ?>></label><label class="field sm:col-span-2"><?= pl_e(pl_t('Description')) ?><input class="input" name="description" value="<?= pl_e(pl_web_text($input,'description')) ?>" maxlength="500" required <?= $preview?'readonly':'' ?>></label>
<p class="muted sm:col-span-2"><?= pl_e(pl_t('Enter aggregate totals only. Positive expenses debit; net pay, deductions and staff-advance recovery credit. The totals must balance.')) ?></p>
<?php $elements=$input['elements']??[]; $count=$preview?count($elements):max(9,count($elements)); for($i=0;$i<$count;$i++): $e=is_array($elements[$i]??null)?$elements[$i]:[]; ?>
<div class="grid grid-cols-1 md:grid-cols-3 gap-2 sm:col-span-2"><label class="field"><?= pl_e(pl_t('Element {n}',['n'=>$i+1])) ?><select class="select" name="elements[<?= $i ?>][kind]"><?php foreach ($kinds as $key=>$definition): ?><option value="<?= pl_e($key) ?>" <?= ($e['kind']??'')===$key?'selected':'' ?>><?= pl_e(pl_t($definition['label'])) ?></option><?php endforeach; ?></select></label><label class="field"><?= pl_e(pl_t('Account')) ?><select class="select" name="elements[<?= $i ?>][account_id]"><option value=""><?= pl_e(pl_t('Choose account')) ?></option><?php foreach ($accounts as $a): ?><option value="<?= (int)$a['id'] ?>" <?= (int)($e['account_id']??0)===(int)$a['id']?'selected':'' ?>><?= pl_e($a['code'].' '.$a['name']) ?></option><?php endforeach; ?></select></label><label class="field"><?= pl_e(pl_t('Amount')) ?><input class="input" inputmode="decimal" name="elements[<?= $i ?>][amount]" value="<?= pl_e((string)($e['amount']??'')) ?>" <?= $preview?'readonly':'' ?>></label></div><?php endfor; ?>
<?php if ($preview): ?><p class="sm:col-span-2"><?= pl_e(pl_t('Balanced totals: {amount} {currency}',['amount'=>$preview['totals']['debit'],'currency'=>$preview['currency']])) ?></p><input type="hidden" name="preview_hash" value="<?= pl_e(hash('sha256',json_encode($preview,JSON_THROW_ON_ERROR))) ?>"><label class="sm:col-span-2"><input type="checkbox" name="confirmed" value="yes" required> <?= pl_e(pl_t('I reviewed these aggregate payroll totals and confirm posting.')) ?></label><?php endif; ?><button class="btn btn-primary sm:col-span-2"><?= pl_e(pl_t($preview?'Post payroll journal':'Review payroll totals')) ?></button></form></div><?php endif; ?>
</section>
