<?php declare(strict_types=1);
foreach (($pack['code_aliases'] ?? []) as $old => $code) { if (isset($accountIds[$code])) { $accountIds[$old] = $accountIds[$code]; } }
?>
<?php if (($pack['kind'] ?? '') === 'starter_playground'): ?>
<section class="flex flex-col gap-3 py-5 sample-guide">
    <?php pl_ui_page_header(pl_t('Accounting starter playground'), pl_t('Try a purchase, an invoice and partial payments. Follow the same figures through stock, outstanding balances and the general ledger.'), static function (): void { ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/purchasing', ['new' => '1'])) ?>"><?= pl_e(pl_t('Create a purchase order')) ?> <?= pl_icon('arrow-right') ?></a><?php }); ?>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 rounded-panel border border-border bg-surface p-4"><div><strong><?= pl_e(pl_t('{year} · Open practice year', ['year' => substr($pack['start_date'], 0, 4)])) ?></strong><p><?= pl_e(pl_t('Your sample began with zero balances, no unpaid documents and no stock. Use a date in this year for practice entries.')) ?></p></div><div><strong><?= pl_e(pl_t('Ready to enter your own examples')) ?></strong><p><?= pl_e(pl_t('Sample customer and supplier has both roles. Sample goods uses one stock location; Sample service needs no stock. Receivables, payables, purchasing and inventory are ready.')) ?></p></div></div>
    <p class="alert alert-info text-xs"><?= pl_e(pl_t('All names and amounts are fictional. {notice} Do not enter real customer or financial data.', ['notice' => $pack['notice']])) ?></p>
    <?php if (isset($pack['scenario']) && is_array($pack['scenario'])): ?><section class="rounded-panel border border-border bg-surface p-4" aria-labelledby="scenario-title"><p class="eyebrow"><?= pl_e(pl_t('Industry teaching scenario · {status}', ['status' => $pack['status'] === 'preview_only' ? pl_t('Preview only') : pl_t('Bookkeeping example')])) ?></p><h2 id="scenario-title"><?= pl_e($pack['scenario']['title'] ?? pl_t('Bookkeeping review')) ?></h2><p><?= pl_e($pack['scenario']['goal'] ?? '') ?></p><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><h3><?= pl_e(pl_t('Suggested path')) ?></h3><ol><?php foreach (($pack['scenario']['steps'] ?? []) as $step): ?><li><?= pl_e($step) ?></li><?php endforeach; ?></ol></div><div><h3><?= pl_e(pl_t('Review boundaries')) ?></h3><ul><?php foreach (($pack['scenario']['checks'] ?? []) as $check): ?><li><?= pl_e($check) ?></li><?php endforeach; ?></ul></div></div></section><?php endif; ?>

    <div class="flex flex-col gap-3">
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise" open><summary class="section-title"><?= pl_e(pl_t('1 · Buy and receive · Start with five items')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('Create an order for')) ?> <strong><?= pl_e(pl_t('5 Sample goods at 10.00 each')) ?></strong><?= pl_e(pl_t('. Confirm it, then receive the five items using')) ?> <strong><?= pl_e(pl_t('2100 · Goods received awaiting bills')) ?></strong><?= pl_e(pl_t('. Stock is now worth 50.00.')) ?></p><p><?= pl_e(pl_t('From the receipt, preview and post the supplier bill for the same quantity and net price. Choose tax-exclusive prices and')) ?> <strong><?= pl_e(pl_t('DEMO5')) ?></strong> <?= pl_e(pl_t('for an illustrative 2.50 tax and a 52.50 payable.')) ?></p><p><a href="<?= pl_e(pl_url('/purchasing', ['new' => '1'])) ?>"><?= pl_e(pl_t('Open purchasing')) ?></a> · <a href="<?= pl_e(pl_url('/inventory')) ?>"><?= pl_e(pl_t('Check stock and its ledger balance')) ?></a></p></div></details>
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise"><summary class="section-title"><?= pl_e(pl_t('2 · Invoice and collect · Sell two items')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('Invoice')) ?> <strong><?= pl_e(pl_t('2 Sample goods at 25.00 each')) ?></strong><?= pl_e(pl_t(', using tax-exclusive prices and DEMO5. Posting records a 52.50 receivable and the cost of the goods sold. Record a partial receipt of 25.00, then the remaining 27.50.')) ?></p><p><?= pl_e(pl_t('For a simpler first invoice, use')) ?> <strong><?= pl_e(pl_t('Sample service')) ?></strong><?= pl_e(pl_t('; it needs no purchase or stock receipt. Posted documents offer linked credit notes and traceable corrections.')) ?></p><p><a href="<?= pl_e(pl_url('/ar', ['new' => '1'])) ?>"><?= pl_e(pl_t('Create an invoice')) ?></a> · <a href="<?= pl_e(pl_url('/ar')) ?>"><?= pl_e(pl_t('Review receivables and ageing')) ?></a></p></div></details>
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise"><summary class="section-title"><?= pl_e(pl_t('3 · Pay and reconcile · Follow what remains')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('Open the posted supplier bill and pay 20.00 through')) ?> <strong><?= pl_e(pl_t('1000 · Cash and bank')) ?></strong><?= pl_e(pl_t('. Review the remaining 32.50 payable. After the two-item sale, three goods remain with a 30.00 carrying value.')) ?></p><p><?= pl_e(pl_t('Compare the open-item and stock totals with their ledger accounts. Keep dates and the selected {currency} currency consistent. Bank-file imports remain disabled in the public demo.', ['currency' => $company['currency']])) ?></p><p><a href="<?= pl_e(pl_url('/ap')) ?>"><?= pl_e(pl_t('Open payables')) ?></a> · <a href="<?= pl_e(pl_url('/reports/trial-balance')) ?>"><?= pl_e(pl_t('Read the Trial Balance')) ?></a></p></div></details>
    </div>
    <section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2"><?= pl_e(pl_t('Your prepared chart and controls')) ?></h2><p><?= pl_e(pl_t('1-110-10001-00 is receivables; 2-100-10001-00 is payables; 1-130-21300-00 is stock; 2-100-22100-00 is received goods awaiting bills; 5-200-25100-00 is cost of goods sold. The separate sample input/output tax accounts use the manually configured DEMO5 rate. 5-100-25200-00 is available when a reviewed purchase variance or currency rounding adjustment is needed.')) ?></p><p><?= pl_e(pl_t('Account, product, tax, module and user administration are locked in the public demo. The prepared examples let you try financial workflows without changing those controls.')) ?></p></section>
    <p class="small muted"><?= pl_e(pl_t('This playground has no historical balances. The eleven historical sample companies remain separate choices. Each visitor receives separate books and access ends at the next hourly reset. The default capacity is 100 source and operation records; linked actions can use several records. Leave the demo and start again to choose a different sample.')) ?></p>
</section>
<?php return; endif; ?>
<section class="flex flex-col gap-3 py-5 sample-guide">
    <p class="eyebrow"><?= pl_e(pl_t('{business} · Your private practice books', ['business' => $pack['business']])) ?></p>
    <?php pl_ui_page_header((string) $pack['name'], pl_t('Two years of history. A new year to practise. Follow a figure to its source, then try an editable draft.'), static function (): void { ?><a class="btn btn-primary" href="<?= pl_e(pl_url('/transactions', ['status' => 'draft'])) ?>"><?= pl_e(pl_t('Open the three practice drafts')) ?> <?= pl_icon('arrow-right') ?></a><?php }); ?>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 rounded-panel border border-border bg-surface p-4"><div><strong><?= pl_e(pl_t('2024–2025 · Historical periods closed')) ?></strong><p><?= pl_e(pl_t('The original history is reconciled month by month. Closed periods reject new postings. The 2024 annual period and twelve 2025 monthly periods do not overlap.')) ?></p></div><div><strong><?= pl_e(pl_t('2026 · Open practice year')) ?></strong><p><?= pl_e(pl_t('January is posted; February has three editable drafts. Choose a date in 2026 for your own entries. The original pack has more than eighty source records, and each sample leaves room for at least 100 records of your own before the hourly refresh.')) ?></p></div></div>
    <p class="alert alert-info text-xs"><?= pl_e(pl_t('All names and amounts are fictional. {notice}', ['notice' => $pack['notice']])) ?></p>
    <?php if (is_array($pack['learning_story'] ?? null)): $story = $pack['learning_story']; ?>
    <section class="rounded-panel border border-border bg-surface p-4" aria-labelledby="company-story-title">
        <img src="<?= pl_e(pl_url($story['logo']['path'])) ?>" width="72" height="72" alt="<?= pl_e($pack['name'] . ' fictional company logo') ?>">
        <h2 id="company-story-title"><?= pl_e(pl_t('Meet the people behind these sample books')) ?></h2>
        <p><?= pl_e($story['origin']) ?></p>
        <ul><?php foreach ($story['characters'] as $person): ?><li><strong><?= pl_e($person['name']) ?></strong> · <?= pl_e($person['role']) ?></li><?php endforeach; ?></ul>
        <p class="small muted"><?= pl_e($story['notice']) ?></p>
        <?php if ($story['status'] === 'profile_only'): ?><p><?= pl_e($story['journey_note']) ?></p><?php endif; ?>
        <?php foreach ($story['chapters'] as $chapter): ?>
        <details class="rounded-panel border border-border p-3 mt-3" id="story-<?= pl_e($chapter['id']) ?>">
            <summary><?= pl_e($chapter['title']) ?> · <?= pl_e($chapter['period'] === 'history' ? pl_t('Recorded history') : pl_t('Practice')) ?></summary>
            <p><?= pl_e($chapter['happened']) ?></p>
            <p><strong><?= pl_e(pl_t('The decision')) ?>:</strong> <?= pl_e($chapter['decision']) ?></p>
            <p><strong><?= pl_e(pl_t('Accounting treatment')) ?>:</strong> <?= pl_e($chapter['accounting']) ?></p>
            <p><?= pl_e($chapter['inspect']) ?></p>
            <ul><?php foreach ($chapter['events'] as $event): ?><li>
                <?php if (isset($pack['story_sources'][$event['key']])): ?><a href="<?= pl_e(pl_url('/journals/detail', ['id' => (int) $pack['story_sources'][$event['key']]])) ?>"><?= pl_e($event['date'] . ' · ' . $event['description']) ?></a><?php else: ?><?= pl_e($event['description']) ?> — <?= pl_e(pl_t('Start a current sample to follow this source.')) ?><?php endif; ?>
                <?php if (isset($event['amount'])): ?> · <?= pl_e(pl_money($event['amount'])) ?> <?= pl_e($company['currency']) ?><?php endif; ?>
            </li><?php endforeach; ?></ul>
            <p><a href="<?= pl_e(pl_url('/reports/profit-loss', $chapter['reports'])) ?>"><?= pl_e(pl_t('Profit and loss for this chapter')) ?></a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => $chapter['reports']['to']])) ?>"><?= pl_e(pl_t('Closing trial balance')) ?></a></p>
        </details>
        <?php endforeach; ?>
    </section>
    <?php endif; ?>


    <div class="flex flex-col gap-3">
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise" open><summary class="section-title"><?= pl_e(pl_t('1 · Daily checks · Where did the money go?')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('On')) ?> <strong><?= pl_e(pl_t('15 January 2026')) ?></strong><?= pl_e(pl_t(', the bank receipt summary records')) ?> <strong><?= pl_e(pl_money($pack['monthly_support'][24]['bank_receipts'])) ?> <?= pl_e($company['currency']) ?></strong><?= pl_e(pl_t('. Open its source, then inspect the primary bank\'s movements for that day.')) ?></p><ul><li><a href="<?= pl_e(pl_url('/transactions/detail', ['id' => $sourceIds['receipt']])) ?>"><?= pl_e(pl_t('Read the January receipt')) ?></a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1000'], 'from' => '2026-01-15', 'as_of' => '2026-01-15'])) ?>"><?= pl_e(pl_t('Check that day\'s bank movements')) ?></a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['1030'], 'from' => '2026-01-01', 'as_of' => '2026-02-28'])) ?>"><?= pl_e(pl_t('Compare petty cash before and after a draft')) ?></a></li></ul><p class="small muted"><?= pl_e(pl_t('The receipt is an illustrative monthly summary dated on the 15th. Cash sales appear separately in the month-end support journal. Neither is an imported bank statement.')) ?></p></div></details>
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise"><summary class="section-title"><?= pl_e(pl_t('2 · Monthly closing · Check December\'s adjustments')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('Read')) ?> <strong><?= pl_e(pl_t('December 2025')) ?></strong> <?= pl_e(pl_t('on its own. Inspect salaries, insurance released from prepayments, depreciation, and the')) ?> <strong>550.00</strong> <?= pl_e(pl_t('maintenance bill still unpaid at year end.')) ?></p><ul><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-12-01', 'to' => '2025-12-31'])) ?>"><?= pl_e(pl_t('December profit and loss')) ?></a></li><li><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['operations']])) ?>"><?= pl_e(pl_t('Open December\'s support journal')) ?></a></li><li><a href="<?= pl_e(pl_url('/reports/account', ['id' => $accountIds['2000'], 'from' => '2025-12-01', 'as_of' => '2026-01-31'])) ?>"><?= pl_e(pl_t('Follow the bill into January\'s payment')) ?></a></li></ul><p class="small muted"><?= pl_e(pl_t('Closing a period prevents backdated posting. It does not certify statements or move profit into retained earnings. The Balance Sheet shows accumulated unclosed earnings once.')) ?></p></div></details>
        <details class="rounded-panel border border-border bg-surface p-4 sample-exercise"><summary class="section-title"><?= pl_e(pl_t('3 · Quarterly and annual review · Compare separate periods')) ?></summary><div class="mt-3"><p><?= pl_e(pl_t('Compare each quarter of')) ?> <strong>2025</strong><?= pl_e(pl_t(', then the two complete years. Quarter results add to the year\'s result. Use the same company and currency throughout.')) ?></p><ul><li><?php foreach ([['01-01','03-31','Q1'],['04-01','06-30','Q2'],['07-01','09-30','Q3'],['10-01','12-31','Q4']] as [$fromDate, $toDate, $label]): ?><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-' . $fromDate, 'to' => '2025-' . $toDate])) ?>"><?= pl_e($label) ?></a> <?php endforeach; ?></li><li><a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2024-01-01', 'to' => '2024-12-31'])) ?>"><?= pl_e(pl_t('2024 profit and loss')) ?></a> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => '2025-01-01', 'to' => '2025-12-31'])) ?>"><?= pl_e(pl_t('2025 profit and loss')) ?></a></li><li><a href="<?= pl_e(pl_url('/reports/balance-sheet', ['as_of' => '2025-12-31'])) ?>"><?= pl_e(pl_t('2025 Balance Sheet')) ?></a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => '2025-12-31'])) ?>"><?= pl_e(pl_t('2025 Trial Balance')) ?></a></li></ul><p class="small muted"><?= pl_e(pl_t('Year-end loans have 3,600.00 principal outstanding. After the display-counter disposal, equipment cost is 1,800.00 and accumulated depreciation is 690.00. Amounts use your chosen base currency; no foreign-exchange conversion occurs.')) ?></p></div></details>
    </div>

    <?php
    $sourceMaterial = is_array($pack['source_material'] ?? null) ? $pack['source_material'] : [];
    $researchEvidence = is_array($sourceMaterial['research_evidence'] ?? null) ? $sourceMaterial['research_evidence'] : null;
    $profile = is_array($researchEvidence['business_profile'] ?? null) ? $researchEvidence['business_profile'] : [];
    $verticalProfile = is_array($researchEvidence['industry_profile'] ?? null) ? $researchEvidence['industry_profile'] : [];
    $futureScenarios = is_array($researchEvidence['industry_scenarios'] ?? null) ? $researchEvidence['industry_scenarios'] : [];
    ?>
    <?php if (($pack['validation_issues'] ?? []) !== []): ?>
    <aside class="alert" aria-label="<?= pl_e(pl_t('Unposted sample evidence')) ?>"><h2><?= pl_e(pl_t('Some practice events remain unposted')) ?></h2>
        <?php foreach ($pack['validation_issues'] as $issue): ?><p><?= pl_e($issue['date']) ?> · <?= pl_e($issue['event_id']) ?>: <?php if (isset($issue['available'], $issue['required'])): ?><?= pl_e(pl_t('The scenario records {available} in the payment account but proposes an outflow of {required}.', ['available'=>pl_money($issue['available']), 'required'=>pl_money($issue['required'])])) ?><?php endif; ?> <?= pl_e($issue['reason']) ?></p><?php endforeach; ?>
    </aside>
    <?php endif; ?>
    <section class="rounded-panel border border-border bg-surface p-4" aria-labelledby="sample-evidence-title">
        <p class="eyebrow"><?= pl_e(pl_t('Pinned sample evidence')) ?></p>
        <h2 id="sample-evidence-title"><?= pl_e(pl_t('What this business example contains')) ?></h2>
        <?php if ($researchEvidence !== null): ?>
            <p><?= pl_e(pl_t('{description} The operational contract is shown as source evidence; it is not silently posted as an unsupported industry module.', ['description' => $profile['description'] ?? pl_t('This profile is sample teaching material.')])) ?></p>
            <dl class="sample-evidence-grid">
                <div><dt><?= pl_e(pl_t('Source pack')) ?></dt><dd><?= pl_e((string) ($researchEvidence['source_pack_id'] ?? $pack['id'])) ?> · <?= pl_e((string) ($researchEvidence['source_pack_version'] ?? '1.0.0')) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Source status')) ?></dt><dd><?= pl_e((string) ($researchEvidence['review_status'] ?? pl_t('not recorded'))) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Vertical profile')) ?></dt><dd><?= pl_e((string) ($verticalProfile['name'] ?? pl_t('Neutral bookkeeping'))) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Account vocabulary')) ?></dt><dd><?= pl_e(pl_t('{count} profile accounts', ['count' => count(is_array($verticalProfile['accounts'] ?? null) ? $verticalProfile['accounts'] : [])])) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Contacts')) ?></dt><dd><?= count(is_array($researchEvidence['contacts'] ?? null) ? $researchEvidence['contacts'] : []) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Products or services')) ?></dt><dd><?= count(is_array($researchEvidence['products'] ?? null) ? $researchEvidence['products'] : []) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Locations')) ?></dt><dd><?= count(is_array($researchEvidence['locations'] ?? null) ? $researchEvidence['locations'] : []) ?></dd></div>
                <div><dt><?= pl_e(pl_t('Operational events')) ?></dt><dd><?= count(is_array($researchEvidence['operational_event_contract'] ?? null) ? $researchEvidence['operational_event_contract'] : []) ?></dd></div>
            </dl>
            <?php if ($verticalProfile !== [] && is_array($verticalProfile['distinct_controls'] ?? null)): ?><details><summary><?= pl_e(pl_t('Vertical controls represented by the profile')) ?></summary><ul><?php foreach ($verticalProfile['distinct_controls'] as $control): ?><li><?= pl_e((string) $control) ?></li><?php endforeach; ?></ul></details><?php endif; ?>
            <?php if ($futureScenarios !== []): ?><details><summary><?= pl_e(pl_t('Future or unsupported scenarios retained as evidence')) ?></summary><ul><?php foreach ($futureScenarios as $scenario): ?><li><strong><?= pl_e((string) ($scenario['id'] ?? pl_t('scenario'))) ?></strong> · <?= pl_e((string) ($scenario['status'] ?? pl_t('future'))) ?><?php if (isset($scenario['description'])): ?> — <?= pl_e((string) $scenario['description']) ?><?php endif; ?></li><?php endforeach; ?></ul></details><?php endif; ?>
        <?php else: ?>
            <p class="alert"><?= pl_e(pl_t('This successor pack has no authored operational source pack yet. The generic ledger history is still sample and reconciled, but specialist business research remains a release blocker.')) ?></p>
        <?php endif; ?>
    </section>

    <section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2"><?= pl_e(pl_t('Manual support schedules')) ?></h2><p><?= pl_e(pl_t('These authored schedules explain the general-ledger entries. They are examples to read, not operational payroll, customer/vendor subledgers or a stock module.')) ?></p>
        <dl class="sample-schedules"><div><dt><?= pl_e(pl_t('Staff and cash')) ?></dt><dd><?= pl_e(pl_t('Mira Vale: 600.00 per month; Noel Reed: 900.00. The 420.00 December 2024 bonus is paid in January 2025. Rent uses the reserve bank; utilities use 90.00 from the primary bank and 10.00 petty cash each posted month. No deductions or payroll tax are calculated.')) ?></dd></div><div><dt><?= pl_e(pl_t('Assets, prepayments and loan')) ?></dt><dd><?= pl_e(pl_t('Equipment: cost 2,400.00, illustrative 60-month life, zero residual, 40.00 monthly from February 2024. Insurance is prepaid 1,200.00 each January and released at 100.00 per posted month. A 6,000.00 loan starts in March 2024; each December payment has 1,200.00 principal and an illustrative 300.00 interest component.')) ?></dd></div><div><dt><?= pl_e(pl_t('Cross-year items')) ?></dt><dd><?= pl_e(pl_t('Alder Customer owes 800.00 on 31 December 2024 and pays in February 2025. Harbor maintenance is owed 550.00 on 31 December 2025 and paid in January 2026. The later settlements do not record the income or expense again.')) ?></dd></div><div><dt><?= pl_e(pl_t('Corrections')) ?></dt><dd><a href="<?= pl_e(pl_url('/general-journals/detail', ['id' => $sourceIds['correction']])) ?>"><?= pl_e(pl_t('The 25.00 mistaken cost')) ?></a> <?= pl_e(pl_t('is reversed in full on 20 August 2025. The separately referenced replacement records 45.00 on the following day. All three journal entries remain visible.')) ?></dd></div></dl>
        <?php if (isset($accountIds['1400'])): ?><p><strong><?= pl_e(pl_t('Manual stock example:')) ?></strong> <?= pl_e(pl_t('Each posted month records {unitsIn} units purchased and {unitsOut} units sold at an illustrative {unitCost} per unit. The stock account at December 2025 reconciles to the accumulated unsold units. POS practice does not deduct this stock or calculate cost of sales.', ['unitsIn' => (int) $pack['monthly_support'][0]['units_in'], 'unitsOut' => (int) $pack['monthly_support'][0]['units_out'], 'unitCost' => pl_money($pack['monthly_support'][0]['unit_cost'])])) ?></p><?php endif; ?>
        <details><summary><?= pl_e(pl_t('Read the 25 posted monthly support rows')) ?></summary><div class="table-wrap max-h-80 overflow-auto" role="region" aria-label="<?= pl_e(pl_t('Manual monthly support')) ?>" tabindex="0"><table class="table"><caption><?= pl_e(pl_t('Original fixture support · {currency} · exact source values have four decimal places', ['currency' => $company['currency']])) ?></caption><thead><tr><th scope="col"><?= pl_e(pl_t('Month')) ?></th><th scope="col"><?= pl_e(pl_t('Gross receipts')) ?></th><th scope="col"><?= pl_e(pl_t('Salaries')) ?></th><th scope="col"><?= pl_e(pl_t('Insurance')) ?></th><th scope="col"><?= pl_e(pl_t('Depreciation')) ?></th><th scope="col"><?= pl_e(pl_t('Stock bought')) ?></th><th scope="col"><?= pl_e(pl_t('Cost of sales')) ?></th></tr></thead><tbody><?php foreach ($pack['monthly_support'] as $row): ?><tr><th scope="row"><?= pl_e($row['month']) ?></th><?php foreach (['gross_receipts','salaries','insurance_release','depreciation','stock_purchases','cost_of_sales'] as $key): ?><td><?= pl_e(pl_money($row[$key])) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></details>
    </section>
    <section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2"><?= pl_e(pl_t('Check any original month')) ?></h2><p><?= pl_e(pl_t('Choose an original checkpoint to open its P&L and month-end Trial Balance. February–December 2026 start with no posted activity; your practice entries can change those reports.')) ?></p><div class="sample-months"><?php foreach ([2024,2025,2026] as $year): ?><details><summary><?= pl_e(pl_t('{year} monthly reports', ['year' => $year])) ?></summary><ul><?php foreach ($pack['checkpoints'] as $point): ?><?php if (str_starts_with($point['from'], (string) $year)): ?><li><?= pl_e(substr($point['from'], 0, 7)) ?> · <a href="<?= pl_e(pl_url('/reports/profit-loss', ['from' => $point['from'], 'to' => $point['to']])) ?>"><?= pl_e(pl_t('P&L')) ?></a> · <a href="<?= pl_e(pl_url('/reports/trial-balance', ['as_of' => $point['to']])) ?>"><?= pl_e(pl_t('Trial Balance')) ?></a> · <?= pl_e(pl_t('original profit {profit}', ['profit' => pl_money($point['profit'])])) ?></li><?php endif; ?><?php endforeach; ?></ul></details><?php endforeach; ?></div></section>
    <?php if (isset($pack['scenario']) && is_array($pack['scenario'])): ?><section class="rounded-panel border border-border bg-surface p-4" aria-labelledby="scenario-title"><p class="eyebrow"><?= pl_e(pl_t('Industry teaching scenario · {status}', ['status' => $pack['status'] === 'preview_only' ? pl_t('Preview only') : pl_t('Bookkeeping example')])) ?></p><h2 id="scenario-title"><?= pl_e($pack['scenario']['title'] ?? pl_t('Bookkeeping review')) ?></h2><p><?= pl_e($pack['scenario']['goal'] ?? '') ?></p><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><h3><?= pl_e(pl_t('Suggested path')) ?></h3><ol><?php foreach (($pack['scenario']['steps'] ?? []) as $step): ?><li><?= pl_e($step) ?></li><?php endforeach; ?></ol></div><div><h3><?= pl_e(pl_t('Review boundaries')) ?></h3><ul><?php foreach (($pack['scenario']['checks'] ?? []) as $check): ?><li><?= pl_e($check) ?></li><?php endforeach; ?></ul></div></div></section><?php endif; ?>
    <p class="small muted"><?= pl_e(pl_t('Original pack {id} · version {version} · 36 month-end checkpoints verified when provisioned. {note}', ['id' => $pack['id'], 'version' => $pack['version'], 'note' => $pack['capability_note'] ?? pl_t('This is a sample bookkeeping example, not a complete industry system.')])) ?> <?php if (pl_demo_enabled()): ?><?= pl_e(pl_t('Use Leave demo and start again to choose another company. Each new visitor receives separate books; all access expires at the next hourly reset.')) ?><?php endif; ?></p>
</section>
