<?php
declare(strict_types=1);
$value=static fn(string $name,string $default=''):string=>pl_web_text($input,$name,$default);
$field=static function(string $name,string $label,string $type='text',string $default='') use($value):void { ?>
<label class="field"><?= pl_e(pl_t($label)) ?><input class="input" type="<?= pl_e($type) ?>" name="<?= pl_e($name) ?>" value="<?= pl_e($value($name,$default)) ?>" <?= $type==='number'?'min="1"':'' ?>></label>
<?php };
$account=static function(string $name,string $label,string $type) use($accounts,$value):void { ?>
<label class="field"><?= pl_e(pl_t($label)) ?><select class="select" name="<?= pl_e($name) ?>" required><option value=""><?= pl_e(pl_t('Choose account')) ?></option><?php foreach($accounts as $a):if($type!=='' && $a['type']!==$type){continue;} ?><option value="<?= (int)$a['id'] ?>" <?= $value($name)===(string)$a['id']?'selected':'' ?>><?= pl_e($a['code'].' · '.$a['name']) ?></option><?php endforeach ?></select></label>
<?php };
?>
<section class="flex flex-col gap-4 py-5">
<div class="page-header"><div><p class="eyebrow"><?= pl_e(pl_t('Planning and review')) ?></p><h1 class="page-title"><?= pl_e(pl_t(ucfirst($area))) ?></h1><p class="muted"><?= pl_e(pl_t('Schedules create review drafts. Review and post each draft through the ordinary journal or document workflow. No payment is sent.')) ?></p></div></div>
<nav class="flex gap-3 flex-wrap" aria-label="<?= pl_e(pl_t('Schedule pages')) ?>"><?php foreach(['recurring'=>'Recurring documents','schedules'=>'Prepaids, accruals and deferred income','loans'=>'Loans'] as $link=>$label): ?><a href="<?= pl_e(pl_url('/'.$link)) ?>"><?= pl_e(pl_t($label)) ?></a><?php endforeach ?></nav>
<?php if(pl_web_text($form,'message')!==''): ?><div class="alert alert-danger" role="alert"><?= pl_e(pl_web_text($form,'message')) ?></div><?php endif ?>
<?php if($area!=='recurring'): ?>
<form method="get" class="flex gap-3 items-end"><label class="field"><?= pl_e(pl_t('As of')) ?><input class="input" type="date" name="as_of" value="<?= pl_e($asOf) ?>" required></label><button class="btn btn-secondary"><?= pl_e(pl_t('Refresh report')) ?></button></form>
<div class="rounded-panel border border-border bg-surface p-4 overflow-x-auto"><h2 class="section-title"><?= pl_e(pl_t('Account reconciliation')) ?></h2><table class="table"><thead><tr><th><?= pl_e(pl_t('Account')) ?></th><th><?= pl_e(pl_t('Schedule balance')) ?></th><th><?= pl_e(pl_t('Ledger balance')) ?></th><th><?= pl_e(pl_t('Difference')) ?></th></tr></thead><tbody><?php foreach($data['accounts'] as $a): ?><tr><td><?= pl_e((string)$a['account_id']) ?></td><td><?= pl_e((string)($a['scheduled_balance']??$a['outstanding']??'')) ?></td><td><?= pl_e((string)($a['ledger_balance']??'')) ?></td><td><?= pl_e($a['difference']) ?></td></tr><?php endforeach ?></tbody></table></div>
<?php foreach($data[$area==='loans'?'loans':'schedules'] as $row): ?>
<article class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title">#<?= (int)$row['id'] ?> <?= pl_e($row['name']) ?></h2>
<?php if($area==='loans'): ?><p><?= pl_e(pl_t('Outstanding principal')) ?>: <?= pl_e($row['outstanding']) ?> · <?= pl_e(pl_t('Current within 12 months')) ?>: <?= pl_e($row['current']) ?> · <?= pl_e(pl_t('Non-current')) ?>: <?= pl_e($row['non_current']) ?> · <?= pl_e(pl_t('Interest paid to date')) ?>: <?= pl_e($row['interest_paid']) ?></p><?php else: ?><p><?= pl_e(pl_t('Unreleased balance')) ?>: <?= pl_e($row['unreleased']) ?></p><?php endif ?>
<?php if($area==='loans' && $mayManage): ?><p><a href="<?= pl_e(pl_url('/loans').'?revise='.(int)$row['id']) ?>"><?= pl_e(pl_t('Reschedule remaining principal')) ?></a></p><?php endif ?><div class="overflow-x-auto"><table class="table"><thead><tr><th><?= pl_e(pl_t('Due date')) ?></th><th><?= pl_e(pl_t('Principal / amount')) ?></th><th><?= pl_e(pl_t('Interest')) ?></th><th><?= pl_e(pl_t('Review draft')) ?></th></tr></thead><tbody><?php foreach(($row[$area==='loans'?'schedule':'releases']??[]) as $r): ?><tr><td><?= pl_e($r['due_date']) ?></td><td><?= pl_e($r['principal']??$r['amount']) ?></td><td><?= pl_e($r['interest']??'—') ?></td><td><?php if(!empty($r['draft_id'])): ?><a href="<?= pl_e(pl_url('/general-journals/detail').'?id='.(int)$r['draft_id']) ?>">#<?= (int)$r['draft_id'] ?></a><?php else: ?><?= pl_e(pl_t('Not generated')) ?><?php endif ?></td></tr><?php endforeach ?></tbody></table></div>
<?php if($area==='loans' && $mayManage && ($row['version']['method']??'')==='custom'): ?><form method="post" class="flex flex-col gap-3 mt-3"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><h3 class="section-title"><?= pl_e(pl_t('Lender-supported period-end accrual')) ?></h3><p class="muted"><?= pl_e(pl_t('Enter the period ID from Periods and the accrued interest from your lender calculation. This creates a review draft with a next-day reversal schedule.')) ?></p><label class="field"><?= pl_e(pl_t('Period ID')) ?><input class="input" name="period_id" type="number" min="1" required></label><label class="field"><?= pl_e(pl_t('Accrued interest')) ?><input class="input" name="amount" required></label><label class="field"><?= pl_e(pl_t('Calculation reference / reason')) ?><input class="input" name="reason" required></label><button class="btn btn-secondary" name="action" value="custom_accrual"><?= pl_e(pl_t('Queue accrual draft')) ?></button></form><?php endif ?>
</article><?php endforeach ?>
<?php else: ?>
<?php foreach($rows as $row): ?><article class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title">#<?= (int)$row['id'] ?> <?= pl_e($row['name']) ?></h2><p><?= pl_e($row['frequency'].' · '.$row['status']) ?> · <?= pl_e(pl_t('Occurrences processed')) ?>: <?= (int)$row['next_index'] ?></p><?php if($mayManage && $row['status']!=='ended'): ?><form method="post" class="flex gap-3 flex-wrap"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="revision" value="<?= (int)$row['revision'] ?>"><label class="field"><?= pl_e(pl_t('Reason')) ?><input class="input" name="reason" required></label><?php foreach([$row['status']==='active'?'pause':'resume','skip','end'] as $action): ?><button class="btn btn-secondary" name="action" value="<?= pl_e($action) ?>"><?= pl_e(pl_t(ucfirst($action))) ?></button><?php endforeach ?></form><?php endif ?><?php if($area==='loans' && $mayManage && ($row['version']['method']??'')==='custom'): ?><form method="post" class="flex flex-col gap-3 mt-3"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><h3 class="section-title"><?= pl_e(pl_t('Lender-supported period-end accrual')) ?></h3><p class="muted"><?= pl_e(pl_t('Enter the period ID from Periods and the accrued interest from your lender calculation. This creates a review draft with a next-day reversal schedule.')) ?></p><label class="field"><?= pl_e(pl_t('Period ID')) ?><input class="input" name="period_id" type="number" min="1" required></label><label class="field"><?= pl_e(pl_t('Accrued interest')) ?><input class="input" name="amount" required></label><label class="field"><?= pl_e(pl_t('Calculation reference / reason')) ?><input class="input" name="reason" required></label><button class="btn btn-secondary" name="action" value="custom_accrual"><?= pl_e(pl_t('Queue accrual draft')) ?></button></form><?php endif ?>
</article><?php endforeach ?>
<?php endif ?>
<?php if($mayManage && !$report): ?>
<form method="post" class="rounded-panel border border-border bg-surface p-4 flex flex-col gap-3"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><h2 class="section-title"><?= pl_e(pl_t('Generate due drafts')) ?></h2><label class="field"><?= pl_e(pl_t('Through date')) ?><input class="input" type="date" name="as_of" value="<?= pl_e($asOf) ?>" required></label><button class="btn btn-secondary" name="action" value="generate"><?= pl_e(pl_t('Generate up to 100 due drafts')) ?></button></form>
<form method="post" class="rounded-panel border border-border bg-surface p-4 flex flex-col gap-4"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><input type="hidden" name="creation_key" value="<?= pl_e($value('creation_key')) ?>"><input type="hidden" name="id" value="<?= pl_e($value('id')) ?>"><input type="hidden" name="revision" value="<?= pl_e($value('revision')) ?>"><h2 class="section-title"><?= pl_e(pl_t($value('id')!==''?'Review revised loan terms':'New plan')) ?></h2><div class="grid gap-4 md:grid-cols-2">
<?php $field('name','Plan name');$field('start_date','Start date','date'); ?>
<?php if($area==='recurring'): ?>
<label class="field"><?= pl_e(pl_t('Posted source')) ?><select class="select" name="source_kind"><?php foreach(['journal'=>'Standalone journal','ar'=>'Invoice or bill','document'=>'Receipt or expense'] as $k=>$v): ?><option value="<?= pl_e($k) ?>" <?= $value('source_kind')===$k?'selected':'' ?>><?= pl_e(pl_t($v)) ?></option><?php endforeach ?></select></label><?php $field('source_id','Posted source ID','number'); ?>
<label class="field"><?= pl_e(pl_t('Frequency')) ?><select class="select" name="frequency"><?php foreach(['weekly','monthly','quarterly','yearly','days'] as $f): ?><option <?= $value('frequency')===$f?'selected':'' ?>><?= pl_e($f) ?></option><?php endforeach ?></select></label><?php $field('every_days','Every N days (days frequency)','number','1');$field('max_runs','Maximum occurrences (optional)','number');$field('end_date','End date (optional)','date');$field('lead_days','Lead days','text','0');$field('fixed_amount','Fixed receipt / expense amount (optional)'); ?>
<?php elseif($area==='schedules'): ?>
<label class="field"><?= pl_e(pl_t('Schedule type')) ?><select class="select" name="kind"><?php foreach(['prepaid','accrual','deferred'] as $kind): ?><option <?= $value('kind')===$kind?'selected':'' ?>><?= pl_e($kind) ?></option><?php endforeach ?></select></label><?php $field('amount','Total amount');$field('periods','Monthly releases','number','12');$field('funding_journal_id','Posted funding / opening journal ID','number');$account('balance_account_id','Balance account (asset for prepaid; liability otherwise)','');$account('counterpart_account_id','Release account (expense; income for deferred)',''); ?>
<?php else: ?>
<label class="field"><?= pl_e(pl_t('Lender')) ?><select class="select" name="lender_party_id" required><option value=""><?= pl_e(pl_t('Choose party')) ?></option><?php foreach($parties as $party): ?><option value="<?= (int)$party['id'] ?>" <?= $value('lender_party_id')===(string)$party['id']?'selected':'' ?>><?= pl_e($party['legal_name']) ?></option><?php endforeach ?></select></label>
<?php $field('principal','Principal');$field('annual_rate','Annual nominal rate (%)','text','0');$field('term_months','Monthly instalments','number','12');$field('payment','Payment amount (optional for computed schedule)');$field('funding_journal_id','Posted funding / opening journal ID','number'); ?>
<label class="field"><?= pl_e(pl_t('Calculation')) ?><select class="select" name="method"><?php foreach(['reducing'=>'Reducing balance','flat'=>'Flat interest','custom'=>'Lender-entered schedule'] as $k=>$v): ?><option value="<?= pl_e($k) ?>" <?= $value('method')===$k?'selected':'' ?>><?= pl_e(pl_t($v)) ?></option><?php endforeach ?></select></label>
<?php $account('liability_account_id','Loan liability','liability');$account('interest_account_id','Interest expense','expense');$account('bank_account_id','Payment cash / bank','asset');$account('accrued_account_id','Accrued interest liability','liability'); ?>
<?php endif ?>
<?php $field('reason','Reason / terms reference'); ?></div>
<?php if($area!=='recurring'): ?><label class="field"><?= pl_e(pl_t($area==='loans'?'Custom lender rows: date, principal, interest':'Custom releases (optional): date, amount')) ?><textarea class="input" name="custom_csv" rows="5" placeholder="<?= $area==='loans'?'2026-10-31, 100.0000, 5.0000':'2026-10-31, 100.0000' ?>"><?= pl_e($value('custom_csv')) ?></textarea></label><?php endif ?>
<?php if($area==='loans'): ?><p class="muted"><?= pl_e(pl_t('Computed loans use monthly nominal APR / 12 and Actual/365 period-end accrual, four-decimal half-up rounding and a final principal adjustment. Functional currency only. Compare the preview with your lender terms; enter a custom schedule when they differ. Custom schedules do not invent period-end accrual rates.')) ?></p><button class="btn btn-secondary" name="action" value="preview"><?= pl_e(pl_t('Preview amortization')) ?></button>
<?php if($preview!==null): ?><input type="hidden" name="preview_hash" value="<?= pl_e(hash('sha256',json_encode($preview,JSON_THROW_ON_ERROR))) ?>"><p><?= pl_e(pl_t('Total interest')) ?>: <?= pl_e($preview['total_interest']) ?> · <?= pl_e(pl_t('Total payments')) ?>: <?= pl_e($preview['total_payments']) ?></p><div class="overflow-x-auto"><table class="table"><thead><tr><th><?= pl_e(pl_t('Date')) ?></th><th><?= pl_e(pl_t('Principal')) ?></th><th><?= pl_e(pl_t('Interest')) ?></th><th><?= pl_e(pl_t('Closing principal')) ?></th></tr></thead><tbody><?php foreach($preview['rows'] as $r): ?><tr><td><?= pl_e($r['date']) ?></td><td><?= pl_e($r['principal']) ?></td><td><?= pl_e($r['interest']) ?></td><td><?= pl_e($r['closing_balance']) ?></td></tr><?php endforeach ?></tbody></table></div><button class="btn btn-primary" name="action" value="save"><?= pl_e(pl_t('Confirm reviewed loan plan')) ?></button><?php endif ?>
<?php else: ?><button class="btn btn-primary" name="action" value="save"><?= pl_e(pl_t('Save plan')) ?></button><?php endif ?></form>
<?php endif ?>
<div class="rounded-panel border border-border bg-surface p-4 overflow-x-auto"><h2 class="section-title"><?= pl_e(pl_t('Recent scheduled work')) ?></h2><table class="table"><thead><tr><th><?= pl_e(pl_t('Due')) ?></th><th><?= pl_e(pl_t('Kind')) ?></th><th><?= pl_e(pl_t('Status')) ?></th><th><?= pl_e(pl_t('Attempts')) ?></th><th><?= pl_e(pl_t('Review')) ?></th></tr></thead><tbody><?php foreach($jobs as $job):$result=$job['result']===null?null:json_decode($job['result'],true); ?><tr><td><?= pl_e($job['occurrence_date']) ?></td><td><?= pl_e($job['job_kind']) ?></td><td><?= pl_e($job['status']) ?></td><td><?= (int)$job['attempts'] ?></td><td><?php if($result):$route=match($result['kind']){'journal'=>'/general-journals/detail','ar'=>'/ar',default=>'/transactions/detail'}; ?><a href="<?= pl_e(pl_url($route).'?id='.(int)$result['id']) ?>">#<?= (int)$result['id'] ?></a><?php endif ?></td></tr><?php endforeach ?></tbody></table></div>
</section>
