<?php declare(strict_types=1);
$v=$form['input']; $settingsInput=($v['action']??'')==='settings'?$v:[]; $codeInput=($v['action']??'')==='code'?$v:[]; $rateInput=($v['action']??'')==='rate'?$v:[];
$accountNames=pl_starter_options($accounts); $today=gmdate('Y-m-d'); $effective=[];
foreach ($rates as $rate) { if ($rate['effective_from']<=$today && !isset($effective[$rate['tax_code_id']])) { $effective[$rate['tax_code_id']]=$rate; } }
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header(pl_t('Tax codes'),pl_t('Country-neutral codes with dated rates and frozen document amounts'),static function () use ($company,$codeInput,$accounts,$form): void {
if (pl_can_write($company)) { pl_ui_sheet(pl_t('New tax code'),static function () use ($company,$codeInput,$accounts,$form): void { ?>
<?php if ($codeInput && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<form class="flex flex-col gap-4" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'code',['request_key'=>$codeInput['request_key']??null]);
pl_starter_field(pl_t('Code'),'code',$codeInput['code']??''); pl_starter_field(pl_t('Name'),'name',$codeInput['name']??''); pl_starter_select(pl_t('Treatment'),'treatment',['standard'=>pl_t('Standard rate'),'zero'=>pl_t('Zero-rated'),'exempt'=>pl_t('Exempt')],$codeInput['treatment']??'standard');
pl_starter_select(pl_t('Output tax liability account'),'sales_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='liability'&&$a['role']===null)),$codeInput['sales_account_id']??'');
pl_starter_select(pl_t('Recoverable input tax asset account'),'purchase_account_id',pl_starter_options(array_filter($accounts,fn($a)=>$a['type']==='asset'&&$a['role']===null)),$codeInput['purchase_account_id']??''); pl_starter_field(pl_t('Reason'),'reason',$codeInput['reason']??''); ?>
<p class="text-xs text-ink-muted"><?= pl_e(pl_t('Code definitions are retained as created. Add dated rates after saving. For a different treatment or posting account, create a new code.')) ?></p><button class="btn btn-primary"><?= pl_e(pl_t('Create tax code')) ?></button></form>
<?php },(bool)$codeInput,'btn btn-primary'); } }); ?>
<div class="alert alert-info"><div><strong><?= pl_e(pl_t('No national tax rules are inferred')) ?></strong><p><?= pl_e(pl_t('Codes, rates and accounts are entered manually. Select a code on each taxable invoice or bill line. Input tax uses the configured recoverable tax account. No country rules, forms or e-filing are included.')) ?></p></div></div>
<section class="rounded-panel border border-border bg-surface p-4"><h2 class="section-title mb-2"><?= pl_e(pl_t('Price entry default')) ?></h2><p class="text-sm"><?= pl_e(pl_t('Current default:')) ?> <strong><?= pl_e($settings['price_mode']==='inclusive'?pl_t('Prices include tax'):pl_t('Prices exclude tax')) ?></strong></p><p class="text-xs text-ink-muted mt-1"><?= pl_e(pl_t('Applies to new documents. Existing documents retain their saved price mode. Net, tax and total are shown separately.')) ?></p>
<?php if ($settingsInput && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<?php if ($company['role']==='owner'): ?><form class="grid grid-cols-1 md:grid-cols-3 gap-3 items-end mt-3" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'settings',['revision'=>$settingsInput?($settingsInput['revision']??''):$settings['revision'],'request_key'=>$settingsInput['request_key']??null]); pl_starter_select(pl_t('Entered prices'),'price_mode',['exclusive'=>pl_t('Exclude tax (tax added)'),'inclusive'=>pl_t('Include tax (tax extracted)')],$settingsInput['price_mode']??$settings['price_mode']); pl_starter_field(pl_t('Reason'),'reason',$settingsInput['reason']??''); ?><button class="btn btn-secondary"><?= pl_e(pl_t('Save price setting')) ?></button></form><?php if ($settingsInput): ?><a class="link" href="<?= pl_e(pl_url('/tax')) ?>"><?= pl_e(pl_t('Reload saved setting')) ?></a><?php endif; else: ?><p class="text-sm mt-2"><?= pl_e(pl_t('Only the company owner can change the price entry setting.')) ?></p><?php endif; ?></section>
<section><h2 class="section-title mb-2"><?= pl_e(pl_t('Codes')) ?></h2><p class="text-xs text-ink-muted mb-2"><?= pl_e(pl_t('Effective rates as of {date}. Code definitions are read-only; manage dated rates below.', ['date' => pl_date_label($today)])) ?></p>
<?php pl_ui_table([pl_t('Code'),pl_t('Treatment'),pl_t('Effective rate'),pl_t('Output account'),pl_t('Input account'),pl_t('Actions')],static function () use ($codes,$effective,$accountNames,$company,$rateInput,$form): void { foreach ($codes as $code): $rate=$effective[$code['id']]??null; $input=(int)($rateInput['tax_code_id']??0)===(int)$code['id']?$rateInput:[]; ?>
<tr><td><span class="row-title"><?= pl_e($code['code']) ?></span><span class="row-sub"><?= pl_e($code['name']) ?></span></td><td><?= pl_e(pl_t(['standard'=>'Standard rate','zero'=>'Zero-rated','exempt'=>'Exempt'][$code['treatment']])) ?></td><td class="amount"><?= $rate?pl_e($rate['percentage']).'%':pl_e(pl_t('Not configured')) ?><?php if ($rate): ?><span class="row-sub"><?= pl_e(pl_t('Since {date}', ['date' => pl_date_label($rate['effective_from'])])) ?></span><?php endif; ?></td><td><?= pl_e($accountNames[$code['sales_account_id']]??pl_t('Account {id}', ['id' => $code['sales_account_id']])) ?></td><td><?= pl_e($accountNames[$code['purchase_account_id']]??pl_t('Account {id}', ['id' => $code['purchase_account_id']])) ?></td><td>
<?php if (pl_can_write($company)) { pl_ui_sheet(pl_t('Manage rates · {code}', ['code' => $code['code']]),static function () use ($company,$code,$input,$form,$accountNames): void { ?>
<dl class="dgrid mb-4"><?php foreach (['Code'=>$code['code'],'Name'=>$code['name'],'Treatment'=>$code['treatment'],'Output account'=>$accountNames[$code['sales_account_id']]??pl_t('Account {id}', ['id' => $code['sales_account_id']]),'Input account'=>$accountNames[$code['purchase_account_id']]??pl_t('Account {id}', ['id' => $code['purchase_account_id']])] as $label=>$value): ?><div class="dgrid-row"><dt><?= pl_e(pl_t($label)) ?></dt><dd><?= pl_e($value) ?></dd></div><?php endforeach; ?></dl>
<p class="text-xs text-ink-muted mb-4"><?= pl_e(pl_t('These code fields are read-only. A new effective date applies until the next dated rate. A revision for the same date supersedes it for new drafts; posted documents retain their original snapshots.')) ?></p>
<?php if ($input && $form['message']!==''): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><?= pl_e($form['message']) ?></div><?php endif; ?>
<form class="flex flex-col gap-4" method="post" action="<?= pl_e(pl_url('/tax')) ?>"><?php pl_starter_form($company,'rate',['request_key'=>$input['request_key']??null,'tax_code_id'=>$code['id']]); pl_starter_field(pl_t('Effective from'),'effective_from',$input['effective_from']??'','date'); pl_starter_field(pl_t('Percentage'),'percentage',$input['percentage']??''); pl_starter_field(pl_t('Reason'),'reason',$input['reason']??''); ?><button class="btn btn-primary"><?= pl_e(pl_t('Record dated rate')) ?></button></form>
<?php },(bool)$input,'btn btn-ghost btn-sm'); } else { echo pl_e(pl_t('Read-only')); } ?></td></tr>
<?php endforeach; if (!$codes): ?><tr><td colspan="6"><?= pl_e(pl_t('No tax codes yet. No tax is added unless a code is explicitly selected.')) ?></td></tr><?php endif; },pl_t('Tax codes and current effective rates')); ?></section>
<section><h2 class="section-title mb-2"><?= pl_e(pl_t('Rate history')) ?></h2><?php pl_ui_table([pl_t('Code'),pl_t('Effective from'),pl_t('Percentage'),pl_t('Revision'),pl_t('Reason')],static function () use ($rates): void { foreach ($rates as $row): ?><tr><td><?= pl_e($row['code']) ?></td><td><?= pl_e(pl_date_label($row['effective_from'])) ?></td><td class="amount"><?= pl_e($row['percentage']) ?>%</td><td><?= (int)$row['revision'] ?></td><td><?= pl_e($row['reason']) ?></td></tr><?php endforeach; if (!$rates): ?><tr><td colspan="5"><?= pl_e(pl_t('No rates configured. No tax is added unless a code is explicitly selected.')) ?></td></tr><?php endif; },pl_t('Tax rate history')); ?></section>
</div>
