<?php
declare(strict_types=1);
$statusLabels = ['draft' => 'Drafts', 'posted' => 'Posted', 'reversed' => 'Reversed', 'all' => 'All transactions'];
$selectedStatus = $filters['status'];
$scopeQuery = $filters;
?>
<div class="flex flex-col gap-4 py-5">
<?php pl_ui_page_header(pl_t('Receipts & expenses'), pl_t('{count} records · {currency} {amount}', ['count' => $list['total'], 'currency' => $company['currency'], 'amount' => pl_money($list['total_amount'])]), static function () use ($company, $filters): void { ?>
    <a class="btn btn-ghost" href="<?= pl_e(pl_url('/reports/account')) ?>"><?= pl_icon('book-2') ?> <?= pl_e(pl_t('Account ledger')) ?></a>
    <?php if (pl_can_write($company)): ?><a class="btn btn-primary" href="<?= pl_e(pl_workflow_url('/transactions/new', ['return_filters'=>$filters])) ?>"><?= pl_icon('plus') ?> <?= pl_e(pl_t('New transaction')) ?></a><?php endif; ?>
<?php }); ?>
<div class="split-view <?= $detailOnly ? 'transaction-record-view' : '' ?>">
<section class="split-view-list<?= $detailOnly || isset($_GET['id']) ? ' has-detail' : '' ?>" aria-label="<?= pl_e(pl_t('Transaction list')) ?>">
    <nav class="tabs-seg mb-3" aria-label="<?= pl_e(pl_t('Transaction status')) ?>"><?php foreach ($statusLabels as $key => $label): ?><a class="tabs-seg-item" href="<?= pl_e(pl_workflow_url('/transactions', array_replace($scopeQuery, ['status' => $key, 'page' => 1]))) ?>" <?= $selectedStatus === $key ? 'aria-current="page"' : '' ?>><?= pl_e(pl_t($label)) ?></a><?php endforeach; ?></nav>
    <form class="filter-bar mb-3" action="<?= pl_e(pl_workflow_url('/transactions')) ?>" method="get">
        <input type="hidden" name="status" value="<?= pl_e($selectedStatus) ?>">
        <?php pl_ui_list_controls($filters); ?>
        <label><span class="sr-only"><?= pl_e(pl_t('Transaction type')) ?></span><select class="select" name="kind"><option value="all"><?= pl_e(pl_t('All types')) ?></option><option value="expense" <?= $filters['kind'] === 'expense' ? 'selected' : '' ?>><?= pl_e(pl_t('Expenses')) ?></option><option value="receipt" <?= $filters['kind'] === 'receipt' ? 'selected' : '' ?>><?= pl_e(pl_t('Receipts')) ?></option></select></label>
        <button class="btn btn-secondary" type="submit"><?= pl_e(pl_t('Filter')) ?></button>
        <details class="date-filters"><summary><?= pl_e(pl_t('Date range')) ?></summary><div><label><?= pl_e(pl_t('From')) ?> <input type="date" name="from" value="<?= pl_e($filters['from']) ?>"></label><label><?= pl_e(pl_t('To')) ?> <input type="date" name="to" value="<?= pl_e($filters['to']) ?>"></label><button class="btn btn-secondary" type="submit"><?= pl_e(pl_t('Apply dates')) ?></button></div></details>
        <?php if ($filters['q'] || $filters['from'] || $filters['to'] || $filters['kind'] !== 'all'): ?><a class="clear-filter" href="<?= pl_e(pl_workflow_url('/transactions', ['status' => $selectedStatus])) ?>"><?= pl_e(pl_t('Clear filters')) ?></a><?php endif; ?>
    </form>
    <div class="transaction-table table-wrap" tabindex="0" role="region" aria-label="<?= pl_e(pl_t('Transaction list; scroll horizontally on smaller screens')) ?>"><table class="table">
        <caption class="sr-only"><?= pl_e(pl_t('Choose a transaction to inspect its details')) ?></caption>
        <thead><tr><?php foreach (['date'=>'Date / reference','name'=>'Name','amount'=>'Amount','status'=>'Status'] as $key=>$label): ?><th scope="col"<?= $key === 'amount' ? ' class="num"' : '' ?>><?php pl_ui_sort('/transactions', $filters, $key, pl_t($label)); ?></th><?php endforeach; ?></tr></thead>
        <tbody><?php foreach ($list['documents'] as $row): $selected = $document && (int) $document['id'] === (int) $row['id']; ?>
        <tr class="<?= $selected ? 'selected' : '' ?>"><td><a class="record-link" href="<?= pl_e(pl_workflow_url('/transactions/detail', array_replace($scopeQuery, ['id' => $row['id']]))) ?>" <?= $selected ? 'aria-current="true"' : '' ?> data-record-link><strong><?= pl_e(pl_date_label($row['date'])) ?></strong><span class="muted"><?= pl_e($row['number']) ?></span></a></td><td><span class="payee"><?= pl_e($row['counterparty'] ?: pl_t('No name entered')) ?></span><span class="muted row-secondary"><?= pl_e(ucfirst($row['kind'])) ?></span></td><td class="amount"><?= pl_e(pl_money($row['amount'])) ?></td><td><?php pl_ui_badge($row['status'], pl_t(ucfirst($row['status']))); ?></td></tr>
        <?php endforeach; ?></tbody>
    </table>
    <?php if (!$list['documents']): ?><div class="empty-state"><?= pl_icon('receipt') ?><h2><?= pl_e($selectedStatus === 'draft' ? pl_t('A clear place to start.') : pl_t('No matching transactions.')) ?></h2><p><?= pl_e($selectedStatus === 'draft' ? pl_t('Record money in or money out. Review the balanced entry before it reaches your books.') : pl_t('Try another status or adjust your filters.')) ?></p><?php if (pl_can_write($company)): ?><a href="<?= pl_e(pl_workflow_url('/transactions/new')) ?>" class="btn btn-primary"><?= pl_e(pl_t('Record your first transaction')) ?></a><?php endif; ?></div><?php endif; ?>
    </div>
    <div class="list-footer"><span><?= pl_e(pl_t('{count} records · Total', ['count' => (int) $list['total']])) ?> <strong><?= pl_e($company['currency'] . ' ' . pl_money($list['total_amount'])) ?></strong></span><div class="pagination"><?php if ($list['page'] > 1): ?><a class="icon-button" aria-label="<?= pl_e(pl_t('Previous page')) ?>" href="<?= pl_e(pl_workflow_url('/transactions', array_replace($scopeQuery, ['page' => $list['page'] - 1]))) ?>"><?= pl_icon('chevron-left') ?></a><?php endif; ?><span><?= pl_e(pl_t('Page {page} of {pages}', ['page' => (int) $list['page'], 'pages' => max(1, (int) $list['pages'])])) ?></span><?php if ($list['page'] < $list['pages']): ?><a class="icon-button" aria-label="<?= pl_e(pl_t('Next page')) ?>" href="<?= pl_e(pl_workflow_url('/transactions', array_replace($scopeQuery, ['page' => $list['page'] + 1]))) ?>"><?= pl_icon('chevron-right') ?></a><?php endif; ?></div></div>
    <?php if ($company['is_sample']): ?><p class="sample-note"><?= pl_icon('info-circle') ?> <?= pl_e(pl_t('These are sample records in a separate sample company.')) ?></p><?php endif; ?>
</section>
<section class="transaction-detail split-view-detail" aria-label="<?= pl_e(pl_t('Transaction details')) ?>">
<?php if ($document): ?>
<?php if($document['status']==='posted' && pl_user_can((int)$user['id'],(int)$company['id'],'schedules.manage')): ?><p><a class="btn btn-secondary" href="<?= pl_e(pl_url('/recurring').'?source_kind=document&source_id='.(int)$document['id']) ?>"><?= pl_e(pl_t('Make recurring')) ?></a></p><?php endif ?>
    <a class="split-view-back" href="<?= pl_e(pl_workflow_url('/transactions', $scopeQuery)) ?>"><?= pl_icon('arrow-left') ?> <?= pl_e(pl_t('Back to list')) ?></a>
    <?php if ($form['message']): ?><div class="alert alert-danger" role="alert" tabindex="-1" data-form-error><strong><?= pl_e(pl_t('We couldn\'t complete that action.')) ?></strong><p><?= pl_e($form['message']) ?></p></div><?php endif; ?>
    <div class="detail-heading"><div><div class="inline-heading"><h2><?= pl_e($document['number']) ?></h2><span class="badge <?= pl_e($document['status']) ?>"><?= pl_e(ucfirst($document['status'])) ?></span></div><h3><?= pl_e($document['counterparty'] ?: ucfirst($document['kind'])) ?></h3></div><p class="detail-amount"><?= pl_e($company['currency']) ?> <strong><?= pl_e(pl_money($document['amount'])) ?></strong></p></div>
    <?php pl_ui_tabs([pl_t('Details')=>'#record-details',pl_t('Journal')=>'#record-journal',pl_t('History')=>'#record-history'], pl_t('Details'), true); ?>
    <section id="record-details" data-ui-tab-panel><dl class="record-details"><div><dt><?= pl_e($document['kind'] === 'expense' ? pl_t('Paid to') : pl_t('Received from')) ?></dt><dd><?= pl_e($document['counterparty'] ?: '—') ?></dd></div><div><dt><?= pl_e(pl_t('Reference')) ?></dt><dd><?= pl_e($document['reference'] ?: '—') ?></dd></div><div><dt><?= pl_e(pl_t('Date')) ?></dt><dd><?= pl_e(pl_date_label($document['date'])) ?></dd></div><div><dt><?= pl_e($document['kind'] === 'expense' ? pl_t('Paid from') : pl_t('Received into')) ?></dt><dd><?= pl_e($document['money_account_name']) ?></dd></div><div><dt><?= pl_e(pl_t('Category')) ?></dt><dd><?= pl_e($document['category_account_name']) ?></dd></div><div><dt><?= pl_e(pl_t('Memo')) ?></dt><dd><?= pl_e($document['memo'] ?: '—') ?></dd></div></dl></section>
    <section id="record-journal" class="journal-section" data-ui-tab-panel><div class="section-heading"><h3><?= pl_e($document['status'] === 'draft' ? pl_t('Posting preview') : pl_t('Posted journal')) ?></h3><span class="balanced-label"><?= pl_icon('check') ?> <?= pl_e(pl_t('Balanced')) ?></span></div>
        <?php $entryLines = $document['journal'] ? $document['journal']['lines'] : $document['journal_preview']['lines']; require __DIR__ . '/../partials/entry.php'; ?>
        <p class="muted small"><?= pl_e($document['status'] === 'draft' ? pl_t('Posting adds this transaction to reports. A saved draft does not change your books.') : pl_t('This entry is included in your reports. Posted financial details are preserved.')) ?> <?php if ($document['journal_id']): ?><a href="<?= pl_e(pl_workflow_url('/journals/detail', ['id' => $document['journal_id']])) ?>"><?= pl_e(pl_t('Open journal {reference}', ['reference' => $document['journal']['reference']])) ?></a><?php endif; ?></p>
    </section>
    <section id="record-history" class="history-section" data-ui-tab-panel><h3 class="section-title"><?= pl_e(pl_t('History')) ?> <span class="muted"><?= pl_e(pl_t('· Revision {number}', ['number' => (int) $document['revision']])) ?></span></h3><dl class="record-details"><div><dt><?= pl_e(pl_t('Created')) ?></dt><dd><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $document['created_at']) . 'Z') ?>"><?= pl_e(pl_t('{time} UTC', ['time' => $document['created_at']])) ?></time></dd></div><div><dt><?= pl_e(pl_t('Last saved')) ?></dt><dd><time data-local-time datetime="<?= pl_e(str_replace(' ', 'T', $document['updated_at']) . 'Z') ?>"><?= pl_e(pl_t('{time} UTC', ['time' => $document['updated_at']])) ?></time></dd></div></dl><?php if ($document['reversal_journal_id']): ?><p><a href="<?= pl_e(pl_workflow_url('/journals/detail', ['id' => $document['reversal_journal_id']])) ?>"><?= pl_e(pl_t('Inspect the linked reversal')) ?></a></p><?php endif; ?></section>
    <?php if (pl_can_write($company)): ?><div class="detail-actions panel-actions" data-fold="primary action">
        <?php if ($document['status'] === 'draft'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_workflow_url('/' . ($document['kind'] === 'receipt' ? 'receipts' : 'expenses') . '/edit', ['id' => $document['id'], 'return_filters'=>$filters])) ?>"><?= pl_e(pl_t('Edit draft')) ?></a><form method="post" action="<?= pl_e(pl_workflow_url('/transactions/post')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><input type="hidden" name="revision" value="<?= (int) $document['revision'] ?>"><button class="btn btn-primary" type="submit" <?= $company['setup_status'] !== 'ready' ? 'disabled' : '' ?>><?= pl_e(pl_t('Post {kind}', ['kind' => $document['kind']])) ?></button></form>
        <?php elseif ($document['status'] === 'posted'): ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>"><?= pl_e(pl_t('See report effect')) ?></a><a class="text-button" href="#reverse-entry" data-open-details><?= pl_e(pl_t('Reverse transaction')) ?></a>
        <?php else: ?><a class="btn btn-secondary" href="<?= pl_e(pl_url('/reports/trial-balance')) ?>"><?= pl_e(pl_t('View trial balance')) ?></a><span class="muted"><?= pl_e(pl_t('Original and reversal retained')) ?></span><?php endif; ?>
    </div><?php endif; ?>
    <?php if ($document['status'] === 'posted' && pl_can_write($company)): ?><details class="reversal-form" id="reverse-entry" <?= $form['message'] ? 'open' : '' ?>><summary><?= pl_e(pl_t('Correct this entry with a reversal')) ?></summary><p><?= pl_e(pl_t('A reversal creates an opposite, linked entry on the date you choose. It preserves this transaction.')) ?></p><form method="post" action="<?= pl_e(pl_workflow_url('/transactions/reverse')) ?>"><?= pl_csrf_field() ?><?= pl_scope_fields($company) ?><?php pl_ui_return_filters($filters); ?><input type="hidden" name="id" value="<?= (int) $document['id'] ?>"><div class="form-grid"><label class="field"><?= pl_e(pl_t('Reversal date')) ?><input type="date" name="date" value="<?= pl_e(pl_web_text($form['input'], 'date', gmdate('Y-m-d'))) ?>" required <?= !isset($form['input']['date']) ? 'data-local-today' : '' ?>></label><label class="field full-width"><?= pl_e(pl_t('Reason')) ?><textarea name="reason" rows="2" maxlength="500" required><?= pl_e(pl_web_text($form['input'], 'reason')) ?></textarea></label></div><button type="submit" class="btn btn-secondary"><?= pl_e(pl_t('Post linked reversal')) ?></button></form></details><?php endif; ?>
<?php else: ?><div class="empty-detail"><span class="detail-mark"><?= pl_icon('book') ?></span><h2><?= pl_e(pl_t('Every entry tells a story.')) ?></h2><p><?= pl_e(pl_t('Select a transaction to see where the money went and how it appears in your books.')) ?></p></div><?php endif; ?>
</section>
</div>
</div>
