<?php declare(strict_types=1);
$input=$form['input'];
$selectedPolicy=$input!==[]?$input:($year['policy']??[]);
$accountOptions=static function(array $accounts,int $selected=0,?bool $drawings=null):void { ?><option value="">Choose an account</option><?php foreach($accounts as $account){if($drawings!==null&&($account['type']!=='equity'||(bool)$account['is_contra']!==$drawings)){continue;} ?><option value="<?= (int)$account['id'] ?>" <?= $selected===(int)$account['id']?'selected':'' ?>><?= pl_e($account['code'].' · '.$account['name']) ?></option><?php } };
$fields=static function(string $action)use($year,$company):void{echo pl_csrf_field(),pl_scope_fields($company);?><input type="hidden" name="action" value="<?= pl_e($action) ?>"><input type="hidden" name="year_id" value="<?= (int)($year['id']??0) ?>"><input type="hidden" name="revision" value="<?= (int)($year['revision']??0) ?>"><input type="hidden" name="request_key" value="<?= pl_e(bin2hex(random_bytes(16))) ?>"><?php };
?>
<section class="flex flex-col gap-4 py-4">
<?php pl_ui_page_header(pl_t('Year-end close'),pl_t('Review accounting policy, adjustments and closing entries. Reopening preserves the original evidence.')); ?>
<p class="muted">No distributions or tax treatment are inferred. Next-year opening balances continue from the ledger; no duplicate opening journal is posted.</p>
<?php if($form['message']!==''): ?><p class="alert alert-danger" role="alert"><?= pl_e($form['message']) ?></p><?php endif; ?>
<nav class="flex flex-wrap gap-3" aria-label="Fiscal years"><a class="btn btn-ghost" href="<?= pl_e(pl_url('/year-end')) ?>">New fiscal year</a><?php foreach($years as $row): ?><a class="btn btn-ghost" href="<?= pl_e(pl_url('/year-end',['id'=>$row['id']])) ?>"><?= pl_e($row['end_date'].' · '.$row['status']) ?></a><?php endforeach; ?></nav>
<?php if($year): ?><h2 class="section-title"><?= pl_e($year['start_date'].' — '.$year['end_date'].' · '.$year['status']) ?></h2><p>Policy: <?= pl_e($year['policy']['legal_basis'].' · '.$year['policy']['treatment']) ?>. <?= pl_e($year['policy']['review_note']) ?></p><?php endif; ?>
<?php if($canManage&&(!$year||in_array($year['status'],['open','closing'],true))): ?>
<details class="rounded-panel border border-border p-4" <?= !$year||$input!==[]?'open':'' ?>><summary class="section-title">Reviewed accounting policy</summary>
<form method="post" action="<?= pl_e(pl_url('/year-end')) ?>" class="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
<?php $fields($year?'policy':'create'); ?>
<?php if(!$year): ?><label>Fiscal year end<input class="input" type="date" name="end_date" required value="<?= pl_e(pl_web_text($input,'end_date')) ?>"></label><?php endif; ?>
<label>Accounting treatment<select class="input" name="treatment" required><option value="">Choose explicitly</option><?php foreach(['company'=>'Company: retained earnings','sole_trader'=>'Sole trader: owner capital','partnership'=>'Partnership: agreed appropriation'] as $key=>$label): ?><option value="<?= $key ?>" <?= ($selectedPolicy['treatment']??'')===$key?'selected':'' ?>><?= pl_e($label) ?></option><?php endforeach; ?></select></label>
<label>Legal form and agreement basis<input class="input" name="legal_basis" required maxlength="500" value="<?= pl_e($selectedPolicy['legal_basis']??'') ?>"></label>
<label>Company retained earnings / sole-trader capital<select class="input" name="destination_account_id"><?php $accountOptions($accounts,(int)($selectedPolicy['destination_account_id']??0),false); ?></select></label>
<label>Sole-trader drawings<select class="input" name="drawings_account_id"><?php $accountOptions($accounts,(int)($selectedPolicy['drawings_account_id']??0),true); ?></select></label>
<label>Partnership capital method<select class="input" name="capital_method"><option value="">Choose if partnership</option><?php foreach(['fixed','fluctuating'] as $method): ?><option <?= ($selectedPolicy['capital_method']??'')===$method?'selected':'' ?> value="<?= $method ?>"><?= ucfirst($method) ?></option><?php endforeach; ?></select></label>
<p class="muted">For partnerships, select every participating partner and confirm ratios as fractions summing to 1. Fixed capital transfers profit and drawings to current accounts. Fluctuating capital uses the registered capital accounts. A current account must be distinct from all partners' capital and drawings accounts.</p>
<?php $policyPartners=$year['policy']['partners']??[];for($i=0;$i<max(2,count($partners));$i++): $p=$policyPartners[$i]??[]; ?>
<fieldset class="border border-border p-3"><legend>Partner <?= $i+1 ?></legend><label>Partner<select class="input" name="partner_id[]"><option value="">Unused</option><?php foreach($partners as $partner): ?><option value="<?= (int)$partner['id'] ?>" <?= (int)($input['partner_id'][$i]??$p['partner_id']??0)===(int)$partner['id']?'selected':'' ?>><?= pl_e($partner['name']) ?></option><?php endforeach; ?></select></label><label>Reviewed ratio<input class="input" name="ratio[]" inputmode="decimal" placeholder="0.600000" value="<?= pl_e($input['ratio'][$i]??$p['ratio']??'') ?>"></label><label>Fixed-capital current account<select class="input" name="current_account_id[]"><?php $accountOptions($accounts,(int)($input['current_account_id'][$i]??$p['destination_account_id']??0),false); ?></select></label></fieldset>
<?php endfor; ?>
<label>Policy review note<textarea class="input" name="note" required maxlength="1000"><?= pl_e($input['note']??$selectedPolicy['review_note']??'') ?></textarea></label><button class="btn btn-primary" type="submit"><?= $year?'Save revised policy':'Create reviewed fiscal year' ?></button></form></details>
<?php endif; ?>
<?php if($previewError!==''): ?><p class="alert alert-warning"><?= pl_e($previewError) ?></p><?php endif; ?>
<?php if($preview): ?><div class="rounded-panel border border-border p-4"><h2 class="section-title">Closing preview</h2><p>Unclosed result: <?= pl_e(pl_money($preview['profit'])) ?></p><?php foreach($preview['blockers'] as $blocker): ?><p class="alert alert-warning"><?= pl_e($blocker) ?></p><?php endforeach; ?>
<div class="overflow-x-auto"><table class="table"><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody><?php foreach($preview['lines'] as $line): $a=array_values(array_filter($accounts,static fn(array $a):bool=>(int)$a['id']===$line['account_id']))[0]??['code'=>(string)$line['account_id'],'name'=>'']; ?><tr><td><?= pl_e($a['code'].' · '.$a['name']) ?></td><td><?= pl_e(pl_money($line['debit'])) ?></td><td><?= pl_e(pl_money($line['credit'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php foreach($preview['allocations'] as $allocation): ?><p><?= pl_e(($allocation['name']??'Earnings destination').': result '.$allocation['amount'].', drawings '.$allocation['drawings'].', net credit '.$allocation['net_credit']) ?></p><?php endforeach; ?></div><?php endif; ?>
<?php if($canManage&&$year): ?>
<?php if($year['status']==='closing'): ?><details class="rounded-panel border border-border p-4"><summary class="section-title">Post final-day adjustment</summary><p>Dated <?= pl_e($year['end_date']) ?>. Both sides must balance. Correct errors using the linked reversal action, then post a replacement.</p><form method="post" action="<?= pl_e(pl_url('/year-end')) ?>" class="grid gap-3"><?php $fields('adjust'); ?><label>Adjustment reason<input class="input" name="note" required maxlength="400"></label><?php for($i=0;$i<4;$i++): ?><fieldset class="grid grid-cols-1 sm:grid-cols-3 gap-2"><legend>Line <?= $i+1 ?></legend><label>Account<select class="input" name="account_id[]"><?php $accountOptions($accounts); ?></select></label><label>Debit<input class="input" name="debit[]" value="0" inputmode="decimal"></label><label>Credit<input class="input" name="credit[]" value="0" inputmode="decimal"></label></fieldset><?php endfor; ?><button class="btn btn-primary">Post reviewed adjustment</button></form></details><?php endif; ?>
<?php $actions=match($year['status']){'open'=>['start'=>'Start closing'],'closing'=>['close'=>'Close reviewed fiscal year','prepare'=>'Return to preparation'],'closed'=>['lock'=>'Lock fiscal year','reopen'=>'Reopen for correction'],'locked'=>['reopen'=>'Reopen for correction'],default=>[]};foreach($actions as $action=>$label): ?>
<form method="post" action="<?= pl_e(pl_url('/year-end')) ?>" class="rounded-panel border border-border p-4 grid gap-3"><?php $fields($action); ?><h2 class="section-title"><?= pl_e($label) ?></h2><?php if($action==='close'): ?><input type="hidden" name="fingerprint" value="<?= pl_e($preview['fingerprint']??'') ?>"><?php foreach(['stock'=>'Stock counts and valuation agreed','provisions'=>'Provisions reviewed','adjustments'=>'Adjusting journals complete','payroll'=>'Payroll reviewed'] as $key=>$text): ?><label><input type="checkbox" name="<?= $key ?>" value="1" required> <?= pl_e($text) ?> (or not applicable, explained below)</label><?php endforeach; ?><?php endif; ?><label>Review / correction note<textarea class="input" name="note" required maxlength="1000"></textarea></label><button class="btn btn-primary" <?= $action==='close'&&(!$preview||!$preview['ready'])?'disabled':'' ?>><?= pl_e($label) ?></button></form>
<?php endforeach;endif; ?>
<?php if($canManage&&$year&&$year['status']==='closing'): ?><details class="rounded-panel border border-border p-4"><summary class="section-title">Reverse a year-end adjustment</summary><form method="post" action="<?= pl_e(pl_url('/year-end')) ?>" class="grid gap-3"><?php $fields('reverse_adjustment'); ?><label>Original adjustment journal ID<input class="input" name="journal_id" type="number" min="1" required></label><label>Correction reason<input class="input" name="note" required maxlength="400"></label><button class="btn btn-primary">Post linked adjustment reversal</button></form></details><?php endif; ?>
<?php if($report): ?><h2 class="section-title">Reports and comparatives</h2><p>Use your browser's Print command for these trial balances and comparative totals. Closing entries are excluded from performance reports. These reports reflect all postings currently recorded.</p>
<div class="overflow-x-auto"><table class="table"><thead><tr><th>Report</th><th>This year</th><th>Previous registered year</th></tr></thead><tbody><tr><td>Net profit</td><td><?= pl_e($report['profit_loss']['net_profit']) ?></td><td><?= pl_e($report['comparative']['profit_loss']['net_profit']??'Not available') ?></td></tr><tr><td>Assets</td><td><?= pl_e($report['balance_sheet']['total_assets']) ?></td><td><?= pl_e($report['comparative']['balance_sheet']['total_assets']??'Not available') ?></td></tr></tbody></table></div>
<?php foreach(['unadjusted_trial_balance'=>'Pre-adjustment trial balance','adjusted_trial_balance'=>'Post-adjustment trial balance'] as $key=>$title): ?><details open><summary class="section-title"><?= pl_e($title) ?></summary><div class="overflow-x-auto"><table class="table"><thead><tr><th>Account</th><th>Debit</th><th>Credit</th></tr></thead><tbody><?php $debit='0.0000';$credit='0.0000';foreach($report[$key] as $a): if(bccomp($a['balance'],'0',4)===0){continue;}$d=bccomp($a['balance'],'0',4)>0?$a['balance']:'0.0000';$c=bccomp($a['balance'],'0',4)<0?bcsub('0',$a['balance'],4):'0.0000';$debit=bcadd($debit,$d,4);$credit=bcadd($credit,$c,4); ?><tr><td><?= pl_e($a['code'].' · '.$a['name']) ?></td><td><?= pl_e($d) ?></td><td><?= pl_e($c) ?></td></tr><?php endforeach; ?><tr><th>Total</th><th><?= pl_e($debit) ?></th><th><?= pl_e($credit) ?></th></tr></tbody></table></div></details><?php endforeach; ?>
<h2 class="section-title">Audit history</h2><?php foreach($report['history'] as $entry): ?><p><?= pl_e($entry['created_at'].' · '.$entry['display_name'].' · '.$entry['action'].' · '.$entry['review_note']) ?> <?php if($entry['journal_id']): ?><a href="<?= pl_e(pl_url('/journals/detail',['id'=>$entry['journal_id']])) ?>">Journal <?= (int)$entry['journal_id'] ?></a><?php endif; ?></p><?php if($entry['policy']): ?><details><summary>Policy recorded for this action</summary><p><?= pl_e($entry['policy']['legal_basis'].' � '.$entry['policy']['treatment'].' � '.$entry['policy']['review_note']) ?></p><?php foreach($entry['policy']['partners']??[] as $partner): ?><p><?= pl_e($partner['name'].' � ratio '.$partner['ratio'].' � destination account '.$partner['destination_account_id']) ?></p><?php endforeach; ?><?php foreach($entry['allocations'] as $allocation): ?><p><?= pl_e(($allocation['name']??'Earnings destination').': allocated '.$allocation['amount'].', drawings '.$allocation['drawings'].', net credit '.$allocation['net_credit']) ?></p><?php endforeach; ?></details><?php endif; ?><?php endforeach;endif; ?>
</section>
