ServerTokens Prod
ServerSignature Off
<VirtualHost *:8080>
    ServerName notice.internal
    DocumentRoot /opt/installation-service/public
    AliasMatch "^/installations/notice$" "/opt/installation-service/public/index.php"
    RemoteIPHeader X-Real-IP
    RemoteIPInternalProxy 10.219.68.2
    <Directory /opt/installation-service/public>
        Options -Indexes -FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    <Directory /opt/installation-service/includes>
        Require all denied
    </Directory>
    LimitRequestBody 16384
    RequestReadTimeout header=10-20,MinRate=500 body=10,MinRate=500
    ErrorLog /dev/null
    CustomLog /dev/null combined
</VirtualHost>
