#!/usr/bin/env python3
"""Regenerate www/phpledger/includes/icons.php from the Tabler files in public/assets/icons.

pl_icon() inlines each icon as SVG so it takes the current text colour (owner review of
25 September 2026: grey <img> icons never matched their state). The map keeps only the drawing
paths; the wrapper attributes live in pl_icon(). Run from the repository root:

    python tools/build-icons.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'www/phpledger/public/assets/icons'
TARGET = ROOT / 'www/phpledger/includes/icons.php'

icons = {}
for file in sorted(SOURCE.glob('*.svg')):
    svg = file.read_text(encoding='utf-8')
    body = re.search(r'<svg[^>]*>(.*)</svg>', svg, re.S)
    if not body:
        raise SystemExit(f'{file.name}: no <svg> element')
    paths = []
    for element in re.findall(r'<(?:path|circle|rect|line|polyline|polygon|ellipse)\b[^>]*/>', body.group(1), re.S):
        # Tabler's leading transparent square only pads the artboard.
        if 'M0 0h24v24H0z' in element:
            continue
        paths.append(re.sub(r'\s+', ' ', element).replace(' />', '/>').strip())
    if not paths:
        raise SystemExit(f'{file.name}: no drawing elements')
    icons[file.stem] = ''.join(paths)

lines = ['<?php', 'declare(strict_types=1);', '',
         '// Generated by tools/build-icons.py from public/assets/icons (Tabler Icons, MIT; see',
         '// public/assets/icons/LICENSE.txt). Do not edit by hand: change the SVG file and rebuild.',
         'return [']
for name, markup in icons.items():
    lines.append("    '%s' => '%s'," % (name, markup.replace("'", "\\'")))
lines.append('];')
TARGET.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'wrote {TARGET.relative_to(ROOT)} with {len(icons)} icons')
